"""AWS architecture scenarios — 24 scenarios × 25 prompts = 600 examples."""
from .helpers import N, E, D

# Shortcuts for common cloud node defaults
def AW(nid, shape, x, y, label, accent, **kw):
    return N(nid, shape, x, y, 90, 90, label, "#FFFFFF", "#E5E7EB",
             sw=1, tc="#111827", fs=11, fw="600", cloud=True, accent=accent, **kw)

COMPUTE  = "#FF9900"
STORAGE  = "#3F8624"
DATABASE = "#3B48CC"
NET      = "#8C4FFF"
MSG      = "#E7157B"
SEC      = "#DD344C"
MGMT     = "#E7157B"

def zone(nid, x, y, w, h, fill, stroke, zi=0, op=0.5):
    return N(nid, "rect", x, y, w, h, "", fill, stroke, sw=1, zi=zi, op=op)

def zlabel(nid, x, y, text, tc):
    return N(nid, "textbox", x, y, 260, 20, text, "transparent", "transparent",
             sw=0, tc=tc, fs=10, fw="700", zi=1)

SCENARIOS = []

# ── A01  Simple EC2 + RDS ────────────────────────────────────────────────────────
SCENARIOS.append({
    "diagram": D("d_a01", "Simple EC2 + RDS",
        nodes=[
            N("n_users", "pill",      20, 95, 120, 50, "Users", "#DBEAFE","#3B82F6", tc="#1E3A8A", fw="700", zi=1),
            AW("n_ec2",  "aws-ec2",  220, 80, "EC2",   COMPUTE, zi=1),
            AW("n_rds",  "aws-rds",  420, 80, "RDS",   DATABASE, zi=1),
        ],
        edges=[
            E("e01","n_users","n_ec2","right","left", anim=True,  color="#3B82F6"),
            E("e02","n_ec2",  "n_rds","right","left", color=DATABASE),
        ], vx=10, vy=80, vz=1.2),
    "prompts": [
        "Create a simple AWS architecture with EC2 and RDS",
        "Draw a minimal AWS setup: users, EC2 instance, RDS database",
        "AWS diagram: single EC2 server connected to RDS",
        "Simple AWS monolith: EC2 app server plus RDS database",
        "Show a basic AWS deployment with one EC2 and one database",
        "Minimal AWS architecture diagram",
        "EC2 + RDS architecture diagram",
        "Simple AWS app: EC2 instance reads and writes to RDS",
        "Draw users connecting to EC2 which connects to RDS database",
        "Basic AWS setup: user traffic hits EC2, EC2 uses RDS",
        "Create an AWS diagram with just compute and database",
        "Show a simple EC2-based application with RDS storage",
        "AWS: users → EC2 instance → RDS database",
        "Diagram a single-server AWS deployment with managed database",
        "Simple AWS monolith: one server, one database",
        "Draw the simplest possible AWS architecture with EC2 and RDS",
        "EC2 app server with RDS backend database diagram",
        "AWS architecture: users access EC2, EC2 stores data in RDS",
        "Create a 3-node AWS diagram: users, EC2, RDS",
        "Show a basic AWS deployment suitable for a small application",
        "Simple AWS: just EC2 and RDS, nothing else",
        "Minimal AWS production setup with compute and database",
        "Diagram a single-tier AWS application: EC2 + RDS",
        "AWS diagram showing users hitting EC2 and EC2 reading from RDS",
        "Draw a bare minimum AWS architecture for a web app",
    ]
})

# ── A02  EC2 + RDS + ElastiCache ─────────────────────────────────────────────────
SCENARIOS.append({
    "diagram": D("d_a02", "EC2 + RDS + ElastiCache",
        nodes=[
            N("n_users", "pill",      20,120, 120, 50, "Users", "#DBEAFE","#3B82F6", tc="#1E3A8A", fw="700", zi=1),
            AW("n_ec2",  "aws-ec2",  220,110, "EC2",         COMPUTE,  zi=1),
            AW("n_rds",  "aws-rds",  440,  30, "RDS",        DATABASE, zi=1),
            AW("n_ec",   "aws-elasticache",440,200,"ElastiCache",DATABASE,zi=1),
        ],
        edges=[
            E("e01","n_users","n_ec2","right","left",  anim=True, color="#3B82F6"),
            E("e02","n_ec2",  "n_rds","right","left",  color=DATABASE),
            E("e03","n_ec2",  "n_ec", "right","left",  color=DATABASE, es="dashed"),
        ], vx=10, vy=60),
    "prompts": [
        "Create an AWS architecture with EC2, RDS, and ElastiCache",
        "Draw a cached AWS app: EC2, RDS database, ElastiCache",
        "AWS diagram with EC2 instance, RDS, and Redis cache",
        "Show an AWS setup with compute, database, and caching layer",
        "EC2 + RDS + ElastiCache architecture diagram",
        "AWS app with caching: users → EC2 → RDS and ElastiCache",
        "Diagram an AWS deployment with a Redis caching layer",
        "Show EC2 reading from ElastiCache for hot data and RDS for persistent data",
        "AWS architecture with EC2, relational database, and in-memory cache",
        "Create an AWS diagram for a cached web application",
        "Draw users connecting to EC2 which uses both RDS and ElastiCache",
        "EC2 with dual data stores: RDS for persistence, ElastiCache for caching",
        "AWS: users → EC2 → RDS (solid) + ElastiCache (dashed)",
        "Simple cached AWS setup: one server, one DB, one cache",
        "Show an AWS app that caches database results in ElastiCache",
        "AWS architecture diagram with ElastiCache caching layer",
        "EC2 app backed by RDS and ElastiCache on AWS",
        "Draw a 4-node AWS diagram with caching",
        "Create an AWS diagram: users hit EC2, EC2 uses RDS and ElastiCache",
        "AWS deployment with application caching using ElastiCache",
        "Show EC2 with both a database (RDS) and a cache (ElastiCache)",
        "AWS: compute layer + relational DB + in-memory cache",
        "Diagram an AWS application using RDS for storage and ElastiCache for session cache",
        "AWS setup with three backend services: EC2, RDS, ElastiCache",
        "Create a simple cached web app architecture on AWS",
    ]
})

# ── A03  CloudFront + S3 Static Site ─────────────────────────────────────────────
SCENARIOS.append({
    "diagram": D("d_a03", "CloudFront + S3 Static Site",
        nodes=[
            N("n_users","pill",     20, 95, 120, 50, "Users","#DBEAFE","#3B82F6",tc="#1E3A8A",fw="700",zi=1),
            AW("n_r53", "aws-route53",  200, 80, "Route 53",   NET,     zi=1),
            AW("n_cf",  "aws-cloudfront",380,80, "CloudFront", NET,     zi=1),
            AW("n_s3",  "aws-s3",       560, 80, "S3 Bucket",  STORAGE, zi=1),
        ],
        edges=[
            E("e01","n_users","n_r53","right","left"),
            E("e02","n_r53",  "n_cf", "right","left", label="DNS",  color=NET),
            E("e03","n_cf",   "n_s3", "right","left", label="origin",color=STORAGE, es="dashed"),
        ], vx=10, vy=80),
    "prompts": [
        "Create a CloudFront + S3 static site architecture diagram",
        "Draw an AWS static website hosting diagram",
        "AWS static site: Route53, CloudFront, S3",
        "Show how to host a static website on AWS using S3 and CloudFront",
        "Static site AWS diagram: users → Route53 → CloudFront → S3",
        "CloudFront CDN serving static assets from S3",
        "AWS static hosting architecture: DNS, CDN, object storage",
        "Diagram an AWS static website with CloudFront distribution",
        "Show a JAMstack AWS deployment: Route53, CloudFront, S3",
        "Create an AWS diagram for hosting a static website",
        "S3 + CloudFront static site with Route53 DNS",
        "AWS CDN architecture for a static website",
        "Draw AWS static site hosting: DNS resolution, CDN, origin bucket",
        "CloudFront serving a React/Vue SPA from S3",
        "Show the AWS static website architecture with CDN caching",
        "Route53 → CloudFront → S3 architecture diagram",
        "Create an AWS diagram for a static site with global CDN",
        "AWS: users hit Route53, resolve to CloudFront, CloudFront pulls from S3",
        "Diagram AWS static hosting with CloudFront as CDN",
        "Show an AWS architecture for hosting a single-page application",
        "Static site hosting: Route53 DNS → CloudFront edge → S3 origin",
        "AWS CDN + S3 architecture for frontend hosting",
        "Draw a 4-node AWS diagram for static website delivery",
        "AWS static hosting with CloudFront caching and S3 origin",
        "Show Route53, CloudFront, and S3 working together for static sites",
    ]
})

# ── A04  Serverless API: API Gateway + Lambda + DynamoDB ─────────────────────────
SCENARIOS.append({
    "diagram": D("d_a04", "Serverless API",
        nodes=[
            N("n_client","pill",     20, 95, 120, 50, "Client","#DBEAFE","#3B82F6",tc="#1E3A8A",fw="700",zi=1),
            AW("n_apigw","aws-apigateway",200,80,"API Gateway",NET,     zi=1),
            AW("n_lmb",  "aws-lambda",    380,80,"Lambda",     COMPUTE, zi=1),
            AW("n_ddb",  "aws-dynamodb",  560,80,"DynamoDB",   DATABASE,zi=1),
        ],
        edges=[
            E("e01","n_client","n_apigw","right","left", anim=True, color=NET),
            E("e02","n_apigw", "n_lmb",  "right","left", label="invoke",anim=True,color=COMPUTE),
            E("e03","n_lmb",   "n_ddb",  "right","left", label="read/write",color=DATABASE),
        ], vx=10, vy=80),
    "prompts": [
        "Create a serverless API architecture on AWS",
        "Draw an API Gateway + Lambda + DynamoDB architecture",
        "AWS serverless: API Gateway, Lambda function, DynamoDB",
        "Show a serverless REST API on AWS",
        "Serverless API diagram: client → API Gateway → Lambda → DynamoDB",
        "AWS Lambda API with DynamoDB storage",
        "Diagram a serverless microservice on AWS",
        "Show API Gateway invoking Lambda which reads from DynamoDB",
        "Create an AWS serverless backend diagram",
        "API Gateway + Lambda + DynamoDB serverless stack",
        "Draw an AWS serverless API flow",
        "Serverless REST API: API GW routes to Lambda, Lambda uses DynamoDB",
        "AWS: API Gateway as entry point, Lambda for logic, DynamoDB for storage",
        "Create a serverless AWS architecture with three services",
        "Show a simple serverless API using managed AWS services",
        "AWS serverless: client calls API Gateway, Lambda handles request, DynamoDB stores data",
        "Diagram the serverless API pattern on AWS",
        "API Gateway triggers Lambda which persists to DynamoDB",
        "Create an AWS diagram for a serverless CRUD API",
        "Serverless backend: API GW → Lambda → DynamoDB read/write",
        "Draw a 4-node AWS serverless API diagram",
        "Show a Lambda-based API with DynamoDB as the data store",
        "AWS API: managed gateway, function-as-a-service, NoSQL database",
        "Serverless API Gateway + Lambda + DynamoDB architecture diagram",
        "Show the serverless pattern: API Gateway → Lambda → DynamoDB",
    ]
})

# ── A05  ECS 3-tier: ALB + ECS + Aurora ──────────────────────────────────────────
SCENARIOS.append({
    "diagram": D("d_a05", "ECS 3-tier Architecture",
        nodes=[
            zone("z_internet","0",  40, 800, 130, "#EFF6FF","#BFDBFE"),
            zone("z_public",  "0", 190, 800, 150, "#F5F3FF","#DDD6FE"),
            zone("z_compute", "0", 360, 800, 160, "#FFF7ED","#FED7AA"),
            zone("z_data",    "0", 540, 800, 150, "#F0FDF4","#BBF7D0"),
            zlabel("l_int", 8,  43,"INTERNET",     "#93C5FD"),
            zlabel("l_pub", 8, 193,"PUBLIC SUBNET", "#C4B5FD"),
            zlabel("l_cmp", 8, 363,"COMPUTE",       "#FCA5A5"),
            zlabel("l_dat", 8, 543,"DATA",          "#6EE7B7"),
            N("n_users","pill",     20,  85, 120, 50, "Users","#DBEAFE","#3B82F6",tc="#1E3A8A",fw="700",zi=2),
            AW("n_r53", "aws-route53",  180, 70, "Route 53",  NET,     zi=2),
            AW("n_cf",  "aws-cloudfront",350,70, "CloudFront",NET,     zi=2),
            AW("n_alb", "aws-elb",      520,70, "ALB",       NET,     zi=2),
            AW("n_ecs", "aws-ecs",      690,70, "ECS Service",COMPUTE,zi=2),
            AW("n_aur", "aws-aurora",   860,70, "Aurora",    DATABASE,zi=2),
        ],
        edges=[
            E("e01","n_users","n_r53","right","left"),
            E("e02","n_r53",  "n_cf", "right","left",label="DNS",  color=NET),
            E("e03","n_cf",   "n_alb","right","left",label="HTTP", color=NET,anim=True),
            E("e04","n_alb",  "n_ecs","right","left",color=COMPUTE,anim=True),
            E("e05","n_ecs",  "n_aur","right","left",color=DATABASE),
        ], vx=10, vy=30, vz=0.95),
    "prompts": [
        "Create a 3-tier AWS architecture with ECS and Aurora",
        "Draw an AWS ECS 3-tier web application diagram",
        "AWS: Route53 → CloudFront → ALB → ECS → Aurora",
        "3-tier AWS architecture using containers on ECS",
        "Show a containerized AWS web app: Route53, CloudFront, ALB, ECS, Aurora",
        "ECS-based 3-tier architecture on AWS",
        "Diagram an AWS web app with load balancer, ECS containers, and Aurora database",
        "AWS 3-tier: internet → public subnet (CF, ALB) → compute (ECS) → data (Aurora)",
        "Create an AWS architecture with subnet zones and ECS backend",
        "Show the classic 3-tier AWS deployment using ECS",
        "AWS container platform: CloudFront CDN, Application Load Balancer, ECS, Aurora DB",
        "3-tier web app on AWS with ECS for compute and Aurora for database",
        "Draw an AWS architecture using ECS for containerized backend and Aurora for data",
        "AWS diagram: Route53 DNS, CloudFront CDN, ALB, ECS container service, Aurora MySQL",
        "Containerized 3-tier AWS app with zone boundaries",
        "AWS web application: CDN → load balancer → ECS containers → managed database",
        "Show a production AWS setup with Route53, CDN, load balancer, containers, Aurora",
        "Create a 3-tier AWS diagram with internet, public, compute, and data zones",
        "ECS deployment with Aurora: users → DNS → CDN → ALB → containers → DB",
        "AWS 3-tier architecture diagram with zone backgrounds",
        "Diagram an AWS app with CloudFront, ALB, ECS cluster, and Aurora database",
        "Show how traffic flows from users to Aurora through 3 tiers on AWS",
        "AWS production architecture: R53 + CloudFront + ALB + ECS + Aurora",
        "3-tier AWS app with subnets labeled: internet, public, compute, data",
        "Create an AWS ECS architecture with proper networking zones",
    ]
})

# ── A06  Serverless + Event-driven: API GW + Lambda + SNS + SQS ──────────────────
SCENARIOS.append({
    "diagram": D("d_a06", "Serverless Event-Driven API",
        nodes=[
            N("n_client","pill",    20,175, 120, 50,"Client","#DBEAFE","#3B82F6",tc="#1E3A8A",fw="700",zi=1),
            AW("n_apigw","aws-apigateway",200,160,"API Gateway",NET,    zi=1),
            AW("n_lmb",  "aws-lambda",    380,160,"Lambda",    COMPUTE, zi=1),
            AW("n_ddb",  "aws-dynamodb",  560, 60,"DynamoDB",  DATABASE,zi=1),
            AW("n_sns",  "aws-sns",       560,260,"SNS Topic", MSG,     zi=1),
            AW("n_sqs",  "aws-sqs",       740,260,"SQS Queue", MSG,     zi=1),
            AW("n_lmb2", "aws-lambda",    920,260,"Worker Lambda",COMPUTE,zi=1),
            AW("n_dlq",  "aws-sqs",       920, 80,"DLQ",       MSG,     zi=1),
        ],
        edges=[
            E("e01","n_client","n_apigw","right","left",anim=True,color=NET),
            E("e02","n_apigw", "n_lmb",  "right","left",label="invoke",anim=True,color=COMPUTE),
            E("e03","n_lmb",   "n_ddb",  "right","left",label="write",color=DATABASE),
            E("e04","n_lmb",   "n_sns",  "bottom","top",label="publish",color=MSG,anim=True),
            E("e05","n_sns",   "n_sqs",  "right","left",label="fan-out",color=MSG,anim=True),
            E("e06","n_sqs",   "n_lmb2", "right","left",label="trigger",color=COMPUTE,anim=True),
            E("e07","n_sqs",   "n_dlq",  "top","bottom",label="failed",color="#F87171",es="dashed"),
        ], vx=10, vy=40, vz=0.85),
    "prompts": [
        "Create an AWS serverless event-driven architecture",
        "Draw an API Gateway + Lambda + SNS + SQS event-driven AWS diagram",
        "AWS serverless: API GW → Lambda → DynamoDB + SNS → SQS → worker Lambda",
        "Show a serverless AWS app that publishes events to SNS",
        "Serverless event-driven diagram: API Gateway, Lambda, SNS, SQS, worker",
        "AWS: API call triggers Lambda, Lambda writes to DDB and publishes to SNS",
        "Diagram a serverless event-driven backend on AWS",
        "API Gateway calls Lambda which stores in DynamoDB and publishes to SNS/SQS",
        "Create an AWS serverless architecture with event bus",
        "Show fan-out pattern: Lambda publishes to SNS, SNS fans out to SQS queues",
        "Serverless AWS: HTTP request → API GW → Lambda → DynamoDB + SNS → SQS → worker",
        "AWS event-driven: API triggers Lambda, Lambda emits events to SNS/SQS pipeline",
        "Draw a serverless AWS app with event publishing and async processing",
        "Create an AWS serverless diagram with DLQ for failed messages",
        "Show AWS serverless event-driven architecture with two Lambda functions",
        "Lambda publishes to SNS, SNS fans out to SQS, SQS triggers worker Lambda",
        "Serverless event-driven AWS: write path and async event path",
        "AWS diagram: API Gateway entry, Lambda processor, SNS broker, SQS queue, worker",
        "Show a serverless AWS architecture combining synchronous API and async events",
        "Create a serverless AWS backend with event pipeline and dead-letter queue",
        "AWS: API GW → Lambda → DynamoDB write + SNS publish → SQS → worker Lambda",
        "Diagram serverless event-driven AWS with DLQ for failed SQS messages",
        "Show how Lambda can both write to a database and emit events asynchronously",
        "Serverless AWS with API Gateway, two Lambda functions, SNS, SQS, DynamoDB",
        "Create an event-driven serverless diagram with fan-out and DLQ on AWS",
    ]
})

# ── A07  EKS Cluster ─────────────────────────────────────────────────────────────
SCENARIOS.append({
    "diagram": D("d_a07", "EKS Kubernetes Cluster",
        nodes=[
            N("n_users","pill",     20,175, 120, 50,"Users","#DBEAFE","#3B82F6",tc="#1E3A8A",fw="700",zi=1),
            AW("n_r53", "aws-route53",   200,160,"Route 53",  NET,    zi=1),
            AW("n_alb", "aws-elb",       380,160,"ALB",       NET,    zi=1),
            AW("n_eks", "aws-eks",       560,160,"EKS Cluster",COMPUTE,zi=1),
            AW("n_ecr", "aws-ecs",       560, 30,"ECR",       COMPUTE,zi=1),
            AW("n_rds", "aws-rds",       740,100,"RDS",       DATABASE,zi=1),
            AW("n_ec",  "aws-elasticache",740,250,"ElastiCache",DATABASE,zi=1),
            AW("n_s3",  "aws-s3",        920,100,"S3",        STORAGE,zi=1),
            AW("n_cw",  "aws-cloudwatch",920,250,"CloudWatch",MGMT,   zi=1),
        ],
        edges=[
            E("e01","n_users","n_r53","right","left"),
            E("e02","n_r53", "n_alb","right","left",label="DNS",color=NET),
            E("e03","n_alb", "n_eks","right","left",color=COMPUTE,anim=True),
            E("e04","n_ecr", "n_eks","bottom","top",label="pull images",color=COMPUTE,es="dashed"),
            E("e05","n_eks", "n_rds","right","left",color=DATABASE),
            E("e06","n_eks", "n_ec", "right","left",color=DATABASE,es="dashed"),
            E("e07","n_eks", "n_s3", "right","top",color=STORAGE,es="dashed"),
            E("e08","n_eks", "n_cw", "right","left",label="logs",color="#D1D5DB",es="dotted"),
        ], vx=10, vy=20, vz=0.85),
    "prompts": [
        "Create an AWS EKS Kubernetes cluster architecture",
        "Draw an EKS-based AWS deployment diagram",
        "AWS EKS architecture with ALB, RDS, and ElastiCache",
        "Show a Kubernetes cluster on AWS EKS",
        "EKS cluster diagram: Route53 → ALB → EKS → RDS + ElastiCache",
        "AWS Kubernetes: EKS cluster with managed database and cache",
        "Diagram an AWS EKS deployment with container registry",
        "Show EKS pulling images from ECR and using RDS and ElastiCache",
        "Create an AWS diagram for a Kubernetes-based application",
        "EKS architecture: users → Route53 → ALB → EKS cluster → data stores",
        "AWS EKS with ECR, RDS, ElastiCache, S3, and CloudWatch",
        "Kubernetes on AWS: EKS cluster with Route53, ALB, and backend services",
        "Draw an AWS EKS deployment with monitoring",
        "Show EKS cluster connected to RDS database and ElastiCache",
        "AWS Kubernetes cluster with load balancer and multiple data services",
        "EKS-based architecture: load balancer → Kubernetes → database + cache + storage",
        "Create an AWS diagram showing EKS as the compute backbone",
        "EKS cluster with container images from ECR, data in RDS and ElastiCache",
        "AWS Kubernetes architecture with CloudWatch for observability",
        "Show a production AWS EKS setup with Route53, ALB, RDS, cache, storage",
        "Diagram AWS EKS: nodes pull from ECR, store in RDS, cache in ElastiCache",
        "AWS diagram with EKS and 5 supporting services",
        "Create an EKS architecture with logging to CloudWatch",
        "EKS Kubernetes on AWS with data layer and observability",
        "Show an AWS EKS architecture diagram with Route53 DNS and ALB ingress",
    ]
})

# ── A08  SNS Fan-out + SQS + Lambda ──────────────────────────────────────────────
SCENARIOS.append({
    "diagram": D("d_a08", "SNS Fan-out + SQS + Lambda",
        nodes=[
            AW("n_src",  "aws-ecs",     40,175,"Source Service",COMPUTE,zi=1),
            AW("n_sns",  "aws-sns",    220,175,"SNS Topic",MSG,         zi=1),
            AW("n_sqs1", "aws-sqs",    400, 60,"Orders Queue",MSG,      zi=1),
            AW("n_sqs2", "aws-sqs",    400,175,"Email Queue", MSG,      zi=1),
            AW("n_sqs3", "aws-sqs",    400,290,"Analytics Queue",MSG,   zi=1),
            AW("n_lmb1", "aws-lambda", 580, 60,"Order Lambda",COMPUTE,  zi=1),
            AW("n_lmb2", "aws-lambda", 580,175,"Email Lambda",COMPUTE,  zi=1),
            AW("n_lmb3", "aws-lambda", 580,290,"Analytics Lambda",COMPUTE,zi=1),
            AW("n_dlq",  "aws-sqs",    760, 60,"DLQ",         MSG,      zi=1),
        ],
        edges=[
            E("e01","n_src", "n_sns", "right","left",label="publish",color=MSG,anim=True),
            E("e02","n_sns", "n_sqs1","right","left",color=MSG),
            E("e03","n_sns", "n_sqs2","right","left",color=MSG),
            E("e04","n_sns", "n_sqs3","right","left",color=MSG),
            E("e05","n_sqs1","n_lmb1","right","left",color=COMPUTE,anim=True),
            E("e06","n_sqs2","n_lmb2","right","left",color=COMPUTE,anim=True),
            E("e07","n_sqs3","n_lmb3","right","left",color=COMPUTE,anim=True),
            E("e08","n_sqs1","n_dlq", "right","left",label="failed",color="#F87171",es="dashed"),
        ], vx=10, vy=20, vz=0.85),
    "prompts": [
        "Create an AWS SNS fan-out with SQS queues and Lambda consumers",
        "Draw an SNS topic fanning out to multiple SQS queues",
        "AWS pub/sub: SNS → 3 SQS queues → 3 Lambda functions",
        "Show AWS event fan-out pattern with SNS and SQS",
        "SNS fan-out diagram: one topic, three queues, three consumers",
        "AWS messaging: SNS fans out to orders, email, and analytics queues",
        "Diagram AWS SNS fan-out architecture",
        "Show an event published to SNS fanning out to 3 different SQS queues",
        "AWS event-driven: one SNS topic subscribed by multiple SQS queues",
        "Create an AWS fan-out diagram: SNS → SQS × 3 → Lambda × 3",
        "SNS publish triggers multiple independent Lambda consumers via SQS",
        "Draw AWS SNS fan-out with dead letter queue for failed messages",
        "AWS event fan-out: source service → SNS → queues → Lambda workers",
        "Show the AWS pub/sub fan-out pattern with 3 subscribers",
        "SNS topic subscribed by Orders Queue, Email Queue, Analytics Queue",
        "AWS messaging architecture: one publisher, one topic, many consumers",
        "Create a fan-out messaging diagram on AWS",
        "Show SNS fanning out to separate SQS queues for different domains",
        "AWS event bus: SNS topic → SQS queues → Lambda processors",
        "Draw a fan-out pattern where one event triggers three parallel processes",
        "AWS diagram: ECS service publishes to SNS, three queues fan out, three Lambda consumers",
        "Show how to implement fan-out messaging on AWS with SNS and SQS",
        "Create an AWS diagram with one SNS topic, 3 SQS queues, 3 Lambda functions",
        "SNS to SQS to Lambda fan-out architecture with DLQ",
        "AWS pub/sub fan-out: publish once, consume in three separate workflows",
    ]
})

# ── A09  Data Lake on AWS ─────────────────────────────────────────────────────────
SCENARIOS.append({
    "diagram": D("d_a09", "AWS Data Lake",
        nodes=[
            AW("n_src1","aws-rds",       40,160,"RDS Source",   DATABASE,zi=1),
            AW("n_src2","aws-dynamodb",  40,310,"DynamoDB",     DATABASE,zi=1),
            AW("n_lmb", "aws-lambda",   220,230,"ETL Lambda",   COMPUTE, zi=1),
            AW("n_s3r", "aws-s3",       400, 90,"Raw Zone",     STORAGE, zi=1),
            AW("n_s3p", "aws-s3",       400,230,"Processed Zone",STORAGE,zi=1),
            AW("n_s3c", "aws-s3",       400,370,"Curated Zone", STORAGE, zi=1),
            AW("n_lmb2","aws-lambda",   580,230,"Transform",    COMPUTE, zi=1),
            AW("n_cw",  "aws-cloudwatch",760,160,"CloudWatch",  MGMT,    zi=1),
            AW("n_iam", "aws-iam",       760,310,"IAM Roles",   SEC,     zi=1),
        ],
        edges=[
            E("e01","n_src1","n_lmb","right","left",  color=DATABASE),
            E("e02","n_src2","n_lmb","right","left",  color=DATABASE),
            E("e03","n_lmb","n_s3r", "right","left",  label="ingest",color=STORAGE),
            E("e04","n_s3r","n_lmb2","right","left",  color=COMPUTE),
            E("e05","n_lmb2","n_s3p","right","left",  label="transform",color=STORAGE),
            E("e06","n_s3p","n_s3c", "bottom","top",  label="curate",color=STORAGE,es="dashed"),
            E("e07","n_lmb","n_cw",  "right","left",  label="logs",color="#D1D5DB",es="dotted"),
        ], vx=10, vy=30, vz=0.85),
    "prompts": [
        "Create an AWS data lake architecture diagram",
        "Draw an AWS data lake with S3 zones and Lambda ETL",
        "AWS data lake: ingestion Lambda, raw/processed/curated S3 zones",
        "Show an AWS data lake with multiple source systems and S3 tiers",
        "AWS data lake diagram: RDS + DynamoDB sources, Lambda ETL, S3 zones",
        "Data lake on AWS with three S3 tiers: raw, processed, curated",
        "Diagram an AWS data lake architecture with ETL pipeline",
        "Show AWS data lake: ingest from multiple sources, transform with Lambda, store in S3",
        "AWS S3-based data lake with Lambda for data processing",
        "Create an AWS data lake diagram with IAM and CloudWatch",
        "AWS: multiple database sources → Lambda ETL → S3 raw zone → transform → processed zone",
        "Show a three-tier S3 data lake on AWS with Lambda transformations",
        "AWS data lake: ingest from RDS and DynamoDB, process with Lambda, store in S3 tiers",
        "Draw an AWS data lake architecture with data zones",
        "Data lake on AWS: raw zone → processed zone → curated zone in S3",
        "AWS data lake diagram with CloudWatch monitoring and IAM security",
        "Create an AWS S3 data lake with ETL Lambda functions",
        "Show how data flows from databases through Lambda into S3 data lake zones",
        "AWS data lake: two data sources, ETL Lambda, three S3 zones, monitoring",
        "Diagram an AWS data pipeline that builds a data lake in S3",
        "AWS data lake architecture with Lambda-based ingestion and transformation",
        "Show the stages of an AWS S3 data lake: raw, processed, curated",
        "Create a data lake diagram on AWS using S3, Lambda, and CloudWatch",
        "AWS data lake with RDS source, DynamoDB source, and tiered S3 storage",
        "Draw an AWS data lake pipeline from source databases to curated data",
    ]
})

# ── A10  Multi-region Active-Passive ─────────────────────────────────────────────
SCENARIOS.append({
    "diagram": D("d_a10", "Multi-region Active-Passive",
        nodes=[
            N("n_users","pill",      20,175, 120, 50,"Users","#DBEAFE","#3B82F6",tc="#1E3A8A",fw="700",zi=1),
            AW("n_r53", "aws-route53",200,160,"Route 53",NET,     zi=1),
            AW("n_cf1", "aws-cloudfront",380,60,"CF us-east-1",NET,zi=1),
            AW("n_alb1","aws-elb",      560,60,"ALB us-east-1",NET,zi=1),
            AW("n_ecs1","aws-ecs",      740,60,"ECS us-east-1",COMPUTE,zi=1),
            AW("n_aur1","aws-aurora",   920,60,"Aurora Primary",DATABASE,zi=1),
            AW("n_cf2", "aws-cloudfront",380,300,"CF eu-west-1",NET,zi=1),
            AW("n_alb2","aws-elb",      560,300,"ALB eu-west-1",NET,zi=1),
            AW("n_ecs2","aws-ecs",      740,300,"ECS eu-west-1",COMPUTE,zi=1),
            AW("n_aur2","aws-aurora",   920,300,"Aurora Replica",DATABASE,zi=1),
        ],
        edges=[
            E("e01","n_users","n_r53", "right","left"),
            E("e02","n_r53",  "n_cf1", "right","top",  label="primary",color=NET),
            E("e03","n_r53",  "n_cf2", "right","top",  label="failover",color="#9CA3AF",es="dashed"),
            E("e04","n_cf1",  "n_alb1","right","left", color=NET,anim=True),
            E("e05","n_alb1", "n_ecs1","right","left", color=COMPUTE),
            E("e06","n_ecs1", "n_aur1","right","left", color=DATABASE),
            E("e07","n_cf2",  "n_alb2","right","left", color=NET),
            E("e08","n_alb2", "n_ecs2","right","left", color=COMPUTE),
            E("e09","n_ecs2", "n_aur2","right","left", color=DATABASE),
            E("e10","n_aur1", "n_aur2","bottom","top", label="replication",color="#60A5FA",es="dashed"),
        ], vx=10, vy=20, vz=0.75),
    "prompts": [
        "Create a multi-region AWS active-passive architecture diagram",
        "Draw an AWS multi-region failover architecture",
        "AWS multi-region: primary us-east-1 and failover eu-west-1",
        "Show an AWS active-passive deployment across two regions",
        "Multi-region AWS: Route53 routes to primary or failover region",
        "AWS disaster recovery: active region with passive failover region",
        "Diagram an AWS multi-region setup with Aurora replication",
        "Show AWS two-region architecture with Route53 failover routing",
        "Create an AWS multi-region architecture with database replication",
        "AWS active-passive: primary region handles traffic, secondary on standby",
        "AWS multi-region failover: Route53 → two regions (ECS + Aurora in each)",
        "Show two AWS regions with Aurora cross-region replication",
        "Diagram AWS disaster recovery: active region, passive replica, R53 failover",
        "AWS multi-region with Route53, CloudFront, ALB, ECS, Aurora in two regions",
        "Create a multi-region AWS diagram showing replication and failover",
        "Show how Route53 routes traffic to primary or secondary AWS region",
        "AWS multi-region active-passive: same stack in two regions, Aurora replication",
        "Diagram AWS multi-region setup for high availability",
        "Two-region AWS architecture with identical stacks and Aurora replication",
        "AWS DR: us-east-1 primary with eu-west-1 passive failover",
        "Create an AWS diagram showing geographic redundancy",
        "Multi-region AWS: primary stack + passive stack + cross-region DB replication",
        "Show AWS multi-region deployment with Route53 health check routing",
        "AWS active-passive disaster recovery diagram with two identical regions",
        "Draw a multi-region AWS architecture with database replication between regions",
    ]
})

# ── A11  Full Production AWS Platform (medium complexity) ─────────────────────────
SCENARIOS.append({
    "diagram": D("d_a11", "AWS Production Platform",
        nodes=[
            zone("z_int","0",  40, 970, 130, "#EFF6FF","#BFDBFE"),
            zone("z_pub","0", 190, 970, 150, "#F5F3FF","#DDD6FE"),
            zone("z_cmp","0", 360, 760, 160, "#FFF7ED","#FED7AA"),
            zone("z_msg","0", 540, 760, 150, "#FEFCE8","#FDE68A"),
            zone("z_dat","0", 710, 970, 160, "#F0FDF4","#BBF7D0"),
            zlabel("l_int", 8, 43,"INTERNET EDGE","#93C5FD"),
            zlabel("l_pub", 8,193,"PUBLIC SUBNETS","#C4B5FD"),
            zlabel("l_cmp", 8,363,"COMPUTE","#FCA5A5"),
            zlabel("l_msg", 8,543,"MESSAGING","#FCD34D"),
            zlabel("l_dat", 8,713,"DATA","#6EE7B7"),
            N("n_users","pill",     20, 85, 120, 50,"Users","#DBEAFE","#3B82F6",tc="#1E3A8A",fw="700",zi=2),
            AW("n_r53", "aws-route53",  200, 70,"Route 53",  NET,     zi=2),
            AW("n_cf",  "aws-cloudfront",380,70,"CloudFront",NET,     zi=2),
            AW("n_s3s", "aws-s3",       560, 70,"Static S3", STORAGE, zi=2),
            AW("n_apigw","aws-apigateway",200,230,"API Gateway",NET,  zi=2),
            AW("n_alb", "aws-elb",       380,230,"ALB",      NET,     zi=2),
            AW("n_lmb", "aws-lambda",    200,390,"Lambda",   COMPUTE, zi=2),
            AW("n_ecs", "aws-ecs",       380,390,"ECS API",  COMPUTE, zi=2),
            AW("n_sns", "aws-sns",       200,560,"SNS",      MSG,     zi=2),
            AW("n_sqs", "aws-sqs",       380,560,"SQS",      MSG,     zi=2),
            AW("n_aur", "aws-aurora",    200,730,"Aurora",   DATABASE,zi=2),
            AW("n_ec",  "aws-elasticache",380,730,"ElastiCache",DATABASE,zi=2),
            AW("n_ddb", "aws-dynamodb",  560,730,"DynamoDB", DATABASE,zi=2),
            AW("n_s3d", "aws-s3",        740,730,"Data Lake S3",STORAGE,zi=2),
            AW("n_cw",  "aws-cloudwatch",740,390,"CloudWatch",MGMT,   zi=2),
            AW("n_iam", "aws-iam",        740,560,"IAM",     SEC,     zi=2),
        ],
        edges=[
            E("e01","n_users","n_r53",  "right","left"),
            E("e02","n_r53",  "n_cf",   "right","left",label="DNS",color=NET),
            E("e03","n_cf",   "n_s3s",  "right","left",label="static",color=STORAGE,es="dashed"),
            E("e04","n_cf",   "n_apigw","bottom","top",label="REST",  color=NET,anim=True),
            E("e05","n_cf",   "n_alb",  "bottom","top",label="web",   color=NET,anim=True),
            E("e06","n_apigw","n_lmb",  "bottom","top",label="invoke",color=COMPUTE,anim=True),
            E("e07","n_alb",  "n_ecs",  "bottom","top",color=COMPUTE),
            E("e08","n_lmb",  "n_sns",  "bottom","top",label="emit",  color=MSG),
            E("e09","n_ecs",  "n_sns",  "bottom","top",color=MSG),
            E("e10","n_sns",  "n_sqs",  "right","left",label="fan-out",color=MSG,anim=True),
            E("e11","n_lmb",  "n_aur",  "bottom","top",color=DATABASE),
            E("e12","n_ecs",  "n_ec",   "bottom","top",label="cache", color=DATABASE,es="dashed"),
            E("e13","n_sqs",  "n_ddb",  "bottom","top",color=DATABASE),
            E("e14","n_lmb",  "n_s3d",  "bottom","top",label="events",color=STORAGE,es="dashed"),
            E("e15","n_ecs",  "n_cw",   "right","left",label="metrics",color="#D1D5DB",es="dotted"),
        ], vx=10, vy=20, vz=0.7),
    "prompts": [
        "Create a comprehensive AWS production platform diagram",
        "Draw a full AWS production architecture",
        "AWS production platform: Route53, CloudFront, ALB, API Gateway, Lambda, ECS, SNS, SQS, Aurora, DynamoDB",
        "Show a complete AWS production deployment with all layers",
        "Full AWS platform: internet edge, public subnets, compute, messaging, data layers",
        "Comprehensive AWS architecture diagram with zone boundaries",
        "AWS production: CDN, load balancer, containers, Lambda, event bus, databases",
        "Show an enterprise AWS architecture with multiple services",
        "Complete AWS platform diagram with Route53 to data layer",
        "AWS: web app backend with API Gateway, ECS, Lambda, SNS/SQS, Aurora, ElastiCache, DynamoDB",
        "Draw a full production AWS setup with IAM, CloudWatch, and 5 data services",
        "Enterprise AWS platform with compute, messaging, and data layers",
        "Full AWS production: CloudFront CDN, ALB, API Gateway, Lambda, ECS, SNS, SQS, Aurora, DynamoDB, S3",
        "Create a large AWS architecture diagram with zone labels",
        "AWS production platform with all major service categories",
        "Show a complex AWS deployment with both ECS containers and Lambda functions",
        "AWS platform diagram: static site, API, workers, databases, messaging",
        "Comprehensive AWS: Route53 → CF → API GW + ALB → Lambda + ECS → SNS/SQS → Aurora + DDB",
        "Create a full AWS architecture with networking, compute, messaging, data layers",
        "Show a production AWS platform with CloudWatch monitoring and IAM security",
        "AWS enterprise architecture: CDN, gateway, containers, serverless, events, data",
        "Draw a detailed AWS production platform with six zones",
        "Full AWS diagram with EC2-less architecture using ECS and Lambda",
        "AWS production: internet tier, public subnet, compute, async, data, observability",
        "Comprehensive AWS architecture with CloudFront, API Gateway, ECS, Lambda, SNS, SQS, and databases",
    ]
})

# ── A12  Lambda Monolith ──────────────────────────────────────────────────────────
SCENARIOS.append({
    "diagram": D("d_a12", "Lambda Monolith",
        nodes=[
            N("n_client","pill",    20, 95, 120, 50,"Client","#DBEAFE","#3B82F6",tc="#1E3A8A",fw="700",zi=1),
            AW("n_apigw","aws-apigateway",200,80,"API Gateway",NET,    zi=1),
            AW("n_lmb",  "aws-lambda",    380,80,"Lambda Monolith",COMPUTE,zi=1),
            AW("n_rds",  "aws-rds",       560, 0,"RDS",       DATABASE,zi=1),
            AW("n_s3",   "aws-s3",        560,160,"S3",       STORAGE, zi=1),
            AW("n_cw",   "aws-cloudwatch",740, 80,"CloudWatch",MGMT,   zi=1),
        ],
        edges=[
            E("e01","n_client","n_apigw","right","left",anim=True,color=NET),
            E("e02","n_apigw", "n_lmb",  "right","left",label="invoke",color=COMPUTE,anim=True),
            E("e03","n_lmb",   "n_rds",  "right","left",color=DATABASE),
            E("e04","n_lmb",   "n_s3",   "right","left",color=STORAGE,es="dashed"),
            E("e05","n_lmb",   "n_cw",   "right","left",label="logs",color="#D1D5DB",es="dotted"),
        ], vx=10, vy=60),
    "prompts": [
        "Create an AWS Lambda monolith architecture diagram",
        "Draw a single Lambda function handling all API routes",
        "AWS Lambda monolith: API Gateway → Lambda → RDS + S3",
        "Show a monolithic Lambda function backed by RDS and S3",
        "Lambda monolith AWS diagram",
        "AWS: API Gateway routes all traffic to a single Lambda function",
        "Diagram a Lambda-based monolith with RDS database and S3 storage",
        "Show a simple AWS serverless monolith",
        "Lambda monolith: one function handles everything, stores in RDS, uploads to S3",
        "Create a single-Lambda AWS backend diagram",
        "AWS monolith Lambda with RDS for data and S3 for files",
        "Show a Lambda function acting as a monolithic backend",
        "API Gateway + single Lambda + RDS + S3 architecture",
        "Draw a serverless monolith on AWS with Lambda",
        "Lambda monolith with CloudWatch logging",
        "AWS: one Lambda function doing all the work with RDS and S3",
        "Simple AWS serverless: API GW → Lambda → database + file storage + monitoring",
        "Create a minimal AWS serverless diagram with one Lambda function",
        "Lambda function connected to RDS, S3, and CloudWatch",
        "Show the Lambda monolith anti-pattern on AWS",
        "AWS diagram: API Gateway → Lambda → RDS (solid) + S3 (dashed) + CloudWatch (dotted)",
        "Single Lambda handling requests, using RDS for storage and S3 for files",
        "Draw an AWS Lambda backend with database and object storage",
        "Lambda monolith AWS architecture with logging",
        "Create an AWS serverless backend with Lambda as the single entry point",
    ]
})

# ── A13  Static Site + Serverless API ────────────────────────────────────────────
SCENARIOS.append({
    "diagram": D("d_a13", "Static Site + Serverless API",
        nodes=[
            N("n_users","pill",     20,175, 120, 50,"Users","#DBEAFE","#3B82F6",tc="#1E3A8A",fw="700",zi=1),
            AW("n_r53", "aws-route53",  200,160,"Route 53",  NET,     zi=1),
            AW("n_cf",  "aws-cloudfront",380,160,"CloudFront",NET,    zi=1),
            AW("n_s3",  "aws-s3",       560, 60,"Frontend S3",STORAGE,zi=1),
            AW("n_apigw","aws-apigateway",560,260,"API Gateway",NET,  zi=1),
            AW("n_lmb", "aws-lambda",   740,260,"Lambda",    COMPUTE, zi=1),
            AW("n_ddb", "aws-dynamodb", 920,260,"DynamoDB",  DATABASE,zi=1),
        ],
        edges=[
            E("e01","n_users","n_r53", "right","left"),
            E("e02","n_r53",  "n_cf",  "right","left",label="DNS",color=NET),
            E("e03","n_cf",   "n_s3",  "right","left",label="static",color=STORAGE,es="dashed"),
            E("e04","n_cf",   "n_apigw","right","left",label="API",  color=NET,anim=True),
            E("e05","n_apigw","n_lmb", "right","left",label="invoke",color=COMPUTE,anim=True),
            E("e06","n_lmb",  "n_ddb", "right","left",color=DATABASE),
        ], vx=10, vy=50, vz=0.9),
    "prompts": [
        "Create an AWS static site with serverless API backend",
        "Draw a React SPA on S3 with a serverless Lambda API",
        "AWS JAMstack: CloudFront + S3 frontend + API Gateway + Lambda + DynamoDB",
        "Show a static site with a separate serverless API on AWS",
        "Frontend on S3, backend serverless API: Route53, CloudFront, S3, API GW, Lambda, DynamoDB",
        "AWS JAMstack architecture diagram",
        "Static frontend in S3, API in Lambda, data in DynamoDB",
        "Show how a SPA on S3 calls a Lambda API on AWS",
        "AWS: CloudFront serves static files from S3 and proxies API calls to API Gateway",
        "Create an AWS diagram for a decoupled frontend and serverless backend",
        "JAMstack on AWS: S3 static site, Lambda API, DynamoDB",
        "AWS architecture: React app in S3, REST API via API Gateway + Lambda, NoSQL in DynamoDB",
        "Draw a static website + serverless API combo on AWS",
        "CloudFront routing: static assets to S3, API calls to API Gateway",
        "AWS SPA architecture: frontend on S3, API on Lambda, storage in DynamoDB",
        "Show a full-stack AWS serverless deployment",
        "AWS: Route53 → CloudFront → S3 for static files → API GW → Lambda → DynamoDB for API",
        "Create an AWS diagram showing separation of frontend and backend",
        "JAMstack AWS: CloudFront CDN, S3 origin, serverless API backend",
        "Show AWS architecture for a React frontend with serverless Node.js API",
        "AWS static + serverless: CF routes static to S3 and API to Lambda",
        "Frontend hosted on S3, API powered by Lambda, data stored in DynamoDB",
        "Create an AWS diagram for a single-page application with serverless backend",
        "AWS static site + serverless API architecture with Route53 and CloudFront",
        "Draw an AWS full-stack serverless architecture for a web app",
    ]
})

# ── A14  ECS Worker + SQS ─────────────────────────────────────────────────────────
SCENARIOS.append({
    "diagram": D("d_a14", "ECS Worker + SQS",
        nodes=[
            AW("n_apigw","aws-apigateway",40,175,"API Gateway",NET,    zi=1),
            AW("n_ecs",  "aws-ecs",       220,175,"ECS API",  COMPUTE, zi=1),
            AW("n_sqs",  "aws-sqs",       400,175,"Work Queue",MSG,    zi=1),
            AW("n_wrk1", "aws-ecs",       580, 80,"Worker A", COMPUTE, zi=1),
            AW("n_wrk2", "aws-ecs",       580,270,"Worker B", COMPUTE, zi=1),
            AW("n_dlq",  "aws-sqs",       760, 80,"DLQ",      MSG,     zi=1),
            AW("n_rds",  "aws-rds",       760,270,"RDS",      DATABASE,zi=1),
            AW("n_s3",   "aws-s3",        940,175,"S3",       STORAGE, zi=1),
        ],
        edges=[
            E("e01","n_apigw","n_ecs",  "right","left",anim=True,color=NET),
            E("e02","n_ecs",  "n_sqs",  "right","left",label="enqueue",color=MSG,anim=True),
            E("e03","n_sqs",  "n_wrk1", "right","left",color=COMPUTE,anim=True),
            E("e04","n_sqs",  "n_wrk2", "right","left",color=COMPUTE,anim=True),
            E("e05","n_sqs",  "n_dlq",  "top","bottom",label="failed",color="#F87171",es="dashed"),
            E("e06","n_wrk1", "n_rds",  "right","top",color=DATABASE),
            E("e07","n_wrk2", "n_s3",   "right","left",color=STORAGE),
        ], vx=10, vy=50, vz=0.85),
    "prompts": [
        "Create an AWS ECS worker pattern with SQS queue",
        "Draw an AWS architecture: API ECS service enqueues work, worker ECS services consume",
        "ECS API + SQS + worker ECS containers diagram",
        "AWS worker pattern: API service → SQS queue → multiple worker services",
        "Show an ECS-based job queue pattern with SQS",
        "AWS: API Gateway → ECS → SQS → worker containers",
        "Diagram an AWS architecture where workers consume from SQS",
        "ECS worker pattern: API enqueues jobs in SQS, workers A and B consume",
        "AWS task queue: ECS API → SQS → ECS workers → RDS and S3",
        "Create an AWS worker architecture with SQS and multiple consumers",
        "API service enqueues to SQS, worker services process the jobs",
        "Show a producer-consumer pattern on AWS with ECS and SQS",
        "ECS + SQS worker architecture with DLQ for failed messages",
        "AWS job processing: API → queue → workers → database/storage",
        "Draw an AWS architecture with ECS API, SQS queue, and worker containers",
        "Producer-consumer on AWS: ECS API produces to SQS, ECS workers consume",
        "AWS worker pool: SQS queue with two ECS worker services reading from it",
        "ECS + SQS: API service places jobs in queue, workers read and process",
        "Create an AWS diagram for background job processing",
        "Show an AWS architecture with API and async worker services",
        "ECS API → SQS work queue → worker ECS services → RDS + S3 output",
        "AWS async job processing: API enqueues, workers process with DLQ on failure",
        "Draw a task queue architecture on AWS using ECS and SQS",
        "AWS: API service posts jobs to SQS, two independent worker services consume",
        "ECS worker architecture with dead-letter queue for failed jobs",
    ]
})

# ── A15  Microservices with API Gateway ───────────────────────────────────────────
SCENARIOS.append({
    "diagram": D("d_a15", "AWS Microservices",
        nodes=[
            N("n_client","pill",    20,265, 120, 50,"Client","#DBEAFE","#3B82F6",tc="#1E3A8A",fw="700",zi=1),
            AW("n_apigw","aws-apigateway",200,250,"API Gateway",NET,   zi=1),
            AW("n_alb",  "aws-elb",       380,250,"ALB",       NET,    zi=1),
            AW("n_svc1", "aws-ecs",       560, 80,"User Service",COMPUTE,zi=1),
            AW("n_svc2", "aws-ecs",       560,250,"Order Service",COMPUTE,zi=1),
            AW("n_svc3", "aws-ecs",       560,420,"Product Service",COMPUTE,zi=1),
            AW("n_rds",  "aws-rds",       740, 80,"Users DB",  DATABASE,zi=1),
            AW("n_aur",  "aws-aurora",    740,250,"Orders DB", DATABASE,zi=1),
            AW("n_ddb",  "aws-dynamodb",  740,420,"Products DB",DATABASE,zi=1),
            AW("n_sns",  "aws-sns",       920,250,"Event Bus", MSG,    zi=1),
            AW("n_cw",   "aws-cloudwatch",920, 80,"CloudWatch",MGMT,  zi=1),
        ],
        edges=[
            E("e01","n_client","n_apigw","right","left",anim=True,color=NET),
            E("e02","n_apigw", "n_alb",  "right","left",color=NET),
            E("e03","n_alb",   "n_svc1", "right","left",color=COMPUTE),
            E("e04","n_alb",   "n_svc2", "right","left",color=COMPUTE),
            E("e05","n_alb",   "n_svc3", "right","left",color=COMPUTE),
            E("e06","n_svc1",  "n_rds",  "right","left",color=DATABASE),
            E("e07","n_svc2",  "n_aur",  "right","left",color=DATABASE),
            E("e08","n_svc3",  "n_ddb",  "right","left",color=DATABASE),
            E("e09","n_svc2",  "n_sns",  "right","left",label="events",color=MSG,anim=True),
            E("e10","n_svc1",  "n_cw",   "right","left",label="metrics",color="#D1D5DB",es="dotted"),
        ], vx=10, vy=30, vz=0.8),
    "prompts": [
        "Create an AWS microservices architecture diagram",
        "Draw a microservices AWS diagram with three services",
        "AWS microservices: API Gateway → ALB → user, order, product services",
        "Show a microservices architecture on AWS with three bounded contexts",
        "Microservices on AWS: each service has its own database",
        "AWS diagram: API Gateway, load balancer, three ECS microservices, three databases",
        "Three-service AWS microservices with database-per-service pattern",
        "Show database isolation in AWS microservices",
        "AWS microservices: user service → RDS, order service → Aurora, product → DynamoDB",
        "Create an AWS microservices diagram with SNS event bus",
        "Show microservices with their own databases and shared event bus",
        "AWS: client → API GW → ALB → three ECS services → three separate databases",
        "Microservices architecture on AWS with per-service data stores",
        "Draw three AWS ECS microservices each with their own database",
        "AWS microservices with CloudWatch monitoring",
        "Order service emits events to SNS in a microservices AWS architecture",
        "Create an AWS diagram showing microservices with separate databases",
        "Show the database-per-microservice pattern on AWS",
        "AWS microservices: API GW, load balancer, user/order/product services, databases",
        "Draw an AWS microservices setup where order service publishes to event bus",
        "Microservices on AWS: three services, three DBs, SNS event bus, CloudWatch",
        "AWS three-service microservices with API Gateway entry point",
        "Create a microservices diagram on AWS with bounded context isolation",
        "Show an AWS microservices deployment with separate persistence per service",
        "AWS microservices architecture with ALB routing to domain services",
    ]
})

# ── A16  Route53 + CloudFront + ALB + ECS + RDS (full 3-tier) ────────────────────
SCENARIOS.append({
    "diagram": D("d_a16", "3-tier Web App Full Stack",
        nodes=[
            N("n_users","pill",     20,175, 120, 50,"Users","#DBEAFE","#3B82F6",tc="#1E3A8A",fw="700",zi=1),
            AW("n_r53", "aws-route53",   200,160,"Route 53",   NET,     zi=1),
            AW("n_cf",  "aws-cloudfront",380,160,"CloudFront", NET,     zi=1),
            AW("n_waf", "aws-vpc",        380, 30,"WAF",       NET,     zi=1),
            AW("n_alb", "aws-elb",        560,160,"ALB",       NET,     zi=1),
            AW("n_ecs1","aws-ecs",        740, 80,"ECS (AZ-a)",COMPUTE, zi=1),
            AW("n_ecs2","aws-ecs",        740,250,"ECS (AZ-b)",COMPUTE, zi=1),
            AW("n_aur", "aws-aurora",     920, 80,"Aurora",    DATABASE,zi=1),
            AW("n_ec",  "aws-elasticache",920,250,"ElastiCache",DATABASE,zi=1),
            AW("n_cw",  "aws-cloudwatch",1100,160,"CloudWatch",MGMT,   zi=1),
        ],
        edges=[
            E("e01","n_users","n_r53","right","left"),
            E("e02","n_r53",  "n_cf", "right","left",label="DNS",  color=NET),
            E("e03","n_cf",   "n_waf","top",  "bottom",label="filter",color=NET,es="dashed"),
            E("e04","n_cf",   "n_alb","right","left",color=NET,anim=True),
            E("e05","n_alb",  "n_ecs1","right","left",color=COMPUTE),
            E("e06","n_alb",  "n_ecs2","right","left",color=COMPUTE),
            E("e07","n_ecs1", "n_aur","right","left",color=DATABASE),
            E("e08","n_ecs1", "n_ec", "right","top",color=DATABASE,es="dashed"),
            E("e09","n_ecs2", "n_ec", "right","left",color=DATABASE,es="dashed"),
            E("e10","n_ecs1", "n_cw", "right","left",label="logs",color="#D1D5DB",es="dotted"),
        ], vx=10, vy=40, vz=0.8),
    "prompts": [
        "Create a full 3-tier AWS web app architecture",
        "Draw a complete AWS web application with Route53, CloudFront, WAF, ALB, ECS, Aurora",
        "3-tier AWS: DNS → CDN → WAF → load balancer → containers → database + cache",
        "AWS production web app with WAF, CloudFront, ALB, multi-AZ ECS, Aurora, ElastiCache",
        "Show a complete AWS web architecture with security (WAF) and caching (ElastiCache)",
        "Full stack AWS: Route53, CloudFront, WAF, ALB, ECS in two AZs, Aurora, ElastiCache",
        "AWS 3-tier web app diagram with WAF and multi-AZ containers",
        "Show an AWS web app with multiple availability zones",
        "Create an AWS diagram: CDN, WAF, load balancer, ECS containers, Aurora, cache",
        "AWS production 3-tier with Route53, CF, WAF, ALB, ECS, Aurora, ElastiCache, CloudWatch",
        "Draw a high-availability AWS 3-tier with WAF and ElastiCache",
        "3-tier AWS architecture with WAF for security and ElastiCache for caching",
        "Show multi-AZ ECS deployment behind ALB in a 3-tier AWS architecture",
        "AWS web app: users → R53 → CF → WAF → ALB → ECS (AZ-a + AZ-b) → Aurora + ElastiCache",
        "Full production AWS with WAF, CDN, containers, managed DB, and cache",
        "AWS 3-tier diagram with two ECS availability zones and Aurora database",
        "Create a complete AWS 3-tier web app with security and caching layers",
        "Show a production-grade AWS 3-tier web application",
        "AWS full-stack: Route53, CloudFront, WAF, ALB, two ECS services, Aurora, ElastiCache",
        "Draw an AWS 3-tier architecture with WAF integration",
        "Complete AWS web app with Route53 DNS, CloudFront CDN, WAF, ALB, ECS, Aurora, cache",
        "AWS architecture diagram for a production web application",
        "Production AWS web app architecture with 10 services",
        "AWS 3-tier with ElastiCache caching, WAF protection, CloudWatch monitoring",
        "Show a complete AWS web app deployment with all networking, compute, and data services",
    ]
})

# ── A17  Serverless + DynamoDB Streams ────────────────────────────────────────────
SCENARIOS.append({
    "diagram": D("d_a17", "DynamoDB Streams + Lambda",
        nodes=[
            N("n_client","pill",    20,175, 120, 50,"Client","#DBEAFE","#3B82F6",tc="#1E3A8A",fw="700",zi=1),
            AW("n_apigw","aws-apigateway",200,160,"API Gateway",NET,   zi=1),
            AW("n_lmb",  "aws-lambda",    380,160,"API Lambda",COMPUTE,zi=1),
            AW("n_ddb",  "aws-dynamodb",  560,160,"DynamoDB",  DATABASE,zi=1),
            AW("n_strm", "aws-sqs",       740,160,"DDB Stream", MSG,   zi=1),
            AW("n_proc", "aws-lambda",    920,160,"Stream Processor",COMPUTE,zi=1),
            AW("n_s3",   "aws-s3",       1100, 60,"Archive S3",STORAGE,zi=1),
            AW("n_sns",  "aws-sns",      1100,270,"SNS Alerts",MSG,    zi=1),
        ],
        edges=[
            E("e01","n_client","n_apigw","right","left",anim=True,color=NET),
            E("e02","n_apigw", "n_lmb",  "right","left",color=COMPUTE,anim=True),
            E("e03","n_lmb",   "n_ddb",  "right","left",label="write",color=DATABASE),
            E("e04","n_ddb",   "n_strm", "right","left",label="stream",color=MSG,anim=True),
            E("e05","n_strm",  "n_proc", "right","left",color=COMPUTE,anim=True),
            E("e06","n_proc",  "n_s3",   "right","top",label="archive",color=STORAGE),
            E("e07","n_proc",  "n_sns",  "right","left",label="alert",color=MSG),
        ], vx=10, vy=60, vz=0.8),
    "prompts": [
        "Create a DynamoDB Streams + Lambda architecture diagram",
        "Draw an AWS DynamoDB change data capture diagram",
        "AWS: writes to DynamoDB trigger Stream, Lambda processes stream events",
        "DynamoDB Streams processing with Lambda consumer",
        "Show DynamoDB Streams triggering a Lambda function",
        "AWS change data capture: DynamoDB writes → stream → Lambda processor",
        "DynamoDB stream to Lambda pipeline diagram",
        "AWS: API Gateway → Lambda writes to DDB, DDB stream triggers processor Lambda",
        "Show a DynamoDB change stream architecture",
        "Create an AWS diagram with DynamoDB Streams and event processing",
        "AWS CDC: DynamoDB → Streams → Lambda → archive to S3 + alerts to SNS",
        "DynamoDB Streams Lambda consumer that archives to S3 and sends alerts",
        "Show how DynamoDB change events trigger downstream processing",
        "AWS diagram: write API → DDB → stream → processor → S3 archive + SNS alerts",
        "DynamoDB CDC with Lambda processor forwarding to S3 and SNS",
        "Create an event-driven AWS architecture using DynamoDB Streams",
        "Show DynamoDB Streams as an event source for Lambda",
        "AWS: API writes to DynamoDB, change stream drives event processor",
        "DynamoDB change data capture pipeline: API → DDB → stream → Lambda → S3/SNS",
        "Draw an AWS architecture leveraging DynamoDB Streams for event processing",
        "CDC pipeline on AWS: DynamoDB writes → stream trigger → Lambda → archive + notify",
        "AWS DynamoDB Streams diagram: capture changes and trigger downstream actions",
        "Show DynamoDB stream events being processed by Lambda for archival and alerts",
        "AWS event-driven with DynamoDB Streams as the event source",
        "Create an AWS diagram showing DynamoDB Streams triggering downstream Lambda",
    ]
})

# ── A18  Cognito + API Gateway + Lambda ───────────────────────────────────────────
SCENARIOS.append({
    "diagram": D("d_a18", "Auth with Cognito",
        nodes=[
            N("n_users","pill",    20,175, 120, 50,"Users","#DBEAFE","#3B82F6",tc="#1E3A8A",fw="700",zi=1),
            AW("n_cog",  "aws-iam",       200,160,"Cognito",    SEC,    zi=1),
            AW("n_apigw","aws-apigateway",380,160,"API Gateway",NET,    zi=1),
            AW("n_lmb",  "aws-lambda",    560,160,"Lambda",     COMPUTE,zi=1),
            AW("n_ddb",  "aws-dynamodb",  740, 80,"DynamoDB",   DATABASE,zi=1),
            AW("n_s3",   "aws-s3",        740,260,"S3",         STORAGE,zi=1),
            AW("n_cw",   "aws-cloudwatch",920,160,"CloudWatch", MGMT,   zi=1),
        ],
        edges=[
            E("e01","n_users","n_cog",  "right","left",label="auth",color=SEC,anim=True),
            E("e02","n_cog",  "n_apigw","right","left",label="JWT",  color=NET),
            E("e03","n_apigw","n_lmb",  "right","left",label="invoke",color=COMPUTE,anim=True),
            E("e04","n_lmb",  "n_ddb",  "right","left",color=DATABASE),
            E("e05","n_lmb",  "n_s3",   "right","left",color=STORAGE,es="dashed"),
            E("e06","n_lmb",  "n_cw",   "right","left",label="logs",color="#D1D5DB",es="dotted"),
        ], vx=10, vy=60, vz=0.85),
    "prompts": [
        "Create an AWS authentication architecture with Cognito",
        "Draw an AWS diagram: Cognito + API Gateway + Lambda",
        "AWS Cognito authentication flow with API Gateway and Lambda",
        "Show a secure AWS API with Cognito for authentication",
        "Cognito → JWT → API Gateway → Lambda → DynamoDB + S3",
        "AWS: users authenticate with Cognito, get JWT, call API Gateway",
        "AWS auth: Cognito issues JWT, API Gateway validates, Lambda handles request",
        "Diagram a Cognito-secured serverless API on AWS",
        "Show Cognito authentication in an AWS serverless architecture",
        "AWS with Cognito identity: auth → JWT → API GW → Lambda → DDB + S3",
        "Create an AWS diagram showing user authentication via Cognito",
        "Cognito user pool + API Gateway + Lambda + DynamoDB + S3 architecture",
        "AWS: Cognito authenticates, issues token, API Gateway validates token, Lambda runs",
        "Draw a serverless AWS API secured by Amazon Cognito",
        "Show an AWS diagram where Cognito manages identity and API Gateway verifies tokens",
        "Cognito-based auth in AWS: users → Cognito → JWT → API GW → Lambda",
        "AWS authentication architecture with managed identity service",
        "Create an AWS diagram for a secure serverless API with Cognito auth",
        "Show Cognito + API Gateway authorization in an AWS diagram",
        "AWS Cognito diagram: authenticate, get token, call API, Lambda processes, stores in DDB",
        "Diagram a complete AWS serverless API with Cognito identity management",
        "Draw AWS Cognito authentication flow for a web or mobile application",
        "Cognito-secured Lambda API on AWS with DynamoDB and S3 backing",
        "AWS IAM-style auth: Cognito user pools → API Gateway authorizer → Lambda handler",
        "Show the authentication and authorization flow in a serverless AWS architecture",
    ]
})

# ── A19  AWS IoT Architecture ─────────────────────────────────────────────────────
SCENARIOS.append({
    "diagram": D("d_a19", "AWS IoT Architecture",
        nodes=[
            N("n_dev", "hexagon",    20,175, 120, 70,"IoT Devices","#EFF6FF","#60A5FA",tc="#1E3A8A",fw="700",zi=1),
            AW("n_iot", "aws-apigateway",200,160,"IoT Core",  NET,    zi=1),
            AW("n_rule","aws-lambda",    380,160,"IoT Rules", COMPUTE,zi=1),
            AW("n_sqs", "aws-sqs",       560, 60,"SQS",       MSG,    zi=1),
            AW("n_s3",  "aws-s3",        560,280,"Raw Data S3",STORAGE,zi=1),
            AW("n_lmb", "aws-lambda",    740, 60,"Processor", COMPUTE,zi=1),
            AW("n_ddb", "aws-dynamodb",  920, 60,"DynamoDB",  DATABASE,zi=1),
            AW("n_cw",  "aws-cloudwatch",920,260,"CloudWatch",MGMT,   zi=1),
        ],
        edges=[
            E("e01","n_dev", "n_iot", "right","left",label="MQTT",color=NET,anim=True),
            E("e02","n_iot", "n_rule","right","left",color=COMPUTE),
            E("e03","n_rule","n_sqs", "right","left",label="enqueue",color=MSG),
            E("e04","n_rule","n_s3",  "right","left",label="archive",color=STORAGE,es="dashed"),
            E("e05","n_sqs", "n_lmb", "right","left",label="process",color=COMPUTE,anim=True),
            E("e06","n_lmb", "n_ddb", "right","left",color=DATABASE),
            E("e07","n_lmb", "n_cw",  "bottom","top",label="metrics",color="#D1D5DB",es="dotted"),
        ], vx=10, vy=50, vz=0.85),
    "prompts": [
        "Create an AWS IoT architecture diagram",
        "Draw an AWS IoT data ingestion pipeline",
        "AWS IoT: devices → IoT Core → rules engine → SQS + S3 → Lambda → DynamoDB",
        "Show an AWS IoT architecture with data processing",
        "IoT device data ingestion on AWS",
        "AWS IoT diagram: MQTT devices, IoT Core, rules, processing, storage",
        "Diagram an IoT data pipeline on AWS",
        "Show IoT devices sending MQTT messages to AWS IoT Core",
        "AWS IoT: devices → IoT Core → rules engine → queue + raw storage → Lambda processor",
        "Create an AWS IoT architecture for device telemetry",
        "IoT devices connect to AWS IoT Core, rules route to SQS and S3, Lambda processes",
        "AWS IoT data flow: MQTT ingestion → IoT rules → SQS → Lambda → DynamoDB",
        "Show how IoT sensor data flows through AWS",
        "AWS IoT pipeline: devices, IoT Core, rules, SQS, processor Lambda, database",
        "Diagram an AWS IoT solution with raw data archival to S3",
        "AWS: IoT devices → IoT Core rules engine → enqueue in SQS → processor → DynamoDB",
        "Create an AWS IoT diagram with CloudWatch monitoring",
        "Show an AWS IoT architecture for industrial sensor data",
        "IoT Core rules engine routing to SQS and S3 simultaneously",
        "AWS IoT pipeline: ingest MQTT, apply rules, process events, store telemetry",
        "Draw an AWS IoT architecture for a smart home or industrial application",
        "IoT data processing on AWS: MQTT → IoT Core → SQS → Lambda → DynamoDB",
        "AWS IoT: raw data to S3, processed data to DynamoDB via Lambda",
        "Create an AWS IoT architecture with rules-based routing",
        "Show the complete AWS IoT data journey from device to database",
    ]
})

# ── A20  AWS CI/CD Pipeline ────────────────────────────────────────────────────────
SCENARIOS.append({
    "diagram": D("d_a20", "AWS CI/CD Pipeline",
        nodes=[
            N("n_git",  "roundedRect", 20,175, 130, 70,"GitHub Repo","#F3F4F6","#9CA3AF",tc="#374151",fw="700",zi=1),
            AW("n_cb",  "aws-ecs",       220,160,"CodeBuild",  COMPUTE, zi=1),
            AW("n_ecr", "aws-ecs",       400,160,"ECR",        COMPUTE, zi=1),
            AW("n_cd",  "aws-ecs",       580,160,"CodeDeploy", COMPUTE, zi=1),
            AW("n_stg", "aws-ecs",       760, 80,"ECS Staging",COMPUTE, zi=1),
            AW("n_prd", "aws-ecs",       760,260,"ECS Prod",   COMPUTE, zi=1),
            AW("n_s3",  "aws-s3",        400, 30,"Artifacts S3",STORAGE,zi=1),
            AW("n_sns", "aws-sns",       940,175,"Notifications",MSG,   zi=1),
            AW("n_cw",  "aws-cloudwatch",940, 30,"CloudWatch", MGMT,   zi=1),
        ],
        edges=[
            E("e01","n_git","n_cb",  "right","left",label="push",color=COMPUTE,anim=True),
            E("e02","n_cb", "n_s3",  "top",  "bottom",label="artifacts",color=STORAGE,es="dashed"),
            E("e03","n_cb", "n_ecr", "right","left",label="push image",color=COMPUTE),
            E("e04","n_ecr","n_cd",  "right","left",color=COMPUTE),
            E("e05","n_cd", "n_stg", "right","left",label="deploy",color=COMPUTE),
            E("e06","n_cd", "n_prd", "right","left",label="deploy",color=COMPUTE),
            E("e07","n_cd", "n_sns", "right","left",label="notify",color=MSG),
            E("e08","n_cb", "n_cw",  "right","left",label="logs",color="#D1D5DB",es="dotted"),
        ], vx=10, vy=30, vz=0.8),
    "prompts": [
        "Create an AWS CI/CD pipeline architecture diagram",
        "Draw an AWS CodeBuild + CodeDeploy + ECS pipeline",
        "AWS CI/CD: GitHub → CodeBuild → ECR → CodeDeploy → ECS",
        "Show an AWS deployment pipeline with container registry",
        "AWS CI/CD pipeline: build, push to ECR, deploy to staging and prod ECS",
        "AWS pipeline: GitHub push → CodeBuild → push image to ECR → CodeDeploy",
        "Diagram an AWS CI/CD pipeline for containerized applications",
        "Show AWS CodeBuild building and pushing Docker images to ECR",
        "AWS CI/CD with CodeBuild, ECR, and CodeDeploy to ECS",
        "Create an AWS CI/CD diagram with staging and production environments",
        "GitHub → CodeBuild → ECR → CodeDeploy → ECS staging + ECS prod",
        "AWS container deployment pipeline with artifact storage in S3",
        "Show AWS CI/CD: build artifacts, push Docker image, deploy to two environments",
        "AWS pipeline diagram: source repo, build, registry, deploy, notifications",
        "AWS CI/CD with CodeBuild, ECR, CodeDeploy, SNS notifications",
        "Diagram the AWS container CI/CD workflow",
        "AWS: code push triggers CodeBuild, image pushed to ECR, CodeDeploy deploys to ECS",
        "Create an AWS CI/CD diagram with notification on deployment",
        "AWS pipeline: GitHub, CodeBuild, S3 artifacts, ECR, CodeDeploy, ECS",
        "Show AWS CI/CD pipeline with CloudWatch monitoring",
        "AWS container deployment: code → build → push image → deploy → notify",
        "CI/CD pipeline on AWS using managed services: CodeBuild, ECR, CodeDeploy",
        "Draw an AWS pipeline from GitHub commit to production ECS deployment",
        "AWS CI/CD with two target environments: staging and production",
        "Show the full AWS container CI/CD flow from code commit to ECS deployment",
    ]
})

# ── A21  AWS Analytics Platform ───────────────────────────────────────────────────
SCENARIOS.append({
    "diagram": D("d_a21", "AWS Analytics Platform",
        nodes=[
            AW("n_rds",  "aws-rds",       40,260,"Transactional DB",DATABASE,zi=1),
            AW("n_lmb",  "aws-lambda",    220,260,"CDC Lambda", COMPUTE, zi=1),
            AW("n_s3r",  "aws-s3",        400, 80,"Raw S3",     STORAGE, zi=1),
            AW("n_s3p",  "aws-s3",        400,260,"Processed S3",STORAGE,zi=1),
            AW("n_s3c",  "aws-s3",        400,440,"Curated S3", STORAGE, zi=1),
            AW("n_glue", "aws-ecs",       580,260,"Glue Job",   COMPUTE, zi=1),
            AW("n_sns",  "aws-sns",       760, 80,"Notifications",MSG,   zi=1),
            AW("n_cw",   "aws-cloudwatch",760,440,"CloudWatch", MGMT,   zi=1),
            AW("n_iam",  "aws-iam",        940,260,"IAM",       SEC,     zi=1),
        ],
        edges=[
            E("e01","n_rds", "n_lmb","right","left",color=DATABASE),
            E("e02","n_lmb", "n_s3r","right","left",label="ingest",color=STORAGE),
            E("e03","n_s3r", "n_glue","right","left",color=COMPUTE),
            E("e04","n_glue","n_s3p","right","left",label="transform",color=STORAGE),
            E("e05","n_s3p", "n_s3c","bottom","top",label="aggregate",color=STORAGE,es="dashed"),
            E("e06","n_glue","n_sns","top",  "bottom",label="complete",color=MSG),
            E("e07","n_glue","n_cw", "bottom","top",label="metrics",color="#D1D5DB",es="dotted"),
        ], vx=10, vy=30, vz=0.85),
    "prompts": [
        "Create an AWS analytics platform architecture diagram",
        "Draw an AWS data analytics pipeline",
        "AWS analytics: RDS → Lambda CDC → S3 raw → Glue → S3 processed → curated",
        "Show an AWS analytics pipeline with S3 data lake and Glue ETL",
        "AWS data analytics: capture from DB, land in S3, process with Glue, curate",
        "Diagram an AWS analytics platform with three S3 tiers",
        "AWS: transactional DB → CDC Lambda → S3 raw → Glue → processed and curated zones",
        "Show an AWS data platform with Glue ETL and tiered S3 storage",
        "AWS analytics platform with CDC pipeline and three-zone data lake",
        "Create an AWS analytics diagram with SNS notification on job completion",
        "AWS data lake with CDC, Glue jobs, and S3 tiers",
        "Draw an AWS analytics pipeline from transactional DB to curated data",
        "AWS: CDC captures DB changes → Lambda → raw S3 → Glue job → processed → curated",
        "Show AWS analytics with IAM controls and CloudWatch monitoring",
        "AWS data analytics with Glue for ETL and tiered S3 zones",
        "Create an AWS diagram for a data analytics pipeline",
        "AWS analytics: Lambda CDC from RDS, Glue for transformation, S3 for storage",
        "Show an AWS data processing pipeline with CDC and Glue",
        "Data analytics on AWS: RDS source, Lambda ingestion, Glue ETL, S3 lake",
        "AWS analytics platform diagram with three S3 zones and Glue processing",
        "Diagram AWS data analytics with CDC and three-tier data lake",
        "Show an AWS analytics pipeline from transactional database to curated zone",
        "AWS analytics: capture, ingest, transform, aggregate with SNS notifications",
        "Create an AWS data platform with CloudWatch and IAM",
        "AWS analytics pipeline: CDC → raw zone → Glue ETL → processed → curated → notify",
    ]
})

# ── A22  AWS Serverless Real-time Chat ─────────────────────────────────────────────
SCENARIOS.append({
    "diagram": D("d_a22", "Serverless WebSocket API",
        nodes=[
            N("n_client","pill",    20,175, 120, 50,"Clients","#DBEAFE","#3B82F6",tc="#1E3A8A",fw="700",zi=1),
            AW("n_apigw","aws-apigateway",200,160,"WebSocket API GW",NET,   zi=1),
            AW("n_conn", "aws-lambda",    380, 60,"$connect Lambda",COMPUTE,zi=1),
            AW("n_msg",  "aws-lambda",    380,260,"$message Lambda",COMPUTE,zi=1),
            AW("n_ddb",  "aws-dynamodb",  560, 60,"Connections DDB",DATABASE,zi=1),
            AW("n_sns",  "aws-sns",       560,260,"SNS",           MSG,     zi=1),
            AW("n_lmb",  "aws-lambda",    740,260,"Broadcast Lambda",COMPUTE,zi=1),
            AW("n_cw",   "aws-cloudwatch",740, 60,"CloudWatch",   MGMT,    zi=1),
        ],
        edges=[
            E("e01","n_client","n_apigw","right","left",anim=True,color=NET),
            E("e02","n_apigw", "n_conn", "right","left",label="connect",color=COMPUTE),
            E("e03","n_apigw", "n_msg",  "right","left",label="message",color=COMPUTE,anim=True),
            E("e04","n_conn",  "n_ddb",  "right","left",label="register",color=DATABASE),
            E("e05","n_msg",   "n_sns",  "right","left",label="publish",color=MSG,anim=True),
            E("e06","n_sns",   "n_lmb",  "right","left",color=COMPUTE,anim=True),
            E("e07","n_lmb",   "n_ddb",  "top",  "bottom",label="get connections",color=DATABASE,es="dashed"),
            E("e08","n_lmb",   "n_cw",   "top",  "bottom",label="logs",color="#D1D5DB",es="dotted"),
        ], vx=10, vy=50, vz=0.8),
    "prompts": [
        "Create an AWS serverless WebSocket architecture",
        "Draw a serverless real-time chat architecture on AWS",
        "AWS WebSocket API Gateway + Lambda + DynamoDB for real-time messaging",
        "Show a serverless WebSocket API on AWS",
        "AWS real-time: WebSocket API GW → connect/message Lambda → DynamoDB + SNS",
        "Serverless WebSocket: connect stores in DDB, messages published to SNS, broadcast Lambda",
        "AWS real-time chat architecture diagram",
        "Show AWS serverless WebSocket with connection tracking in DynamoDB",
        "Create an AWS diagram for serverless real-time communication",
        "WebSocket API: on connect → register in DDB, on message → SNS → broadcast Lambda",
        "AWS serverless real-time messaging: WebSocket API GW, two Lambdas, DDB, SNS",
        "Draw an AWS real-time serverless architecture with WebSockets",
        "Serverless chat on AWS: WebSocket API Gateway, Lambda handlers, DynamoDB, SNS",
        "Show how AWS handles serverless WebSocket connections and message broadcasting",
        "AWS WebSocket diagram with $connect and $message Lambda routes",
        "Create a serverless real-time AWS architecture",
        "AWS: WebSocket API GW routes to connect Lambda (stores in DDB) and message Lambda (SNS)",
        "Show an AWS serverless architecture for push notifications",
        "WebSocket API Gateway with Lambda and DynamoDB for connection management",
        "AWS serverless real-time diagram with SNS and broadcast Lambda",
        "Draw a serverless WebSocket architecture on AWS",
        "AWS real-time: clients WebSocket to API GW, messages fan out via SNS",
        "Create an AWS serverless chat architecture with CloudWatch",
        "Show the AWS WebSocket API flow: connect, message, broadcast",
        "AWS serverless real-time messaging with WebSocket API and SNS fan-out",
    ]
})

# ── A23  AWS Disaster Recovery ────────────────────────────────────────────────────
SCENARIOS.append({
    "diagram": D("d_a23", "AWS Warm Standby DR",
        nodes=[
            zone("z_pri","0",  40, 980, 120, "#EFF6FF","#BFDBFE"),
            zone("z_dr", "0", 180, 980, 120, "#FEF9E7","#FDE68A"),
            zlabel("l_pri",8,  43,"PRIMARY REGION (us-east-1)","#93C5FD"),
            zlabel("l_dr", 8, 183,"DR REGION (us-west-2)",     "#FCD34D"),
            AW("n_r53", "aws-route53",    20,175,"Route 53 Health",NET,    zi=2),
            AW("n_cf1", "aws-cloudfront",200, 80,"CloudFront",   NET,    zi=2),
            AW("n_alb1","aws-elb",        380, 80,"ALB",         NET,    zi=2),
            AW("n_ecs1","aws-ecs",        560, 80,"ECS",         COMPUTE,zi=2),
            AW("n_aur1","aws-aurora",     740, 80,"Aurora",      DATABASE,zi=2),
            AW("n_cf2", "aws-cloudfront",200,280,"CF Standby",   NET,    zi=2),
            AW("n_alb2","aws-elb",        380,280,"ALB Standby", NET,    zi=2),
            AW("n_ecs2","aws-ecs",        560,280,"ECS Standby", COMPUTE,zi=2),
            AW("n_aur2","aws-aurora",     740,280,"Aurora Replica",DATABASE,zi=2),
            AW("n_cw",  "aws-cloudwatch", 920,175,"CloudWatch",  MGMT,   zi=2),
        ],
        edges=[
            E("e01","n_r53", "n_cf1","right","left",label="active",color=NET,anim=True),
            E("e02","n_r53", "n_cf2","right","left",label="standby",color="#9CA3AF",es="dashed"),
            E("e03","n_cf1", "n_alb1","right","left",color=NET),
            E("e04","n_alb1","n_ecs1","right","left",color=COMPUTE),
            E("e05","n_ecs1","n_aur1","right","left",color=DATABASE),
            E("e06","n_cf2", "n_alb2","right","left",color=NET),
            E("e07","n_alb2","n_ecs2","right","left",color=COMPUTE),
            E("e08","n_ecs2","n_aur2","right","left",color=DATABASE),
            E("e09","n_aur1","n_aur2","bottom","top",label="global replication",color="#60A5FA",es="dashed"),
            E("e10","n_ecs1","n_cw",  "right","left",label="health",color="#D1D5DB",es="dotted"),
        ], vx=10, vy=20, vz=0.75),
    "prompts": [
        "Create an AWS warm standby disaster recovery architecture",
        "Draw an AWS DR diagram with primary and standby regions",
        "AWS DR: warm standby with Route53 health check routing",
        "Show an AWS warm standby DR setup with two regions",
        "AWS disaster recovery: primary region active, standby region warm",
        "AWS DR architecture with Route53 health check and Aurora global replication",
        "Warm standby DR on AWS with two full stacks and cross-region replication",
        "Show an AWS architecture designed for disaster recovery",
        "AWS DR: Route53 health check, active primary, warm standby in DR region",
        "Create an AWS DR diagram with Aurora global database replication",
        "AWS warm standby: same infrastructure in two regions, Aurora cross-region replication",
        "Show primary us-east-1 and standby us-west-2 AWS regions in a DR diagram",
        "AWS disaster recovery architecture with zone labels for primary and DR",
        "Route53 health check routes to primary, fails over to DR region automatically",
        "AWS DR: active region with ECS + Aurora, standby replica region with same stack",
        "Create an AWS warm standby DR architecture diagram",
        "Show cross-region disaster recovery on AWS with Aurora replication",
        "AWS DR diagram: Route53 failover, two regions, Aurora global database",
        "Warm standby AWS DR with CloudWatch health monitoring",
        "Show an AWS deployment built for disaster recovery with two identical regions",
        "AWS two-region warm standby: R53 → active stack + standby stack + Aurora replication",
        "Diagram AWS disaster recovery with Route53 failover and Aurora global tables",
        "Create an AWS DR architecture with warm standby in a second region",
        "Show how Route53 enables automatic failover in an AWS DR setup",
        "AWS warm standby disaster recovery: same stack in two regions with DB replication",
    ]
})

# ── A24  AWS Full Enterprise Platform ─────────────────────────────────────────────
SCENARIOS.append({
    "diagram": D("d_a24", "AWS Enterprise Platform",
        nodes=[
            zone("z_int","0",   40, 970, 120, "#EFF6FF","#BFDBFE"),
            zone("z_pub","0",  180, 970, 140, "#F5F3FF","#DDD6FE"),
            zone("z_cmp","0",  340, 600, 150, "#FFF7ED","#FED7AA"),
            zone("z_asc","0",  510, 600, 150, "#FEFCE8","#FDE68A"),
            zone("z_dat","0",  680, 970, 150, "#F0FDF4","#BBF7D0"),
            zone("z_ops","0",  850, 340, 160, "#FDF2F8","#FBCFE8"),
            zlabel("l_int",8,  43,"INTERNET EDGE",   "#93C5FD"),
            zlabel("l_pub",8, 183,"PUBLIC SUBNETS",  "#C4B5FD"),
            zlabel("l_cmp",8, 343,"COMPUTE",         "#FCA5A5"),
            zlabel("l_asc",8, 513,"ASYNC / MESSAGING","#FCD34D"),
            zlabel("l_dat",8, 683,"DATA LAYER",      "#6EE7B7"),
            zlabel("l_ops",8, 853,"OBSERVABILITY",   "#F9A8D4"),
            N("n_usr","pill",      20, 85,120, 50,"Users","#DBEAFE","#3B82F6",tc="#1E3A8A",fw="700",zi=2),
            AW("n_r53", "aws-route53",    200, 70,"Route 53",    NET,     zi=2),
            AW("n_cf",  "aws-cloudfront", 380, 70,"CloudFront",  NET,     zi=2),
            AW("n_s3s", "aws-s3",         560, 70,"Static S3",   STORAGE, zi=2),
            AW("n_apigw","aws-apigateway",200,230,"API Gateway",NET,     zi=2),
            AW("n_alb",  "aws-elb",        380,230,"ALB",        NET,     zi=2),
            AW("n_lmb",  "aws-lambda",     200,395,"Lambda",     COMPUTE, zi=2),
            AW("n_ecs",  "aws-ecs",        380,395,"ECS API",    COMPUTE, zi=2),
            AW("n_eks",  "aws-eks",        560,395,"EKS",        COMPUTE, zi=2),
            AW("n_sns",  "aws-sns",        200,565,"SNS",        MSG,     zi=2),
            AW("n_sqs",  "aws-sqs",        380,565,"SQS",        MSG,     zi=2),
            AW("n_dlq",  "aws-sqs",        560,565,"DLQ",        MSG,     zi=2),
            AW("n_aur",  "aws-aurora",     200,735,"Aurora",     DATABASE,zi=2),
            AW("n_rds",  "aws-rds",        380,735,"Read Replica",DATABASE,zi=2),
            AW("n_ec",   "aws-elasticache",560,735,"ElastiCache",DATABASE,zi=2),
            AW("n_ddb",  "aws-dynamodb",   740,735,"DynamoDB",   DATABASE,zi=2),
            AW("n_s3d",  "aws-s3",         920,735,"Data Lake",  STORAGE, zi=2),
            AW("n_cw",   "aws-cloudwatch", 870,395,"CloudWatch", MGMT,    zi=2),
            AW("n_iam",  "aws-iam",         870,565,"IAM",       SEC,     zi=2),
        ],
        edges=[
            E("e01","n_usr",  "n_r53",  "right","left"),
            E("e02","n_r53",  "n_cf",   "right","left",label="DNS",color=NET),
            E("e03","n_cf",   "n_s3s",  "right","left",label="static",color=STORAGE,es="dashed"),
            E("e04","n_cf",   "n_apigw","bottom","top",label="REST",  color=NET,anim=True),
            E("e05","n_cf",   "n_alb",  "bottom","top",label="web",   color=NET,anim=True),
            E("e06","n_apigw","n_lmb",  "bottom","top",label="invoke",color=COMPUTE,anim=True),
            E("e07","n_alb",  "n_ecs",  "bottom","top",color=COMPUTE),
            E("e08","n_alb",  "n_eks",  "bottom","top",color=COMPUTE),
            E("e09","n_lmb",  "n_sns",  "bottom","top",label="events",color=MSG),
            E("e10","n_ecs",  "n_sns",  "bottom","top",color=MSG),
            E("e11","n_sns",  "n_sqs",  "right","left",label="fan-out",color=MSG,anim=True),
            E("e12","n_sqs",  "n_dlq",  "right","left",label="failed",color="#F87171",es="dashed"),
            E("e13","n_lmb",  "n_aur",  "bottom","top",color=DATABASE),
            E("e14","n_ecs",  "n_ec",   "bottom","top",label="cache",color=DATABASE,es="dashed"),
            E("e15","n_eks",  "n_ddb",  "bottom","top",color=DATABASE),
            E("e16","n_aur",  "n_rds",  "right","left",label="replication",color="#60A5FA",es="dashed"),
            E("e17","n_lmb",  "n_s3d",  "bottom","top",label="events",color=STORAGE,es="dashed"),
            E("e18","n_ecs",  "n_cw",   "right","left",label="metrics",color="#D1D5DB",es="dotted"),
            E("e19","n_lmb",  "n_cw",   "right","left",label="logs",color="#D1D5DB",es="dotted"),
        ], vx=10, vy=20, vz=0.6),
    "prompts": [
        "Create a comprehensive AWS enterprise platform architecture diagram",
        "Draw a large-scale AWS architecture with all service layers",
        "Full AWS enterprise: internet edge, public subnets, compute (Lambda+ECS+EKS), messaging, data, observability",
        "Show a complete enterprise AWS platform with 25+ services",
        "AWS enterprise architecture with 6 labeled zones",
        "Full AWS platform: Route53, CloudFront, API GW, ALB, Lambda, ECS, EKS, SNS, SQS, Aurora, DynamoDB",
        "Comprehensive AWS enterprise diagram with compute, messaging, and data zones",
        "Show an enterprise AWS deployment with Lambda, ECS, and EKS as compute options",
        "AWS enterprise: web tier, API tier, compute tier, async tier, data tier, ops tier",
        "Large AWS architecture with zone backgrounds and 25 services",
        "Create an AWS diagram that shows a full enterprise backend",
        "AWS enterprise: CDN, multiple compute options, event bus, multiple databases, observability",
        "Show a comprehensive AWS enterprise architecture with IAM and CloudWatch",
        "Full AWS platform with ECS, EKS, Lambda, Aurora with read replica, ElastiCache, DynamoDB, data lake",
        "Draw an enterprise AWS architecture with 6 zone layers",
        "AWS enterprise backend: API Gateway, Lambda, ECS, EKS, SNS fan-out, SQS, DLQ, Aurora replication",
        "Comprehensive AWS: full internet edge through data layer with observability",
        "Show the most complete AWS architecture diagram you can build",
        "Enterprise AWS with Lambda for serverless, ECS for containers, EKS for Kubernetes",
        "AWS enterprise platform: three compute types, event-driven messaging, five data stores",
        "Create a large-scale AWS architecture with IAM and CloudWatch observability",
        "AWS: full stack from Route53 to data lake, including Aurora replication and ElastiCache",
        "Draw a comprehensive AWS enterprise architecture with all major service categories",
        "Full AWS platform diagram: 6 zones, Lambda+ECS+EKS compute, SNS/SQS messaging, Aurora+DDB+ElastiCache data",
        "Show a complete enterprise-grade AWS architecture with redundancy and observability",
    ]
})
