"""Basic / mixed shape scenarios — 12 scenarios × 25 prompts = 300 examples."""
from .helpers import N, E, D

SCENARIOS = []

# ── B01  Simple 3-node Linear Flow ───────────────────────────────────────────────
SCENARIOS.append({
    "diagram": D("d_b01", "Simple 3-step Process",
        nodes=[
            N("n_a","pill",        40,160,160, 60,"Start",   "#ECFDF5","#34D399",tc="#064E3B",fw="700"),
            N("n_b","roundedRect", 260,160,160, 80,"Process", "#EEF2FF","#818CF8",tc="#1E1B4B"),
            N("n_c","pill",        480,160,160, 60,"End",     "#ECFDF5","#34D399",tc="#064E3B",fw="700"),
        ],
        edges=[
            E("e01","n_a","n_b","right","left"),
            E("e02","n_b","n_c","right","left"),
        ], vx=20, vy=120),
    "prompts": [
        "Create a simple 3-step linear process diagram",
        "Draw a minimal flow: start, process, end",
        "Simple flowchart with three nodes",
        "Show a basic linear flow with start, middle step, and end",
        "Three-node diagram: start → process → end",
        "Create a simple process flow diagram",
        "Draw a 3-step workflow",
        "Minimal diagram: start, one step, end",
        "Basic flowchart with start pill, process box, end pill",
        "Show a simple three-node flow",
        "Diagram a simple start-to-finish process",
        "Create a simple diagram with three connected nodes",
        "Three-node process: start, do something, done",
        "Simple flow: start → process → complete",
        "Draw a minimal workflow diagram",
        "Basic process flow with three steps",
        "Show a simple flow with start, a single action, and end",
        "Create a 3-node process diagram",
        "Minimal workflow: start → process → finish",
        "Simple diagram with start pill, rounded rect, end pill",
        "Draw a simple process from start to end",
        "Three-step process diagram",
        "Show a basic workflow flow from start to completion",
        "Create a minimal 3-node flowchart",
        "Diagram a simple linear process with three nodes",
    ]
})

# ── B02  5-step Linear Process ────────────────────────────────────────────────────
SCENARIOS.append({
    "diagram": D("d_b02", "5-step Process Flow",
        nodes=[
            N("n_s","pill",         40,160,160, 60,"Start",      "#ECFDF5","#34D399",tc="#064E3B",fw="700"),
            N("n_1","rect",        260,160,160, 80,"Step 1",     "#EEF2FF","#818CF8",tc="#1E1B4B"),
            N("n_2","rect",        480,160,160, 80,"Step 2",     "#EEF2FF","#818CF8",tc="#1E1B4B"),
            N("n_3","rect",        700,160,160, 80,"Step 3",     "#EEF2FF","#818CF8",tc="#1E1B4B"),
            N("n_4","roundedRect", 920,160,160, 80,"Complete",   "#F0FDF4","#4ADE80",tc="#14532D"),
            N("n_e","pill",       1140,160,160, 60,"Done",       "#ECFDF5","#34D399",tc="#064E3B",fw="700"),
        ],
        edges=[
            E("e01","n_s","n_1","right","left"),
            E("e02","n_1","n_2","right","left"),
            E("e03","n_2","n_3","right","left"),
            E("e04","n_3","n_4","right","left"),
            E("e05","n_4","n_e","right","left"),
        ], vx=20, vy=120, vz=0.85),
    "prompts": [
        "Create a 5-step linear process flowchart",
        "Draw a horizontal 5-step workflow diagram",
        "Linear process diagram with 5 steps",
        "Show a left-to-right 5-step workflow",
        "Horizontal flow with start, three steps, complete, and done",
        "Five-step process diagram",
        "Draw a sequential 5-step process from start to end",
        "Create a linear workflow with five stages",
        "5-step horizontal workflow: start, step 1, step 2, step 3, complete, done",
        "Show a simple 5-node sequential process",
        "Create a horizontal 5-step process flow",
        "Linear diagram: start → step 1 → step 2 → step 3 → complete → done",
        "Draw a 6-node horizontal workflow with 5 steps",
        "Sequential workflow diagram with start, three process steps, and completion",
        "Show a horizontal linear process with 5 actions",
        "Five-stage workflow from start to done",
        "Create a left-to-right process diagram with 5 steps",
        "Linear process flow with start pill, three rect steps, success step, end pill",
        "Show a simple pipeline with 5 stages",
        "Draw a sequential process with start, steps, and completion",
        "Horizontal 5-step workflow diagram",
        "Create a simple workflow showing 5 sequential steps",
        "Linear five-step flow: start → step A → step B → step C → done",
        "Five sequential steps shown in a horizontal flow diagram",
        "Show a basic 5-stage process from beginning to end",
    ]
})

# ── B03  Decision Branching ───────────────────────────────────────────────────────
SCENARIOS.append({
    "diagram": D("d_b03", "Decision Branch Flow",
        nodes=[
            N("n_s",  "pill",        170,  40,160,  60,"Start",     "#ECFDF5","#34D399",tc="#064E3B",fw="700"),
            N("n_p",  "rect",        170, 160,160,  80,"Process",   "#EEF2FF","#818CF8",tc="#1E1B4B"),
            N("n_d",  "diamond",     155, 300,190, 110,"Decision?", "#FDF2F8","#F472B6",tc="#831843",fw="700"),
            N("n_y",  "roundedRect", 390, 480,160,  80,"Path A",    "#F0FDF4","#4ADE80",tc="#14532D"),
            N("n_n",  "roundedRect", -30, 480,160,  80,"Path B",    "#EEF2FF","#818CF8",tc="#1E1B4B"),
            N("n_e",  "pill",        170, 640,160,  60,"End",       "#ECFDF5","#34D399",tc="#064E3B",fw="700"),
        ],
        edges=[
            E("e01","n_s","n_p","bottom","top"),
            E("e02","n_p","n_d","bottom","top"),
            E("e03","n_d","n_y","right","top", "Yes","#4ADE80"),
            E("e04","n_d","n_n","left", "top", "No", "#6B7280"),
            E("e05","n_y","n_e","bottom","top"),
            E("e06","n_n","n_e","bottom","top"),
        ]),
    "prompts": [
        "Create a flowchart with a decision branch",
        "Draw a diagram with a yes/no decision node",
        "Simple decision flow: process → decision → two paths → end",
        "Show a flowchart with a diamond decision and two branches",
        "Binary decision flowchart with two paths that reconverge",
        "Diagram a flow with a yes/no decision leading to path A or path B",
        "Decision branch diagram: yes path and no path both lead to end",
        "Create a simple branching flowchart",
        "Show a flowchart with a decision diamond that branches to two outcomes",
        "Simple if-else flow diagram",
        "Draw a flow: start, process, decision, two branches that merge at end",
        "Flowchart with conditional branching",
        "Create a decision-based flow where two paths converge at the end",
        "Show a yes/no decision splitting flow into two paths",
        "Decision diamond flowchart with Path A and Path B",
        "Simple branching flow: start → process → decision → yes (A) or no (B) → end",
        "Diagram a flow with conditional logic",
        "Show a flow with one decision point leading to two different outcomes",
        "Simple if-else flowchart",
        "Create a diagram with a binary decision branching to two paths",
        "Decision branch flow: both paths reconverge at the end node",
        "Draw a flow with a diamond node that splits into two branches",
        "Show a simple process flow with a decision point",
        "Flowchart: process → decision → path A (yes) or path B (no) → end",
        "Create a basic branching diagram with a yes/no decision",
    ]
})

# ── B04  State Machine ────────────────────────────────────────────────────────────
SCENARIOS.append({
    "diagram": D("d_b04", "Order State Machine",
        nodes=[
            N("n_new",     "circle",      40,160,100,100,"New",        "#ECFDF5","#34D399",tc="#064E3B",fw="700",fs=14),
            N("n_pending", "roundedRect", 210,160,140, 80,"Pending",   "#EEF2FF","#818CF8",tc="#1E1B4B"),
            N("n_paid",    "roundedRect", 420,160,140, 80,"Paid",      "#F0FDF4","#4ADE80",tc="#14532D"),
            N("n_fulfil",  "roundedRect", 630,160,140, 80,"Fulfilled", "#EFF6FF","#60A5FA",tc="#1E3A8A"),
            N("n_shipped", "roundedRect", 420,310,140, 80,"Shipped",   "#EFF6FF","#60A5FA",tc="#1E3A8A"),
            N("n_done",    "circle",      630,310,100,100,"Delivered", "#ECFDF5","#34D399",tc="#064E3B",fw="700",fs=12),
            N("n_cancel",  "circle",      210,310,100,100,"Cancelled", "#FFF1F2","#FB7185",tc="#881337",fw="700",fs=12),
        ],
        edges=[
            E("e01","n_new",    "n_pending","right","left",  label="submit",   color="#818CF8"),
            E("e02","n_pending","n_paid",   "right","left",  label="pay",      color="#4ADE80"),
            E("e03","n_pending","n_cancel", "bottom","top",  label="cancel",   color="#FB7185"),
            E("e04","n_paid",   "n_fulfil", "right","left",  label="fulfil",   color="#60A5FA"),
            E("e05","n_fulfil", "n_shipped","bottom","top",  label="ship",     color="#60A5FA"),
            E("e06","n_shipped","n_done",   "right","left",  label="deliver",  color="#34D399"),
            E("e07","n_paid",   "n_cancel", "bottom","left", label="cancel",   color="#FB7185",es="dashed"),
        ], vx=20, vy=80, vz=0.95),
    "prompts": [
        "Create an order state machine diagram",
        "Draw a state diagram for order lifecycle",
        "State machine: New → Pending → Paid → Fulfilled → Shipped → Delivered",
        "Show the states an order goes through from creation to delivery",
        "Order state transitions: submit, pay, fulfil, ship, deliver",
        "Diagram the order lifecycle as a state machine",
        "State machine diagram for an e-commerce order",
        "Show order states with transition labels",
        "Create a state diagram showing order progression",
        "Order lifecycle: New, Pending, Paid, Fulfilled, Shipped, Delivered + Cancelled",
        "State machine: order starts as New, ends as Delivered or Cancelled",
        "Show valid transitions between order states",
        "Diagram a finite state machine for order processing",
        "Order status flow: submit to pending, pay to paid, fulfil, ship, deliver",
        "State machine with circles for terminal states and rects for intermediate states",
        "Create an order state diagram with cancellation path",
        "Show order states as a state machine with labeled transitions",
        "Order FSM: New → Pending (submit) → Paid (pay) → Fulfilled → Shipped → Delivered",
        "Draw an order state diagram showing the full lifecycle including cancellation",
        "State machine diagram: e-commerce order with 5 states and transitions",
        "Show order state transitions including the cancel path from Pending or Paid",
        "Create a state machine diagram for an order management system",
        "Order lifecycle state diagram with terminal states: Delivered and Cancelled",
        "Diagram showing how an order moves through processing states",
        "State machine for e-commerce: order creation to delivery with cancel option",
    ]
})

# ── B05  Org Chart ───────────────────────────────────────────────────────────────
SCENARIOS.append({
    "diagram": D("d_b05", "Org Chart",
        nodes=[
            N("n_ceo", "roundedRect", 360, 40,160, 70,"CEO",         "#DBEAFE","#3B82F6",tc="#1E3A8A",fw="700"),
            N("n_cto", "roundedRect", 100,180,160, 70,"CTO",         "#EEF2FF","#818CF8",tc="#1E1B4B",fw="700"),
            N("n_cmo", "roundedRect", 360,180,160, 70,"CMO",         "#EEF2FF","#818CF8",tc="#1E1B4B",fw="700"),
            N("n_cfo", "roundedRect", 620,180,160, 70,"CFO",         "#EEF2FF","#818CF8",tc="#1E1B4B",fw="700"),
            N("n_eng", "rect",          0,330,140, 60,"Engineering", "#EFF6FF","#60A5FA",tc="#1E3A8A"),
            N("n_inf", "rect",        160,330,140, 60,"Infra",       "#EFF6FF","#60A5FA",tc="#1E3A8A"),
            N("n_mkt", "rect",        340,330,140, 60,"Marketing",   "#EFF6FF","#60A5FA",tc="#1E3A8A"),
            N("n_slz", "rect",        500,330,140, 60,"Sales",       "#EFF6FF","#60A5FA",tc="#1E3A8A"),
            N("n_fin", "rect",        660,330,140, 60,"Finance",     "#EFF6FF","#60A5FA",tc="#1E3A8A"),
        ],
        edges=[
            E("e01","n_ceo","n_cto","bottom","top",at="open"),
            E("e02","n_ceo","n_cmo","bottom","top",at="open"),
            E("e03","n_ceo","n_cfo","bottom","top",at="open"),
            E("e04","n_cto","n_eng","bottom","top",at="open"),
            E("e05","n_cto","n_inf","bottom","top",at="open"),
            E("e06","n_cmo","n_mkt","bottom","top",at="open"),
            E("e07","n_cmo","n_slz","bottom","top",at="open"),
            E("e08","n_cfo","n_fin","bottom","top",at="open"),
        ], vx=30, vy=40, vz=0.9),
    "prompts": [
        "Create an organizational chart",
        "Draw a company org chart",
        "Org chart: CEO → CTO, CMO, CFO → departments",
        "Show a company hierarchy diagram",
        "Company structure: CEO at top, three VPs, department teams below",
        "Create an org chart with CEO, CTO, CMO, CFO",
        "Organizational hierarchy diagram",
        "Draw a top-down org chart for a tech company",
        "Company org chart: CEO → CTO (Engineering, Infra), CMO (Marketing, Sales), CFO (Finance)",
        "Show company organizational structure with three levels",
        "Org chart diagram with CEO at top and departments at bottom",
        "Hierarchy diagram: CEO → three executives → five departments",
        "Create a company org chart with CEO, three C-suite, and five teams",
        "Show the reporting structure of a tech company",
        "Org chart: CEO, CTO, CMO, CFO, Engineering, Infra, Marketing, Sales, Finance",
        "Draw a 3-level org chart",
        "Company hierarchy: CEO → CTO → Engineering + Infra, CMO → Marketing + Sales",
        "Create an org chart diagram with open arrowheads",
        "Organizational chart for a startup with C-suite and department teams",
        "Show company structure as a top-down tree",
        "Org chart with CEO, three C-level executives, and five departments",
        "Draw an org chart diagram with rounded rectangles",
        "Company structure diagram: CEO level, VP level, department level",
        "Hierarchy: CEO at top, CTO/CMO/CFO in middle, teams at bottom",
        "Create an org chart showing three levels of company hierarchy",
    ]
})

# ── B06  Network Topology ─────────────────────────────────────────────────────────
SCENARIOS.append({
    "diagram": D("d_b06", "Network Topology",
        nodes=[
            N("n_int",   "cloud",       350,  0,  160, 80,"Internet",    "#DBEAFE","#3B82F6",tc="#1E3A8A",fw="700"),
            N("n_fw",    "hexagon",     350,140,  160, 80,"Firewall",    "#FFF1F2","#FB7185",tc="#881337",fw="700"),
            N("n_dmz",   "rect",        350,280,  220,140,"DMZ",         "#FEF9E7","#F59E0B",tc="#78350F",op=0.6),
            N("n_web",   "roundedRect", 300,310,  120, 60,"Web Server",  "#EEF2FF","#818CF8",tc="#1E1B4B"),
            N("n_proxy", "roundedRect", 460,310,  120, 60,"Reverse Proxy","#EEF2FF","#818CF8",tc="#1E1B4B"),
            N("n_lan",   "rect",        350,500,  220,140,"Internal LAN","#F0FDF4","#BBF7D0",tc="#14532D",op=0.6),
            N("n_app",   "roundedRect", 300,530,  120, 60,"App Server",  "#EFF6FF","#60A5FA",tc="#1E3A8A"),
            N("n_db",    "cylinder",    460,530,  120, 60,"Database",    "#EFF6FF","#60A5FA",tc="#1E3A8A"),
        ],
        edges=[
            E("e01","n_int","n_fw",   "bottom","top", label="traffic", color="#3B82F6"),
            E("e02","n_fw", "n_web",  "bottom","top", color="#818CF8"),
            E("e03","n_fw", "n_proxy","bottom","top", color="#818CF8"),
            E("e04","n_proxy","n_app","bottom","top", color="#60A5FA"),
            E("e05","n_app","n_db",   "right","left", color="#60A5FA"),
        ], vx=30, vy=20, vz=0.9),
    "prompts": [
        "Create a network topology diagram",
        "Draw a network architecture diagram with DMZ",
        "Network topology: Internet → Firewall → DMZ (web + proxy) → LAN (app + DB)",
        "Show a network diagram with DMZ and internal LAN",
        "Network architecture: internet, firewall, DMZ, internal servers",
        "Diagram a network with firewall, DMZ zone, and internal LAN",
        "Network topology with web server, reverse proxy, app server, database",
        "Show a network architecture diagram with security zones",
        "Create a network diagram with DMZ and LAN zones",
        "Network topology: Internet → Firewall → DMZ → Internal LAN",
        "Show a three-zone network: internet edge, DMZ, internal LAN",
        "Network architecture with firewall, reverse proxy in DMZ, app and DB inside",
        "Diagram a network with internet, firewall, DMZ (web server, reverse proxy), LAN (app, DB)",
        "Draw a network topology with security perimeter",
        "Network diagram showing DMZ and internal network separation",
        "Create a network architecture with firewall protection and DMZ",
        "Show a classic three-tier network: internet, DMZ, internal",
        "Network topology with hexagon firewall and zone backgrounds",
        "Draw a network diagram with internet, firewall, DMZ zone, internal zone",
        "Network architecture: traffic enters through firewall, passes through DMZ to internal",
        "Show a secure network topology with DMZ isolation",
        "Create a network diagram showing internet → firewall → DMZ → LAN",
        "Network topology diagram with three network zones",
        "Draw a corporate network architecture with DMZ",
        "Network topology: internet traffic, firewall, reverse proxy, internal app server, database",
    ]
})

# ── B07  System Context Diagram ───────────────────────────────────────────────────
SCENARIOS.append({
    "diagram": D("d_b07", "System Context Diagram",
        nodes=[
            N("n_sys",   "roundedRect", 310,220, 200,140,"My System",     "#DBEAFE","#3B82F6",tc="#1E3A8A",fw="700",fs=15),
            N("n_usr1",  "circle",       60,240, 100,100,"End User",      "#EEF2FF","#818CF8",tc="#1E1B4B",fw="600",fs=12),
            N("n_usr2",  "circle",       60, 80, 100,100,"Admin",         "#EEF2FF","#818CF8",tc="#1E1B4B",fw="600",fs=12),
            N("n_ext1",  "hexagon",     600, 80, 140, 80,"Payment API",   "#FFF7ED","#F59E0B",tc="#78350F"),
            N("n_ext2",  "hexagon",     600,220, 140, 80,"Email Service", "#FFF7ED","#F59E0B",tc="#78350F"),
            N("n_ext3",  "hexagon",     600,360, 140, 80,"Analytics",     "#FFF7ED","#F59E0B",tc="#78350F"),
            N("n_db",    "cylinder",    310,420, 200, 80,"Database",      "#EFF6FF","#60A5FA",tc="#1E3A8A"),
        ],
        edges=[
            E("e01","n_usr1","n_sys","right","left",  label="uses",         astart=True),
            E("e02","n_usr2","n_sys","right","left",  label="manages",      astart=True),
            E("e03","n_sys","n_ext1","right","left",  label="charges",      color="#F59E0B"),
            E("e04","n_sys","n_ext2","right","left",  label="sends mail",   color="#F59E0B"),
            E("e05","n_sys","n_ext3","right","left",  label="tracks",       color="#F59E0B"),
            E("e06","n_sys","n_db",  "bottom","top",  label="reads/writes", color="#60A5FA"),
        ], vx=30, vy=30, vz=0.95),
    "prompts": [
        "Create a system context diagram",
        "Draw a C4 context diagram",
        "System context: My System in the center, users on the left, external APIs on the right",
        "Show a system context diagram with users, external services, and a database",
        "C4 Level 1 context diagram: system, actors, external dependencies",
        "Diagram a system with its external actors and integrations",
        "Show system context: end user, admin, payment API, email service, analytics, database",
        "Create a context diagram showing system boundaries and external actors",
        "System context diagram: users interact with the system, system calls external APIs",
        "C4 context diagram with My System in the middle",
        "Show a system and all its external interactions",
        "Context diagram: two users, central system, three external services, one database",
        "System context: users on left, external services on right, database below",
        "Draw a C4 context diagram for a web application",
        "Show a system context with actors and external dependencies",
        "Context diagram with payment, email, and analytics as external services",
        "Create a C4 Level 1 diagram showing system and its actors",
        "Show the system boundary with internal database and external API dependencies",
        "C4 context: end user and admin interact with system, system uses three external APIs",
        "Diagram showing how a system relates to its external environment",
        "System context diagram: show what's inside and outside the system boundary",
        "Draw a context-level diagram with actors and external systems",
        "Show a system's external context: users, third-party APIs, database",
        "C4 Level 1: system in center, actors and external services around it",
        "Create a system context diagram showing all actors and integrations",
    ]
})

# ── B08  Generic Microservices ────────────────────────────────────────────────────
SCENARIOS.append({
    "diagram": D("d_b08", "Generic Microservices",
        nodes=[
            N("n_gw",   "hexagon",     300,  0,  160, 80,"API Gateway",  "#EEF2FF","#818CF8",tc="#1E1B4B",fw="700"),
            N("n_svc1", "roundedRect",  60,160,  160, 80,"User Service", "#EFF6FF","#60A5FA",tc="#1E3A8A"),
            N("n_svc2", "roundedRect", 300,160,  160, 80,"Order Service","#EFF6FF","#60A5FA",tc="#1E3A8A"),
            N("n_svc3", "roundedRect", 540,160,  160, 80,"Item Service", "#EFF6FF","#60A5FA",tc="#1E3A8A"),
            N("n_db1",  "cylinder",     60,300,  160, 80,"Users DB",     "#EEF2FF","#818CF8",tc="#1E1B4B"),
            N("n_db2",  "cylinder",    300,300,  160, 80,"Orders DB",    "#EEF2FF","#818CF8",tc="#1E1B4B"),
            N("n_db3",  "cylinder",    540,300,  160, 80,"Items DB",     "#EEF2FF","#818CF8",tc="#1E1B4B"),
            N("n_bus",  "parallelogram",300,440, 160, 80,"Event Bus",    "#FFFBEB","#F59E0B",tc="#78350F",fw="700"),
        ],
        edges=[
            E("e01","n_gw",  "n_svc1","bottom","top"),
            E("e02","n_gw",  "n_svc2","bottom","top"),
            E("e03","n_gw",  "n_svc3","bottom","top"),
            E("e04","n_svc1","n_db1", "bottom","top"),
            E("e05","n_svc2","n_db2", "bottom","top"),
            E("e06","n_svc3","n_db3", "bottom","top"),
            E("e07","n_svc2","n_bus", "bottom","top",label="events",color="#F59E0B",anim=True),
        ], vx=20, vy=20, vz=0.9),
    "prompts": [
        "Create a generic microservices architecture diagram",
        "Draw a microservices diagram with API gateway and three services",
        "Microservices: API Gateway → User Service, Order Service, Item Service",
        "Show a microservices architecture with database-per-service pattern",
        "Generic microservices diagram with three services and an event bus",
        "Diagram three microservices each with their own database",
        "Show an API gateway routing to three independent microservices",
        "Microservices with database isolation and event bus",
        "Create a microservices diagram: gateway, services, databases, event bus",
        "Show three microservices each owning their data and communicating via events",
        "Microservices diagram: User Service, Order Service, Item Service with separate DBs",
        "Generic microservices architecture with API gateway and shared event bus",
        "Draw a microservices diagram showing service and database boundaries",
        "Three microservices with separate databases and an event bus",
        "Microservices: gateway routes to services, each service has its own DB",
        "Create a generic microservices diagram with event-driven communication",
        "Show a microservices pattern with database-per-service and event bus",
        "API Gateway routes to three microservices, Order Service publishes to Event Bus",
        "Generic microservices architecture with hexagon gateway and cylinder databases",
        "Show service isolation in a microservices architecture",
        "Microservices diagram: three services, three DBs, one event bus",
        "Draw a microservices diagram with API gateway, services, and databases",
        "Generic microservices: gateway, service1, service2, service3, three databases",
        "Microservices with event-driven integration: Order Service publishes to event bus",
        "Create a generic microservices diagram showing service + data isolation",
    ]
})

# ── B09  Team Handoff Workflow ────────────────────────────────────────────────────
SCENARIOS.append({
    "diagram": D("d_b09", "Team Handoff Workflow",
        nodes=[
            N("n_req",   "parallelogram",170,  40,160,  80,"Requirement",    "#F0F9FF","#38BDF8",tc="#0C4A6E"),
            N("n_pm",    "rect",         170, 180,160,  80,"PM: Spec",       "#EEF2FF","#818CF8",tc="#1E1B4B"),
            N("n_des",   "roundedRect",  170, 320,160,  80,"Design: Mockup", "#EFF6FF","#60A5FA",tc="#1E3A8A"),
            N("n_dev",   "roundedRect",  170, 460,160,  80,"Dev: Implement", "#EFF6FF","#60A5FA",tc="#1E3A8A"),
            N("n_qa",    "roundedRect",  170, 600,160,  80,"QA: Test",       "#FFF7ED","#F59E0B",tc="#78350F"),
            N("n_dec",   "diamond",      155, 740,190, 110,"Pass?",          "#FDF2F8","#F472B6",tc="#831843",fw="700"),
            N("n_fix",   "rect",         -30, 920,160,  80,"Fix Issues",     "#FFF1F2","#FB7185",tc="#881337"),
            N("n_dep",   "roundedRect",  390, 920,160,  80,"Deploy",         "#F0FDF4","#4ADE80",tc="#14532D"),
            N("n_end",   "pill",         390,1060,160,  60,"Done",           "#ECFDF5","#34D399",tc="#064E3B",fw="700"),
        ],
        edges=[
            E("e01","n_req","n_pm",  "bottom","top"),
            E("e02","n_pm", "n_des", "bottom","top",label="handoff"),
            E("e03","n_des","n_dev", "bottom","top",label="handoff"),
            E("e04","n_dev","n_qa",  "bottom","top",label="handoff"),
            E("e05","n_qa", "n_dec", "bottom","top"),
            E("e06","n_dec","n_fix", "left",  "top",  "No", "#FB7185"),
            E("e07","n_dec","n_dep", "right", "top",  "Yes","#4ADE80"),
            E("e08","n_fix","n_dev", "top",   "left",label="reassign",color="#FB7185",es="dashed"),
            E("e09","n_dep","n_end", "bottom","top"),
        ]),
    "prompts": [
        "Create a team handoff workflow diagram",
        "Draw a software development handoff flow",
        "Team workflow: requirement → PM spec → design → dev → QA → deploy",
        "Show a cross-team development workflow with handoffs",
        "SDLC workflow: product, design, engineering, QA, deployment",
        "Team handoff diagram for a software feature",
        "Show handoffs between PM, design, dev, and QA teams",
        "Software delivery workflow: spec, mockup, implement, test, deploy",
        "Draw a team collaboration flow from requirement to deployment",
        "Diagram a feature development workflow with handoffs",
        "Team workflow: requirement → PM → design → dev → QA → pass/fail → deploy",
        "Show a cross-functional team workflow with QA gate",
        "Team handoff: PM specs, design mocks up, dev implements, QA tests, deploy",
        "Software development team workflow with QA test gate",
        "Create a team workflow diagram with handoff labels",
        "Show a SCRUM-style team workflow from requirement to deployment",
        "Team workflow: PM hands off to design, design to dev, dev to QA, QA decides",
        "Diagram a software delivery process with team handoffs",
        "Feature workflow: requirement → PM → design → engineering → QA → decision → deploy",
        "Show the team handoff process with a fix loop on QA failure",
        "Cross-team workflow: spec → mockup → implementation → testing → go/no-go",
        "Create a diagram for a software feature moving through product, design, dev, QA",
        "Team handoff flow with QA gate and bug fix loop back to development",
        "Show a software delivery workflow with four team roles",
        "Draw a team workflow from requirement intake to production deployment",
    ]
})

# ── B10  Event Storming ─────────────────────────────────────────────────────────
SCENARIOS.append({
    "diagram": D("d_b10", "Event Storming (Order Domain)",
        nodes=[
            N("n_t",  "textbox",    0,  0, 360, 36,"Order Domain — Event Storming",
              "transparent","transparent",sw=0,tc="#111827",fs=18,fw="700"),
            N("n_e1", "rect",      40,100, 160, 60,"Order Placed",   "#FEF3C7","#D97706",tc="#78350F",fw="700",fs=12),
            N("n_e2", "rect",     260,100, 160, 60,"Payment Processed","#FEF3C7","#D97706",tc="#78350F",fw="700",fs=12),
            N("n_e3", "rect",     480,100, 160, 60,"Inventory Reserved","#FEF3C7","#D97706",tc="#78350F",fw="700",fs=12),
            N("n_e4", "rect",     700,100, 160, 60,"Order Shipped",  "#FEF3C7","#D97706",tc="#78350F",fw="700",fs=12),
            N("n_e5", "rect",     920,100, 160, 60,"Order Delivered","#FEF3C7","#D97706",tc="#78350F",fw="700",fs=12),
            N("n_c1", "roundedRect",40,220, 160, 60,"Place Order",    "#DBEAFE","#3B82F6",tc="#1E3A8A",fs=12),
            N("n_c2", "roundedRect",260,220,160, 60,"Process Payment","#DBEAFE","#3B82F6",tc="#1E3A8A",fs=12),
            N("n_c3", "roundedRect",480,220,160, 60,"Reserve Stock",  "#DBEAFE","#3B82F6",tc="#1E3A8A",fs=12),
            N("n_agg","hexagon",  480,340, 200, 80,"Order Aggregate","#F3F4F6","#9CA3AF",tc="#374151",fw="700"),
            N("n_pol","callout",  700,220, 180, 60,"Notify Customer","#FFFBEB","#F59E0B",tc="#78350F",fs=12),
        ],
        edges=[
            E("e01","n_c1","n_e1","bottom","top",color="#D97706"),
            E("e02","n_c2","n_e2","bottom","top",color="#D97706"),
            E("e03","n_c3","n_e3","bottom","top",color="#D97706"),
            E("e04","n_e1","n_e2","right","left",color="#D97706",anim=True),
            E("e05","n_e2","n_e3","right","left",color="#D97706",anim=True),
            E("e06","n_e3","n_e4","right","left",color="#D97706",anim=True),
            E("e07","n_e4","n_e5","right","left",color="#D97706",anim=True),
            E("e08","n_e4","n_pol","bottom","top",color="#F59E0B",es="dashed"),
            E("e09","n_c1","n_agg","bottom","top",color="#9CA3AF",es="dotted"),
        ], vx=20, vy=20, vz=0.8),
    "prompts": [
        "Create an event storming diagram for an order domain",
        "Draw an event storming board for order processing",
        "Event storming: domain events (orange), commands (blue), aggregate (hex)",
        "Show an event storming diagram with domain events and commands",
        "Order domain event storming: Place Order command → Order Placed event, etc.",
        "Diagram an event storming session for an e-commerce order domain",
        "Show domain events flowing in an event storming board",
        "Event storming with commands, domain events, and aggregate",
        "Create an event storming diagram: commands trigger events, events flow left to right",
        "Order event storming: Order Placed → Payment Processed → Inventory Reserved → Shipped → Delivered",
        "Show an event storming board with orange events, blue commands, hex aggregate",
        "Event storming diagram for order lifecycle",
        "Domain event flow: Place Order → Order Placed → Payment Processed → Reserved → Shipped",
        "Event storming board: five domain events across top, commands below",
        "Create an event storming diagram with a policy (callout) and aggregate (hexagon)",
        "Show event storming with animated event flow and commands triggering events",
        "Order domain event storming: domain events connected left to right",
        "Diagram event storming: commands issue events, aggregate processes state",
        "Event storming for e-commerce: show five domain events and three commands",
        "Draw an event storming board with orange event cards and blue command cards",
        "Event storming: show how commands trigger domain events in an order system",
        "Order domain event map with commands and events",
        "Create a DDD event storming diagram for order management",
        "Show event storming notation: orange events, blue commands, hex aggregate, callout policy",
        "Draw an event storming diagram for an order processing bounded context",
    ]
})

# ── B11  Complex Decision Tree ────────────────────────────────────────────────────
SCENARIOS.append({
    "diagram": D("d_b11", "Loan Approval Decision Tree",
        nodes=[
            N("n_start","pill",      250,  0,160,  60,"Loan Application","#ECFDF5","#34D399",tc="#064E3B",fw="700"),
            N("n_d1",   "diamond",   235, 120,190, 110,"Credit Score ≥ 700?","#FDF2F8","#F472B6",tc="#831843",fw="700",fs=12),
            N("n_d2",   "diamond",     0, 300,190, 110,"Income Verified?","#FDF2F8","#F472B6",tc="#831843",fw="700",fs=12),
            N("n_d3",   "diamond",   470, 300,190, 110,"DTI ≤ 40%?",     "#FDF2F8","#F472B6",tc="#831843",fw="700",fs=12),
            N("n_d4",   "diamond",   235, 500,190, 110,"Collateral OK?", "#FDF2F8","#F472B6",tc="#831843",fw="700",fs=12),
            N("n_apr",  "roundedRect",470,500,160,  80,"Approve Loan",   "#F0FDF4","#4ADE80",tc="#14532D",fw="700"),
            N("n_rev",  "roundedRect",  0,500,160,  80,"Manual Review",  "#FFF7ED","#F59E0B",tc="#78350F"),
            N("n_rej1", "callout",   470,680,160,  80,"Reject",         "#FFF1F2","#FB7185",tc="#881337"),
            N("n_rej2", "callout",   235,680,160,  80,"Reject",         "#FFF1F2","#FB7185",tc="#881337"),
            N("n_rej3", "callout",     0,680,160,  80,"Reject",         "#FFF1F2","#FB7185",tc="#881337"),
        ],
        edges=[
            E("e01","n_start","n_d1","bottom","top"),
            E("e02","n_d1","n_d2",  "left",  "top",  "No",  "#9CA3AF"),
            E("e03","n_d1","n_d3",  "right", "top",  "Yes", "#4ADE80"),
            E("e04","n_d2","n_rej3","bottom","top",  "No",  "#FB7185"),
            E("e05","n_d2","n_d4",  "right", "left", "Yes", "#4ADE80"),
            E("e06","n_d3","n_rev", "left",  "top",  "No",  "#F59E0B"),
            E("e07","n_d3","n_apr", "bottom","top",  "Yes", "#4ADE80"),
            E("e08","n_d4","n_rej2","bottom","top",  "No",  "#FB7185"),
            E("e09","n_d4","n_apr", "right", "left", "Yes", "#4ADE80"),
            E("e10","n_rev","n_rej1","bottom","top"),
        ], vx=30, vy=20, vz=0.85),
    "prompts": [
        "Create a loan approval decision tree",
        "Draw a decision tree for loan approval",
        "Loan decision tree: credit score → income verification → DTI → collateral → approve/reject",
        "Show a loan approval flow with multiple decision nodes",
        "Decision tree: credit score, income, debt-to-income ratio, collateral checks",
        "Diagram a loan approval process with four decision criteria",
        "Show a multi-criteria loan decision tree",
        "Loan application flow: four decision checks → approve or reject",
        "Create a loan decision tree with approve, reject, and manual review paths",
        "Decision tree for credit approval: credit score, income, DTI, collateral",
        "Loan approval decision tree with approve and reject outcomes",
        "Show a loan decision flow with multiple criteria and outcomes",
        "Diagram a 4-criteria loan approval decision tree",
        "Loan approval: credit score ≥ 700, income verified, DTI ≤ 40%, collateral check",
        "Decision tree for a bank loan application",
        "Create a multi-level decision tree for loan approval",
        "Show loan decision logic: four decision diamonds leading to approve, reject, or review",
        "Loan decision tree diagram with four gates and three possible outcomes",
        "Draw a loan approval process with credit score, income, DTI, and collateral checks",
        "Multi-criteria decision tree for financial loan approval",
        "Show a decision tree where passing all four checks leads to loan approval",
        "Loan application decision tree with diamond nodes for each criterion",
        "Create a decision tree diagram for a loan processing workflow",
        "Diagram loan approval: each check either continues or rejects the application",
        "Decision tree flowchart for a lending institution's loan approval process",
    ]
})

# ── B12  Data Flow Diagram ────────────────────────────────────────────────────────
SCENARIOS.append({
    "diagram": D("d_b12", "E-commerce Data Flow",
        nodes=[
            N("n_usr",  "circle",     20,220, 100,100,"Customer",      "#DBEAFE","#3B82F6",tc="#1E3A8A",fw="600",fs=12),
            N("n_order","roundedRect",200,220, 160, 80,"Order System",  "#EEF2FF","#818CF8",tc="#1E1B4B",fw="700"),
            N("n_inv",  "roundedRect",430,100, 160, 80,"Inventory Sys", "#EEF2FF","#818CF8",tc="#1E1B4B",fw="700"),
            N("n_pay",  "roundedRect",430,220, 160, 80,"Payment Sys",   "#EEF2FF","#818CF8",tc="#1E1B4B",fw="700"),
            N("n_ship", "roundedRect",430,340, 160, 80,"Shipping Sys",  "#EEF2FF","#818CF8",tc="#1E1B4B",fw="700"),
            N("n_db",   "cylinder",   660,220, 160, 80,"Order DB",      "#EFF6FF","#60A5FA",tc="#1E3A8A"),
            N("n_admin","circle",     660, 80, 100,100,"Admin",         "#F0FDF4","#4ADE80",tc="#14532D",fw="600",fs=13),
        ],
        edges=[
            E("e01","n_usr",  "n_order","right","left",  label="place order",  anim=True, color="#3B82F6"),
            E("e02","n_order","n_inv",  "right","bottom", label="check stock",  color="#818CF8"),
            E("e03","n_order","n_pay",  "right","left",   label="process payment",color="#818CF8"),
            E("e04","n_order","n_ship", "right","top",   label="create shipment",color="#818CF8"),
            E("e05","n_order","n_db",   "right","left",   label="persist",      color="#60A5FA"),
            E("e06","n_admin","n_db",   "bottom","top",  label="view reports",  color="#4ADE80",at="open"),
            E("e07","n_pay",  "n_usr",  "left",  "right", label="receipt",      color="#818CF8",es="dashed",astart=True),
        ], vx=10, vy=50, vz=0.9),
    "prompts": [
        "Create a data flow diagram for an e-commerce system",
        "Draw a DFD showing how an order flows through systems",
        "Data flow: customer places order, order system interacts with inventory, payment, shipping",
        "Show a DFD for an online store with order, payment, inventory, and shipping systems",
        "E-commerce DFD: customer → order system → inventory, payment, shipping, database",
        "Data flow diagram for e-commerce with admin access",
        "Show an e-commerce data flow diagram",
        "DFD: order system processes customer orders, checks inventory, charges payment, creates shipment",
        "Create an e-commerce data flow diagram with external entities",
        "Show data flows between customer, order system, and subsystems",
        "E-commerce DFD: customer places order, order system distributes to subsystems",
        "Data flow diagram: customer, order system, inventory, payment, shipping, database, admin",
        "Show a DFD for an order management system",
        "Create a data flow diagram showing order processing subsystems",
        "DFD with customer and admin as external entities",
        "E-commerce data flow: order placed, stock checked, payment processed, shipment created",
        "Show how data flows from customer order to fulfillment systems",
        "Data flow diagram with animated customer order flow",
        "E-commerce DFD: customer and admin actors, order system processes, DB stores",
        "Show a data flow diagram for a simple e-commerce platform",
        "DFD: customer → order system → (inventory + payment + shipping + database)",
        "Draw a data flow diagram for an online ordering system",
        "Create a DFD showing bidirectional data flow between customer and order system",
        "E-commerce DFD with receipt flowing back to customer",
        "Diagram data flows in an e-commerce system with four subsystems",
    ]
})
