"""Flowchart scenarios — 20 scenarios × 25 prompts = 500 examples."""
from .helpers import N, E, D

SCENARIOS = []

# ── F01  Simple User Login ─────────────────────────────────────────────────────
SCENARIOS.append({
    "diagram": D("d_f01", "User Login Flow",
        nodes=[
            N("n_start",  "pill",         170, 40,  160, 60,  "Start",             "#ECFDF5","#34D399", tc="#064E3B", fw="700"),
            N("n_input",  "parallelogram",170, 160, 160, 80,  "Enter Credentials", "#F0F9FF","#38BDF8", tc="#0C4A6E"),
            N("n_valid",  "rect",         170, 300, 160, 80,  "Validate Login",    "#EEF2FF","#818CF8", tc="#1E1B4B"),
            N("n_dec",    "diamond",      155, 440, 190, 110, "Valid?",            "#FDF2F8","#F472B6", tc="#831843", fw="700", fs=14),
            N("n_dash",   "roundedRect",  390, 620, 160, 80,  "Go to Dashboard",   "#F0FDF4","#4ADE80", tc="#14532D"),
            N("n_err",    "callout",      -40, 620, 160, 80,  "Show Error",        "#FFF1F2","#FB7185", tc="#881337"),
            N("n_end",    "pill",         390, 760, 160, 60,  "End",               "#ECFDF5","#34D399", tc="#064E3B", fw="700"),
        ],
        edges=[
            E("e01","n_start","n_input","bottom","top"),
            E("e02","n_input","n_valid","bottom","top"),
            E("e03","n_valid","n_dec",  "bottom","top"),
            E("e04","n_dec",  "n_dash", "right", "top",   "Yes","#4ADE80"),
            E("e05","n_dec",  "n_err",  "left",  "top",   "No", "#FB7185"),
            E("e06","n_dash", "n_end",  "bottom","top"),
        ]),
    "prompts": [
        "Create a user login flowchart",
        "Draw a simple login flow diagram",
        "Generate a flowchart for user authentication",
        "Show the login process with a valid/invalid decision",
        "Make a diagram for the sign-in flow with success and error paths",
        "Create a flowchart showing how a user logs into the system",
        "User login flow with credential validation",
        "Design a login flow with happy path and error handling",
        "Flowchart for user sign-in process",
        "Authentication flowchart with yes/no decision",
        "Build a login flowchart with credential validation and dashboard redirect",
        "Simple auth flow: start, enter creds, validate, success or error",
        "Login flow with a decision diamond for valid credentials",
        "Grafly diagram of a login process",
        "User enters credentials, system validates, redirects to dashboard or shows error",
        "Login process diagram from start to end",
        "Show credential validation flow with success and failure branches",
        "Authentication flowchart — valid creds go to dashboard, invalid show error",
        "Create a login diagram with parallelogram input and diamond decision",
        "Basic user login: start pill, credentials, validate, decision, end",
        "Draw a flowchart of the user sign-in journey",
        "Login diagram: enter username/password, validate, success or error",
        "Login flow diagram with error state for bad credentials",
        "Flowchart: user submits login, system checks, either grants access or shows error",
        "Diagram the user authentication process with two outcome paths",
    ]
})

# ── F02  Login with MFA ─────────────────────────────────────────────────────────
SCENARIOS.append({
    "diagram": D("d_f02", "Login with MFA",
        nodes=[
            N("n_start",  "pill",         170,  40, 160,  60, "Start",           "#ECFDF5","#34D399", tc="#064E3B", fw="700"),
            N("n_creds",  "parallelogram",170, 160, 160,  80, "Enter Credentials","#F0F9FF","#38BDF8", tc="#0C4A6E"),
            N("n_chkpw",  "rect",         170, 300, 160,  80, "Verify Password",  "#EEF2FF","#818CF8", tc="#1E1B4B"),
            N("n_dec1",   "diamond",      155, 440, 190, 110, "Password OK?",     "#FDF2F8","#F472B6", tc="#831843", fw="700", fs=13),
            N("n_pwderr", "callout",      -40, 590, 160,  80, "Wrong Password",   "#FFF1F2","#FB7185", tc="#881337"),
            N("n_mfa",    "rect",         170, 610, 160,  80, "Send MFA Code",    "#EEF2FF","#818CF8", tc="#1E1B4B"),
            N("n_code",   "parallelogram",170, 750, 160,  80, "Enter MFA Code",   "#F0F9FF","#38BDF8", tc="#0C4A6E"),
            N("n_dec2",   "diamond",      155, 890, 190, 110, "Code Valid?",      "#FDF2F8","#F472B6", tc="#831843", fw="700", fs=13),
            N("n_mfaerr", "callout",      -40,1060, 160,  80, "Invalid Code",     "#FFF1F2","#FB7185", tc="#881337"),
            N("n_dash",   "roundedRect",  390,1060, 160,  80, "Dashboard",        "#F0FDF4","#4ADE80", tc="#14532D"),
            N("n_end",    "pill",         390,1200, 160,  60, "End",              "#ECFDF5","#34D399", tc="#064E3B", fw="700"),
        ],
        edges=[
            E("e01","n_start", "n_creds", "bottom","top"),
            E("e02","n_creds", "n_chkpw","bottom","top"),
            E("e03","n_chkpw","n_dec1",  "bottom","top"),
            E("e04","n_dec1", "n_pwderr","left",  "top",  "No", "#FB7185"),
            E("e05","n_dec1", "n_mfa",   "bottom","top",  "Yes","#4ADE80"),
            E("e06","n_mfa",  "n_code",  "bottom","top"),
            E("e07","n_code", "n_dec2",  "bottom","top"),
            E("e08","n_dec2", "n_mfaerr","left",  "top",  "No", "#FB7185"),
            E("e09","n_dec2", "n_dash",  "right", "top",  "Yes","#4ADE80"),
            E("e10","n_dash", "n_end",   "bottom","top"),
        ]),
    "prompts": [
        "Create a login flow with MFA verification",
        "Draw a two-factor authentication flowchart",
        "Login flowchart with password check then MFA code step",
        "Multi-factor authentication flow diagram",
        "Show the MFA login process from start to dashboard",
        "2FA login flowchart: enter credentials, verify password, send code, verify code",
        "User authentication with two-step verification diagram",
        "Build a login flow: password decision then MFA decision",
        "MFA authentication flowchart with two decision nodes",
        "Login with MFA: wrong password goes to error, correct goes to send code step",
        "Diagram a secure login process requiring both password and MFA code",
        "Two-step auth flow: credential check then one-time code verification",
        "Flowchart for login requiring multi-factor authentication",
        "Show a login flow where successful password check triggers an MFA code",
        "User sign-in with MFA: two separate decision diamonds",
        "Create a 2FA login diagram with error paths for both steps",
        "Authentication flowchart: password verification followed by OTP verification",
        "Login process with MFA gate before granting dashboard access",
        "Secure login flow: enter creds, verify, send MFA, enter code, verify, done",
        "Two-factor login diagram with error handling at each stage",
        "Build a login flowchart that requires both password and authenticator code",
        "MFA login flow: start, credentials, password decision, MFA code, code decision, end",
        "Diagram the two-factor authentication journey",
        "Show how a user with MFA enabled logs in step by step",
        "Flowchart for enterprise MFA authentication process",
    ]
})

# ── F03  OAuth Social Login ─────────────────────────────────────────────────────
SCENARIOS.append({
    "diagram": D("d_f03", "OAuth Social Login",
        nodes=[
            N("n_start",    "pill",         170,  40, 160,  60, "Start",           "#ECFDF5","#34D399", tc="#064E3B", fw="700"),
            N("n_click",    "roundedRect",  170, 160, 160,  80, "Click Login",     "#EEF2FF","#818CF8", tc="#1E1B4B"),
            N("n_redirect", "rect",         170, 300, 160,  80, "Redirect to OAuth","#EEF2FF","#818CF8",tc="#1E1B4B"),
            N("n_dec",      "diamond",      155, 440, 190, 110, "Authorized?",     "#FDF2F8","#F472B6", tc="#831843", fw="700"),
            N("n_denied",   "callout",      -40, 620, 160,  80, "Access Denied",   "#FFF1F2","#FB7185", tc="#881337"),
            N("n_profile",  "rect",         390, 620, 160,  80, "Fetch User Profile","#EEF2FF","#818CF8",tc="#1E1B4B"),
            N("n_session",  "rect",         390, 760, 160,  80, "Create Session",  "#EEF2FF","#818CF8", tc="#1E1B4B"),
            N("n_dash",     "roundedRect",  390, 900, 160,  80, "Dashboard",       "#F0FDF4","#4ADE80", tc="#14532D"),
            N("n_end",      "pill",         390,1040, 160,  60, "End",             "#ECFDF5","#34D399", tc="#064E3B", fw="700"),
        ],
        edges=[
            E("e01","n_start",   "n_click",   "bottom","top"),
            E("e02","n_click",   "n_redirect","bottom","top"),
            E("e03","n_redirect","n_dec",     "bottom","top"),
            E("e04","n_dec",     "n_denied",  "left",  "top",  "No", "#FB7185"),
            E("e05","n_dec",     "n_profile", "right", "top",  "Yes","#4ADE80"),
            E("e06","n_profile", "n_session", "bottom","top"),
            E("e07","n_session", "n_dash",    "bottom","top"),
            E("e08","n_dash",    "n_end",     "bottom","top"),
        ]),
    "prompts": [
        "Create an OAuth login flowchart",
        "Draw a social login flow using OAuth",
        "OAuth authentication flow diagram",
        "Flowchart for login with Google/GitHub OAuth",
        "Show the OAuth authorization flow with success and denied paths",
        "Social login flow: click button, redirect to provider, authorize, fetch profile",
        "Diagram the OAuth login process",
        "Login with OAuth: redirect to provider, check authorization, create session",
        "Build a social sign-in flowchart with access denied branch",
        "OAuth flow: click login, redirect to OAuth, authorized decision, profile fetch, dashboard",
        "Flowchart showing OAuth 2.0 authorization code flow (simplified)",
        "Social login diagram with three outcomes: denied or session created",
        "Create a Google/GitHub login flow",
        "OAuth login process: user clicks, provider redirects, decision, fetch profile, session",
        "Draw a flowchart for third-party OAuth authentication",
        "Show social auth flow from user click to dashboard",
        "OAuth login diagram with authorization decision diamond",
        "Diagram OAuth-based authentication with fetch profile step",
        "Third-party login flow with session creation",
        "Show the complete OAuth login journey with error handling",
        "Build a social auth flow: click, redirect, authorize, profile, session, dashboard",
        "OAuth flowchart for a web application",
        "Login via OAuth provider flowchart with session setup",
        "Diagram the social login process from button click to user dashboard",
        "Flowchart: user clicks Sign in with Google, OAuth provider responds, session is created",
    ]
})

# ── F04  E-commerce Checkout ────────────────────────────────────────────────────
SCENARIOS.append({
    "diagram": D("d_f04", "E-commerce Checkout",
        nodes=[
            N("n_start",  "pill",         170,  40, 160,  60, "Start",          "#ECFDF5","#34D399", tc="#064E3B", fw="700"),
            N("n_cart",   "roundedRect",  170, 160, 160,  80, "Review Cart",    "#EEF2FF","#818CF8", tc="#1E1B4B"),
            N("n_ship",   "parallelogram",170, 300, 160,  80, "Enter Shipping", "#F0F9FF","#38BDF8", tc="#0C4A6E"),
            N("n_pay",    "parallelogram",170, 440, 160,  80, "Enter Payment",  "#F0F9FF","#38BDF8", tc="#0C4A6E"),
            N("n_order",  "rect",         170, 580, 160,  80, "Place Order",    "#EEF2FF","#818CF8", tc="#1E1B4B"),
            N("n_confirm","roundedRect",  170, 720, 160,  80, "Confirmation",   "#F0FDF4","#4ADE80", tc="#14532D"),
            N("n_end",    "pill",         170, 860, 160,  60, "End",            "#ECFDF5","#34D399", tc="#064E3B", fw="700"),
        ],
        edges=[
            E("e01","n_start",  "n_cart",   "bottom","top"),
            E("e02","n_cart",   "n_ship",   "bottom","top"),
            E("e03","n_ship",   "n_pay",    "bottom","top"),
            E("e04","n_pay",    "n_order",  "bottom","top"),
            E("e05","n_order",  "n_confirm","bottom","top"),
            E("e06","n_confirm","n_end",    "bottom","top"),
        ]),
    "prompts": [
        "Create an e-commerce checkout flowchart",
        "Draw a simple online shopping checkout flow",
        "Flowchart for the checkout process in an online store",
        "Show the steps a user takes to complete a purchase",
        "Checkout flow: cart review, shipping, payment, order placement, confirmation",
        "E-commerce purchase flow diagram",
        "Build a checkout process flowchart",
        "Online store checkout: from cart to order confirmation",
        "Show the checkout journey from cart review to final confirmation",
        "Simple checkout flow with shipping and payment input steps",
        "Diagram the e-commerce checkout process step by step",
        "Shopping cart to order confirmation flow",
        "Create a linear checkout flowchart for an online shop",
        "Checkout process: review cart, enter shipping, enter payment, confirm",
        "Draw the purchase flow for a web store",
        "E-commerce order flow from start to confirmation page",
        "Flowchart for placing an online order",
        "Show the steps: cart, shipping info, payment info, place order, done",
        "Online checkout diagram with parallelogram input steps",
        "Customer purchase journey: add to cart → checkout → confirmation",
        "Build a flowchart showing the checkout steps for a web app",
        "Checkout flow diagram with 5 steps from cart to confirmation",
        "Simple 6-step e-commerce checkout process",
        "Diagram for online shopping: review cart, ship, pay, confirm",
        "Show the typical checkout flow for an e-commerce platform",
    ]
})

# ── F05  Checkout with Payment Decision ─────────────────────────────────────────
SCENARIOS.append({
    "diagram": D("d_f05", "Checkout with Payment Decision",
        nodes=[
            N("n_start",  "pill",         170,  40, 160,  60, "Start",           "#ECFDF5","#34D399", tc="#064E3B", fw="700"),
            N("n_cart",   "roundedRect",  170, 160, 160,  80, "Review Cart",     "#EEF2FF","#818CF8", tc="#1E1B4B"),
            N("n_ship",   "parallelogram",170, 300, 160,  80, "Enter Shipping",  "#F0F9FF","#38BDF8", tc="#0C4A6E"),
            N("n_pay",    "parallelogram",170, 440, 160,  80, "Enter Payment",   "#F0F9FF","#38BDF8", tc="#0C4A6E"),
            N("n_charge", "rect",         170, 580, 160,  80, "Process Payment", "#EEF2FF","#818CF8", tc="#1E1B4B"),
            N("n_dec",    "diamond",      155, 720, 190, 110, "Payment OK?",     "#FDF2F8","#F472B6", tc="#831843", fw="700"),
            N("n_fail",   "callout",      -40, 900, 160,  80, "Payment Failed",  "#FFF1F2","#FB7185", tc="#881337"),
            N("n_confirm","roundedRect",  390, 900, 160,  80, "Order Confirmed", "#F0FDF4","#4ADE80", tc="#14532D"),
            N("n_email",  "rect",         390,1040, 160,  80, "Send Email",      "#EEF2FF","#818CF8", tc="#1E1B4B"),
            N("n_end",    "pill",         390,1180, 160,  60, "End",             "#ECFDF5","#34D399", tc="#064E3B", fw="700"),
        ],
        edges=[
            E("e01","n_start",  "n_cart",   "bottom","top"),
            E("e02","n_cart",   "n_ship",   "bottom","top"),
            E("e03","n_ship",   "n_pay",    "bottom","top"),
            E("e04","n_pay",    "n_charge", "bottom","top"),
            E("e05","n_charge", "n_dec",    "bottom","top"),
            E("e06","n_dec",    "n_fail",   "left",  "top",  "No", "#FB7185"),
            E("e07","n_dec",    "n_confirm","right", "top",  "Yes","#4ADE80"),
            E("e08","n_confirm","n_email",  "bottom","top"),
            E("e09","n_email",  "n_end",    "bottom","top"),
        ]),
    "prompts": [
        "Create a checkout flowchart with payment processing decision",
        "E-commerce checkout flow with payment success and failure paths",
        "Checkout diagram including payment gateway decision",
        "Show the checkout flow where a failed payment shows an error",
        "Build a checkout flowchart: cart, shipping, payment input, charge, decision, confirm or fail",
        "Online store checkout with payment processing and error handling",
        "E-commerce flow with payment gateway: success sends confirmation email, failure shows error",
        "Draw a checkout process that handles both successful and failed payments",
        "Checkout flowchart with payment decision diamond",
        "Show cart-to-confirmation flow with a payment OK decision node",
        "Checkout: enter payment, process charge, payment OK? Yes: confirm order. No: show error.",
        "Diagram checkout process with failed payment branch",
        "E-commerce checkout with payment processing and confirmation email",
        "Build a purchase flow including payment gateway and order confirmation email",
        "Create a checkout flow that sends an email on success and shows error on failure",
        "Flowchart for online checkout: shipping, payment, charge, decision, confirm",
        "Show the complete purchase flow including payment failure handling",
        "Checkout process diagram with payment error recovery path",
        "Online shopping checkout with payment decision and confirmation email step",
        "Diagram checkout where failed payment loops back to payment entry",
        "E-commerce flow: cart review → shipping → payment → process → success or error",
        "Checkout flowchart including payment processing with two outcome paths",
        "Draw a 10-step checkout flow with payment gateway decision",
        "Show the e-commerce purchase flow with a payment charged step and decision",
        "Detailed checkout diagram from cart to confirmation email",
    ]
})

# ── F06  Simple CI/CD Pipeline ──────────────────────────────────────────────────
SCENARIOS.append({
    "diagram": D("d_f06", "Simple CI/CD Pipeline",
        nodes=[
            N("n_push",  "pill",         170,  40, 160,  60, "Code Push",      "#ECFDF5","#34D399", tc="#064E3B", fw="700"),
            N("n_test",  "rect",         170, 160, 160,  80, "Run Tests",      "#EEF2FF","#818CF8", tc="#1E1B4B"),
            N("n_dec",   "diamond",      155, 300, 190, 110, "Tests Pass?",    "#FDF2F8","#F472B6", tc="#831843", fw="700"),
            N("n_fail",  "callout",      -40, 480, 160,  80, "Notify Dev",     "#FFF1F2","#FB7185", tc="#881337"),
            N("n_build", "rect",         390, 480, 160,  80, "Build Artifact", "#EEF2FF","#818CF8", tc="#1E1B4B"),
            N("n_deploy","roundedRect",  390, 620, 160,  80, "Deploy to Prod", "#F0FDF4","#4ADE80", tc="#14532D"),
            N("n_end",   "pill",         390, 760, 160,  60, "Done",           "#ECFDF5","#34D399", tc="#064E3B", fw="700"),
        ],
        edges=[
            E("e01","n_push", "n_test", "bottom","top"),
            E("e02","n_test", "n_dec",  "bottom","top"),
            E("e03","n_dec",  "n_fail", "left",  "top",  "No", "#FB7185"),
            E("e04","n_dec",  "n_build","right", "top",  "Yes","#4ADE80"),
            E("e05","n_build","n_deploy","bottom","top"),
            E("e06","n_deploy","n_end", "bottom","top"),
        ]),
    "prompts": [
        "Create a simple CI/CD pipeline flowchart",
        "Draw a continuous integration and deployment flow",
        "CI/CD pipeline diagram",
        "Flowchart for a code push triggering tests and deployment",
        "Show the CI/CD process: push, test, build, deploy",
        "Build a deployment pipeline flowchart",
        "Code push to production deployment flow",
        "Simple pipeline: push code, run tests, decision, build, deploy",
        "CI pipeline with test decision — pass builds and deploys, fail notifies dev",
        "Diagram a basic CI/CD flow with test gate",
        "Deployment flow: code push → tests → pass/fail → build → deploy",
        "Create a flowchart for automated code deployment",
        "Show the software release pipeline from commit to production",
        "CI/CD flow with tests pass/fail decision and notification on failure",
        "Flowchart: developer pushes code, tests run, if pass deploy, else notify",
        "Build a DevOps pipeline diagram from commit to deployment",
        "Show CI/CD: run tests on push, build artifact on success, deploy to prod",
        "Simple deployment pipeline with test gate flowchart",
        "Create a pipeline flow: code push → unit tests → build → deploy",
        "CI/CD pipeline diagram with failure notification path",
        "Automated deployment flowchart with test verification step",
        "Draw a release pipeline that skips deployment on test failure",
        "Flowchart for software delivery: push, test, build, deploy, done",
        "Show a simple CI pipeline that deploys only when all tests pass",
        "Code integration and deployment flow with pass/fail decision node",
    ]
})

# ── F07  Full CI/CD with Staging Gate ───────────────────────────────────────────
SCENARIOS.append({
    "diagram": D("d_f07", "CI/CD with Staging Gate",
        nodes=[
            N("n_push",   "pill",         170,  40, 160,  60, "Code Push",       "#ECFDF5","#34D399", tc="#064E3B", fw="700"),
            N("n_lint",   "rect",         170, 160, 160,  80, "Lint & Unit Test","#EEF2FF","#818CF8", tc="#1E1B4B"),
            N("n_integ",  "rect",         170, 300, 160,  80, "Integration Tests","#EEF2FF","#818CF8",tc="#1E1B4B"),
            N("n_dec1",   "diamond",      155, 440, 190, 110, "Tests Pass?",     "#FDF2F8","#F472B6", tc="#831843", fw="700"),
            N("n_fail",   "callout",      -40, 620, 160,  80, "Alert Team",      "#FFF1F2","#FB7185", tc="#881337"),
            N("n_build",  "rect",         390, 620, 160,  80, "Build & Push Image","#EEF2FF","#818CF8",tc="#1E1B4B"),
            N("n_staging","roundedRect",  390, 760, 160,  80, "Deploy Staging",  "#EEF2FF","#818CF8", tc="#1E1B4B"),
            N("n_dec2",   "diamond",      375, 900, 190, 110, "Approval?",       "#FDF2F8","#F472B6", tc="#831843", fw="700"),
            N("n_reject", "callout",      200,1080, 160,  80, "Reject Deploy",   "#FFF1F2","#FB7185", tc="#881337"),
            N("n_prod",   "roundedRect",  590,1080, 160,  80, "Deploy Prod",     "#F0FDF4","#4ADE80", tc="#14532D"),
            N("n_notify", "rect",         590,1220, 160,  80, "Notify Team",     "#EEF2FF","#818CF8", tc="#1E1B4B"),
            N("n_end",    "pill",         590,1360, 160,  60, "Done",            "#ECFDF5","#34D399", tc="#064E3B", fw="700"),
        ],
        edges=[
            E("e01","n_push",   "n_lint",   "bottom","top"),
            E("e02","n_lint",   "n_integ",  "bottom","top"),
            E("e03","n_integ",  "n_dec1",   "bottom","top"),
            E("e04","n_dec1",   "n_fail",   "left",  "top",  "No", "#FB7185"),
            E("e05","n_dec1",   "n_build",  "right", "top",  "Yes","#4ADE80"),
            E("e06","n_build",  "n_staging","bottom","top"),
            E("e07","n_staging","n_dec2",   "bottom","top"),
            E("e08","n_dec2",   "n_reject", "left",  "top",  "No", "#FB7185"),
            E("e09","n_dec2",   "n_prod",   "right", "top",  "Yes","#4ADE80"),
            E("e10","n_prod",   "n_notify", "bottom","top"),
            E("e11","n_notify", "n_end",    "bottom","top"),
        ]),
    "prompts": [
        "Create a CI/CD pipeline with staging approval gate",
        "Draw a deployment pipeline that requires manual approval before production",
        "CI/CD flow with staging environment and approval step",
        "Full deployment pipeline: lint, integration test, build, staging, approval, prod",
        "DevOps pipeline flowchart with two decision gates",
        "Show a pipeline that deploys to staging first and requires approval for prod",
        "CI/CD with staging: test gate and approval gate before production",
        "Build a pipeline flowchart with lint, tests, build image, staging deploy, approval, prod",
        "Deployment flow with test failure alert and manual approval gate",
        "Full CI/CD diagram: push → lint → integration test → build → staging → approval → prod",
        "Show a complete software delivery pipeline with two decision nodes",
        "Diagram a DevOps workflow that deploys to staging before production",
        "CI/CD with test gate: fail alerts team, pass builds and deploys to staging then prod",
        "Pipeline with approval workflow: staging environment → human approval → production",
        "Create a multi-stage deployment pipeline flowchart",
        "Show CI/CD: unit test, integration test, pass → staging, approved → prod, notify team",
        "Build a deployment pipeline diagram with environment promotion",
        "Flowchart for a pipeline requiring both automated tests and human approval",
        "CI/CD with two gates: automated test suite and manual production approval",
        "Diagram the full pipeline from code push to production notification",
        "Create a staged deployment flow: test, build, staging, approval decision, production",
        "Show a DevOps release pipeline with staging promotion and approval",
        "Full delivery pipeline with rejection and approval paths for production",
        "CI/CD flowchart: push code → tests → build Docker image → deploy staging → approve → prod",
        "Draw a complete deployment pipeline with automated and manual gates",
    ]
})

# ── F08  Document Approval ──────────────────────────────────────────────────────
SCENARIOS.append({
    "diagram": D("d_f08", "Document Approval Workflow",
        nodes=[
            N("n_start",   "pill",         170,  40, 160,  60, "Start",           "#ECFDF5","#34D399", tc="#064E3B", fw="700"),
            N("n_submit",  "parallelogram",170, 160, 160,  80, "Submit Document", "#F0F9FF","#38BDF8", tc="#0C4A6E"),
            N("n_auto",    "rect",         170, 300, 160,  80, "Auto-check Rules","#EEF2FF","#818CF8", tc="#1E1B4B"),
            N("n_review",  "rect",         170, 440, 160,  80, "Manual Review",   "#EEF2FF","#818CF8", tc="#1E1B4B"),
            N("n_dec",     "diamond",      155, 580, 190, 110, "Approved?",       "#FDF2F8","#F472B6", tc="#831843", fw="700"),
            N("n_revise",  "callout",      -40, 760, 160,  80, "Return for Edit", "#FFF1F2","#FB7185", tc="#881337"),
            N("n_archive", "roundedRect",  390, 760, 160,  80, "Sign & Archive",  "#F0FDF4","#4ADE80", tc="#14532D"),
            N("n_notify",  "rect",         390, 900, 160,  80, "Notify Author",   "#EEF2FF","#818CF8", tc="#1E1B4B"),
            N("n_end",     "pill",         390,1040, 160,  60, "End",             "#ECFDF5","#34D399", tc="#064E3B", fw="700"),
        ],
        edges=[
            E("e01","n_start",  "n_submit", "bottom","top"),
            E("e02","n_submit", "n_auto",   "bottom","top"),
            E("e03","n_auto",   "n_review", "bottom","top"),
            E("e04","n_review", "n_dec",    "bottom","top"),
            E("e05","n_dec",    "n_revise", "left",  "top",  "No", "#FB7185"),
            E("e06","n_dec",    "n_archive","right", "top",  "Yes","#4ADE80"),
            E("e07","n_archive","n_notify", "bottom","top"),
            E("e08","n_notify", "n_end",    "bottom","top"),
        ]),
    "prompts": [
        "Create a document approval workflow flowchart",
        "Draw an approval process diagram",
        "Document review and approval flow",
        "Show the document approval process with auto-check and manual review",
        "Approval workflow: submit, auto-check, manual review, approve or reject",
        "Flowchart for document submission and approval",
        "Build an approval flow with two review stages",
        "Document workflow: submit → auto-check → manual review → approved/rejected → notify",
        "Diagram a document approval process with rejection returning to author",
        "Show a document flow: submit, rules check, reviewer decision, archive or revise",
        "Approval flow with auto-rule checking then manual review decision",
        "Create a document lifecycle flow from submission to archival",
        "Show how a document gets reviewed and either approved or returned for editing",
        "Flowchart: submit doc, auto-check passes, reviewer approves or sends back",
        "Document approval with notification step after signing",
        "Build a flowchart for content approval in a publishing workflow",
        "Diagram approval flow with rejected path returning document to author",
        "Show a policy document approval workflow",
        "Document approval: auto-validate, reviewer checks, approve → archive, reject → revise",
        "Flowchart for a document review and sign-off process",
        "Draw a legal document approval workflow",
        "Approval process flowchart: submit → rules check → manual review → sign → notify",
        "Document management workflow with two decision outcomes",
        "Create a flowchart for contract approval",
        "Show the document review pipeline from submission to final archival",
    ]
})

# ── F09  Password Reset ─────────────────────────────────────────────────────────
SCENARIOS.append({
    "diagram": D("d_f09", "Password Reset Flow",
        nodes=[
            N("n_start",  "pill",         170,  40, 160,  60, "Start",            "#ECFDF5","#34D399", tc="#064E3B", fw="700"),
            N("n_req",    "roundedRect",  170, 160, 160,  80, "Request Reset",    "#EEF2FF","#818CF8", tc="#1E1B4B"),
            N("n_check",  "rect",         170, 300, 160,  80, "Validate Email",   "#EEF2FF","#818CF8", tc="#1E1B4B"),
            N("n_dec1",   "diamond",      155, 440, 190, 110, "Email Found?",     "#FDF2F8","#F472B6", tc="#831843", fw="700"),
            N("n_nouser", "callout",      -40, 620, 160,  80, "User Not Found",   "#FFF1F2","#FB7185", tc="#881337"),
            N("n_send",   "rect",         390, 620, 160,  80, "Send Reset Link",  "#EEF2FF","#818CF8", tc="#1E1B4B"),
            N("n_click",  "rect",         390, 760, 160,  80, "Click Reset Link", "#EEF2FF","#818CF8", tc="#1E1B4B"),
            N("n_newpwd", "parallelogram",390, 900, 160,  80, "Enter New Password","#F0F9FF","#38BDF8",tc="#0C4A6E"),
            N("n_update", "rect",         390,1040, 160,  80, "Update Password",  "#EEF2FF","#818CF8", tc="#1E1B4B"),
            N("n_end",    "pill",         390,1180, 160,  60, "Done",             "#ECFDF5","#34D399", tc="#064E3B", fw="700"),
        ],
        edges=[
            E("e01","n_start", "n_req",    "bottom","top"),
            E("e02","n_req",   "n_check",  "bottom","top"),
            E("e03","n_check", "n_dec1",   "bottom","top"),
            E("e04","n_dec1",  "n_nouser", "left",  "top",  "No", "#FB7185"),
            E("e05","n_dec1",  "n_send",   "right", "top",  "Yes","#4ADE80"),
            E("e06","n_send",  "n_click",  "bottom","top"),
            E("e07","n_click", "n_newpwd", "bottom","top"),
            E("e08","n_newpwd","n_update", "bottom","top"),
            E("e09","n_update","n_end",    "bottom","top"),
        ]),
    "prompts": [
        "Create a password reset flowchart",
        "Draw the forgot password flow",
        "Password reset process diagram",
        "Show the password recovery flow from request to completion",
        "Build a flowchart for resetting a user password via email link",
        "Forgot password flow: request, validate email, send link, click, enter new password, update",
        "Password reset: email check → send link → click → new password → done",
        "Diagram the password reset process for a web application",
        "Show a password recovery flow with user-not-found error path",
        "Flowchart: user requests reset, system checks email, sends link, user enters new password",
        "Create a forgot password flow with email validation step",
        "Password reset flow with user not found branch",
        "Show the password recovery process: request → validate → send link → reset",
        "Flowchart for password reset via email",
        "Build a password change flow triggered by forgot password request",
        "Password reset diagram: validate email address, send token link, enter new password",
        "Forgot password flowchart with error handling for unknown email",
        "Show the complete password recovery journey",
        "Create a secure password reset flow with email verification",
        "Diagram the forgot-password UX flow from request to successful reset",
        "Password reset: input email, check if exists, send link if yes, update on click",
        "Draw a password recovery flowchart for a user account system",
        "Show how users recover account access via password reset email",
        "Forgot password flowchart: request → email check → link sent → new password → done",
        "Create a password reset process with not-found error path",
    ]
})

# ── F10  User Registration ──────────────────────────────────────────────────────
SCENARIOS.append({
    "diagram": D("d_f10", "User Registration Flow",
        nodes=[
            N("n_start",  "pill",         170,  40, 160,  60, "Start",              "#ECFDF5","#34D399", tc="#064E3B", fw="700"),
            N("n_form",   "parallelogram",170, 160, 160,  80, "Fill Sign-up Form",  "#F0F9FF","#38BDF8", tc="#0C4A6E"),
            N("n_valid",  "rect",         170, 300, 160,  80, "Validate Input",     "#EEF2FF","#818CF8", tc="#1E1B4B"),
            N("n_dec",    "diamond",      155, 440, 190, 110, "Valid?",             "#FDF2F8","#F472B6", tc="#831843", fw="700"),
            N("n_errors", "callout",      -40, 620, 160,  80, "Show Errors",        "#FFF1F2","#FB7185", tc="#881337"),
            N("n_create", "rect",         390, 620, 160,  80, "Create Account",     "#EEF2FF","#818CF8", tc="#1E1B4B"),
            N("n_email",  "rect",         390, 760, 160,  80, "Send Verify Email",  "#EEF2FF","#818CF8", tc="#1E1B4B"),
            N("n_click",  "rect",         390, 900, 160,  80, "User Clicks Link",   "#EEF2FF","#818CF8", tc="#1E1B4B"),
            N("n_active", "roundedRect",  390,1040, 160,  80, "Activate Account",   "#F0FDF4","#4ADE80", tc="#14532D"),
            N("n_end",    "pill",         390,1180, 160,  60, "End",                "#ECFDF5","#34D399", tc="#064E3B", fw="700"),
        ],
        edges=[
            E("e01","n_start", "n_form",  "bottom","top"),
            E("e02","n_form",  "n_valid", "bottom","top"),
            E("e03","n_valid", "n_dec",   "bottom","top"),
            E("e04","n_dec",   "n_errors","left",  "top",  "No", "#FB7185"),
            E("e05","n_dec",   "n_create","right", "top",  "Yes","#4ADE80"),
            E("e06","n_create","n_email", "bottom","top"),
            E("e07","n_email", "n_click", "bottom","top"),
            E("e08","n_click", "n_active","bottom","top"),
            E("e09","n_active","n_end",   "bottom","top"),
        ]),
    "prompts": [
        "Create a user registration flowchart",
        "Draw a sign-up process flow diagram",
        "User account creation flow",
        "Show the registration flow with email verification",
        "Build a sign-up flowchart: fill form, validate, create account, verify email",
        "Registration flow with form validation and email confirmation",
        "Diagram the user onboarding registration process",
        "Sign-up flow: form → validate → decision → create account → email link → activate",
        "User registration with email verification flowchart",
        "Show how a new user creates an account with email confirmation step",
        "Registration diagram: fill form, validate input, errors or account creation",
        "Flowchart for new user account registration with email verification",
        "Create a registration flow with form validation error handling",
        "Show the complete sign-up journey from form to activated account",
        "User registration: input form, validate, create account, send verification email, activate",
        "Sign-up process with validation decision and email confirmation",
        "Build a flowchart for user account creation with activation step",
        "Registration flow: fill form → validate → show errors or create account → verify email",
        "Diagram new user registration with email link activation",
        "Create a sign-up flowchart with error state for invalid form data",
        "User registration process: form submission, validation, account creation, activation",
        "Show the account creation flow with email-based verification",
        "Draw a registration flowchart that shows both valid and invalid form paths",
        "Registration flow with two outcomes: errors shown or account created and verified",
        "Flowchart: user fills sign-up form, system validates, creates account, sends email",
    ]
})

# ── F11  File Upload & Processing ───────────────────────────────────────────────
SCENARIOS.append({
    "diagram": D("d_f11", "File Upload & Processing",
        nodes=[
            N("n_start",   "pill",         170,  40, 160,  60, "Start",           "#ECFDF5","#34D399", tc="#064E3B", fw="700"),
            N("n_select",  "parallelogram",170, 160, 160,  80, "Select File",     "#F0F9FF","#38BDF8", tc="#0C4A6E"),
            N("n_check",   "rect",         170, 300, 160,  80, "Validate Type/Size","#EEF2FF","#818CF8",tc="#1E1B4B"),
            N("n_dec",     "diamond",      155, 440, 190, 110, "Valid?",          "#FDF2F8","#F472B6", tc="#831843", fw="700"),
            N("n_errf",    "callout",      -40, 620, 160,  80, "File Error",      "#FFF1F2","#FB7185", tc="#881337"),
            N("n_upload",  "rect",         390, 620, 160,  80, "Upload to Storage","#EFF6FF","#60A5FA",tc="#1E3A8A"),
            N("n_process", "hexagon",      390, 760, 160,  80, "Process File",    "#EEF2FF","#818CF8", tc="#1E1B4B"),
            N("n_db",      "cylinder",     390, 900, 160,  80, "Update Database", "#EFF6FF","#60A5FA", tc="#1E3A8A"),
            N("n_notify",  "rect",         390,1040, 160,  80, "Notify User",     "#EEF2FF","#818CF8", tc="#1E1B4B"),
            N("n_end",     "pill",         390,1180, 160,  60, "End",             "#ECFDF5","#34D399", tc="#064E3B", fw="700"),
        ],
        edges=[
            E("e01","n_start",  "n_select", "bottom","top"),
            E("e02","n_select", "n_check",  "bottom","top"),
            E("e03","n_check",  "n_dec",    "bottom","top"),
            E("e04","n_dec",    "n_errf",   "left",  "top",  "No", "#FB7185"),
            E("e05","n_dec",    "n_upload", "right", "top",  "Yes","#4ADE80"),
            E("e06","n_upload", "n_process","bottom","top"),
            E("e07","n_process","n_db",     "bottom","top"),
            E("e08","n_db",     "n_notify", "bottom","top"),
            E("e09","n_notify", "n_end",    "bottom","top"),
        ]),
    "prompts": [
        "Create a file upload and processing flowchart",
        "Draw a file upload flow diagram",
        "File upload process with validation and storage",
        "Show the flow for uploading and processing a file",
        "Build a flowchart: select file, validate, upload, process, update DB, notify",
        "File upload flow with type and size validation",
        "Diagram file upload: validate type/size → upload to storage → process → update DB",
        "Show a file upload process with error handling for invalid files",
        "File upload flowchart with storage, processing, and database update steps",
        "Create a document upload flow with validation decision",
        "Flowchart: select file, check type/size, if valid upload and process, else show error",
        "Show how a file gets uploaded, processed, and stored",
        "File processing pipeline: upload → validate → store → process → DB → notify user",
        "Build a media upload flow with post-processing steps",
        "Diagram an image/file upload process from selection to user notification",
        "File upload with pipeline: select, validate, upload to S3-like storage, process, notify",
        "Create a file upload flowchart with invalid file error branch",
        "Show the upload pipeline: validate → upload to blob storage → transform → update records",
        "Upload flow diagram with hexagon for processing and cylinder for database",
        "Flowchart for a file upload feature in a web application",
        "File upload and transformation flow with user notification at end",
        "Show file upload: type check, size check, upload, process, save metadata, done",
        "Create a document processing flow from upload to database record",
        "File upload flowchart with three backend stages after validation",
        "Draw a flow for handling file uploads with processing and storage",
    ]
})

# ── F12  Support Ticket Routing ─────────────────────────────────────────────────
SCENARIOS.append({
    "diagram": D("d_f12", "Support Ticket Routing",
        nodes=[
            N("n_start",  "pill",         170,  40, 160,  60, "Start",            "#ECFDF5","#34D399", tc="#064E3B", fw="700"),
            N("n_submit", "parallelogram",170, 160, 160,  80, "Submit Ticket",    "#F0F9FF","#38BDF8", tc="#0C4A6E"),
            N("n_auto",   "rect",         170, 300, 160,  80, "Auto-classify",    "#EEF2FF","#818CF8", tc="#1E1B4B"),
            N("n_dec",    "diamond",      155, 440, 190, 110, "High Severity?",   "#FDF2F8","#F472B6", tc="#831843", fw="700"),
            N("n_esc",    "roundedRect",  390, 620, 160,  80, "Escalate to L2",   "#FFF1F2","#FB7185", tc="#881337"),
            N("n_queue",  "cylinder",     -40, 620, 160,  80, "L1 Support Queue", "#EFF6FF","#60A5FA", tc="#1E3A8A"),
            N("n_assign", "rect",         170, 780, 160,  80, "Assign Agent",     "#EEF2FF","#818CF8", tc="#1E1B4B"),
            N("n_resolve","roundedRect",  170, 920, 160,  80, "Resolve Issue",    "#F0FDF4","#4ADE80", tc="#14532D"),
            N("n_close",  "pill",         170,1060, 160,  60, "Close Ticket",     "#ECFDF5","#34D399", tc="#064E3B", fw="700"),
        ],
        edges=[
            E("e01","n_start", "n_submit","bottom","top"),
            E("e02","n_submit","n_auto",  "bottom","top"),
            E("e03","n_auto",  "n_dec",   "bottom","top"),
            E("e04","n_dec",   "n_esc",   "right", "top",  "Yes","#FB7185"),
            E("e05","n_dec",   "n_queue", "left",  "top",  "No", "#6B7280"),
            E("e06","n_esc",   "n_assign","bottom","left"),
            E("e07","n_queue", "n_assign","right", "left"),
            E("e08","n_assign","n_resolve","bottom","top"),
            E("e09","n_resolve","n_close","bottom","top"),
        ]),
    "prompts": [
        "Create a support ticket routing flowchart",
        "Draw a helpdesk ticket flow diagram",
        "Support ticket process with severity routing",
        "Show the ticket triage flow: submit, classify, route by severity",
        "Build a support workflow: submit ticket → auto-classify → severity decision → route",
        "Ticket routing flow with L1 and L2 escalation",
        "Customer support flow: submit → classify → high severity escalates to L2",
        "Diagram a helpdesk routing process with severity triage",
        "Support flow: ticket submitted, auto-classified, high severity goes to L2, low to L1 queue",
        "Show the support ticket lifecycle from submission to resolution",
        "Flowchart for support ticket triage and routing",
        "Build a customer service flow with automatic severity routing",
        "Ticket triage diagram with escalation for critical issues",
        "Support process: submit, auto-triage, branch on severity, assign agent, resolve, close",
        "Create a helpdesk flow with two routing paths based on priority",
        "Show how support tickets get classified and routed to the right team",
        "Support ticket routing: auto-classify, high severity → L2 escalation, low → L1 queue",
        "Diagram an IT helpdesk ticket workflow with severity branching",
        "Ticket flow from submission to closure with routing logic",
        "Build a support flow that escalates high-priority tickets to second-level support",
        "Create a customer support routing diagram with auto-classification",
        "Helpdesk flow: submit ticket, system classifies, routes to L1 or L2, assigns, resolves",
        "Show the complete support ticket journey from open to close",
        "Support flowchart with cylinder for queue and escalation branch for high severity",
        "Diagram a support ticket workflow with triage decision node",
    ]
})

# ── F13  API Request Handling ───────────────────────────────────────────────────
SCENARIOS.append({
    "diagram": D("d_f13", "API Request Handling",
        nodes=[
            N("n_req",    "parallelogram",170,  40, 160,  80, "Incoming Request", "#F0F9FF","#38BDF8", tc="#0C4A6E"),
            N("n_auth",   "rect",         170, 180, 160,  80, "Check Auth Token", "#EEF2FF","#818CF8", tc="#1E1B4B"),
            N("n_dec1",   "diamond",      155, 320, 190, 110, "Authorized?",      "#FDF2F8","#F472B6", tc="#831843", fw="700"),
            N("n_401",    "callout",      -40, 500, 160,  80, "Return 401",       "#FFF1F2","#FB7185", tc="#881337"),
            N("n_rate",   "rect",         390, 500, 160,  80, "Check Rate Limit", "#EEF2FF","#818CF8", tc="#1E1B4B"),
            N("n_dec2",   "diamond",      375, 640, 190, 110, "Limit OK?",        "#FDF2F8","#F472B6", tc="#831843", fw="700"),
            N("n_429",    "callout",      570, 820, 160,  80, "Return 429",       "#FFF1F2","#FB7185", tc="#881337"),
            N("n_proc",   "hexagon",      200, 820, 160,  80, "Process Request",  "#EEF2FF","#818CF8", tc="#1E1B4B"),
            N("n_resp",   "parallelogram",200, 960, 160,  80, "Return Response",  "#F0F9FF","#38BDF8", tc="#0C4A6E"),
        ],
        edges=[
            E("e01","n_req",  "n_auth", "bottom","top"),
            E("e02","n_auth", "n_dec1", "bottom","top"),
            E("e03","n_dec1", "n_401",  "left",  "top",  "No", "#FB7185"),
            E("e04","n_dec1", "n_rate", "right", "top",  "Yes","#4ADE80"),
            E("e05","n_rate", "n_dec2", "bottom","top"),
            E("e06","n_dec2", "n_429",  "right", "top",  "No", "#FB7185"),
            E("e07","n_dec2", "n_proc", "left",  "top",  "Yes","#4ADE80"),
            E("e08","n_proc", "n_resp", "bottom","top"),
        ]),
    "prompts": [
        "Create an API request handling flowchart",
        "Draw an API authentication and rate limiting flow",
        "Flowchart showing API request pipeline with auth and rate limit checks",
        "API gateway flow: check auth token, check rate limit, process or reject",
        "Show how an API handles incoming requests with auth and throttling",
        "Build a flowchart: incoming request → auth check → 401 or rate limit check → 429 or process",
        "API middleware flow diagram with authorization and rate limiting",
        "Diagram an API request pipeline: auth → rate limit → process → response",
        "Show the API request lifecycle with two validation gates",
        "API flow: unauthorized returns 401, rate exceeded returns 429, else process",
        "Create a REST API request flowchart with auth check and throttling",
        "API request diagram: check token → authorized decision → rate limit decision → handler",
        "Flowchart for API middleware: authentication then rate limiting then processing",
        "Show two decision nodes in API flow: auth check and rate limit check",
        "API request handling: auth fails → 401, rate limit fails → 429, success → process",
        "Build a flowchart for handling HTTP API requests with security checks",
        "Diagram the API request journey from receipt to response",
        "Show an API with sequential guards: auth gate and rate limit gate",
        "Create an API flow that returns proper HTTP error codes on failure",
        "API gateway flowchart: incoming request, validate token, check throttle, process",
        "Flowchart showing API request handling with 401 and 429 error responses",
        "Draw a flow for API request validation and processing",
        "API processing flow with two gatekeeping decision nodes",
        "Show the complete API request flow from receipt to response with error paths",
        "Create a diagram for an API that checks auth and rate limits before processing",
    ]
})

# ── F14  Data Ingestion Pipeline ────────────────────────────────────────────────
SCENARIOS.append({
    "diagram": D("d_f14", "Data Ingestion Pipeline",
        nodes=[
            N("n_src",    "cylinder",     40, 160, 160, 80, "Data Source",     "#EFF6FF","#60A5FA", tc="#1E3A8A"),
            N("n_val",    "diamond",     250, 155, 160, 90, "Validate Schema", "#FDF2F8","#F472B6", tc="#831843"),
            N("n_dlq",    "callout",     250, 310, 160, 80, "Dead Letter Queue","#FFF1F2","#FB7185",tc="#881337"),
            N("n_trans",  "hexagon",     470, 160, 160, 80, "Transform Data",  "#EEF2FF","#818CF8", tc="#1E1B4B"),
            N("n_enrich", "rect",        690, 160, 160, 80, "Enrich Data",     "#EEF2FF","#818CF8", tc="#1E1B4B"),
            N("n_load",   "cylinder",    910, 160, 160, 80, "Load to Warehouse","#EFF6FF","#60A5FA",tc="#1E3A8A"),
            N("n_report", "roundedRect",1130, 160, 160, 80, "Trigger Report",  "#F0FDF4","#4ADE80", tc="#14532D"),
        ],
        edges=[
            E("e01","n_src",   "n_val",   "right","left"),
            E("e02","n_val",   "n_dlq",   "bottom","top", "Invalid","#FB7185"),
            E("e03","n_val",   "n_trans", "right","left", "Valid",  "#4ADE80"),
            E("e04","n_trans", "n_enrich","right","left"),
            E("e05","n_enrich","n_load",  "right","left"),
            E("e06","n_load",  "n_report","right","left"),
        ], vx=20, vy=100),
    "prompts": [
        "Create a data ingestion pipeline flowchart",
        "Draw a data pipeline flow diagram",
        "ETL pipeline flow: extract, validate, transform, enrich, load",
        "Show the data ingestion process from source to warehouse",
        "Build a data processing pipeline diagram",
        "Horizontal data pipeline: source → validate → transform → enrich → load → report",
        "Data ingestion flow with invalid records going to dead letter queue",
        "Diagram a data pipeline with schema validation and dead letter handling",
        "ETL flow: data source, schema check, transform, enrich, warehouse load, report",
        "Show a data pipeline where invalid records are redirected to DLQ",
        "Create a left-to-right data ingestion flowchart",
        "Data flow diagram: source → validate schema → transform → enrich → load → trigger report",
        "Build an ETL pipeline flowchart with error routing",
        "Show the data processing stages from raw source to data warehouse",
        "Horizontal pipeline: read data, validate, dead-letter invalids, transform, enrich, load",
        "Create a data ingestion flow with DLQ branch for bad records",
        "Diagram a batch data processing pipeline",
        "Show a data pipeline that validates schema and routes failures to DLQ",
        "ETL pipeline with dead letter queue for failed validation",
        "Data ingestion: source → schema validation → transform → enrich → warehouse → report",
        "Build a horizontal data flow with cylinder source and warehouse shapes",
        "Pipeline diagram: validate records, transform valid ones, enrich, load to DW",
        "Create a flowchart for a data processing job with error handling",
        "Show how raw data flows through validation, transformation, and loading steps",
        "Data pipeline flowchart from source to business intelligence report trigger",
    ]
})

# ── F15  Order Fulfillment ──────────────────────────────────────────────────────
SCENARIOS.append({
    "diagram": D("d_f15", "Order Fulfillment",
        nodes=[
            N("n_order",  "parallelogram",170,  40, 160,  80, "Order Received",  "#F0F9FF","#38BDF8", tc="#0C4A6E"),
            N("n_inv",    "rect",         170, 180, 160,  80, "Check Inventory", "#EEF2FF","#818CF8", tc="#1E1B4B"),
            N("n_dec",    "diamond",      155, 320, 190, 110, "In Stock?",       "#FDF2F8","#F472B6", tc="#831843", fw="700"),
            N("n_back",   "callout",      -40, 500, 160,  80, "Backorder",       "#FFF1F2","#FB7185", tc="#881337"),
            N("n_reserve","rect",         390, 500, 160,  80, "Reserve Items",   "#EEF2FF","#818CF8", tc="#1E1B4B"),
            N("n_pay",    "rect",         390, 640, 160,  80, "Process Payment", "#EEF2FF","#818CF8", tc="#1E1B4B"),
            N("n_pack",   "rect",         390, 780, 160,  80, "Pack Order",      "#EEF2FF","#818CF8", tc="#1E1B4B"),
            N("n_ship",   "rect",         390, 920, 160,  80, "Ship Order",      "#EEF2FF","#818CF8", tc="#1E1B4B"),
            N("n_track",  "roundedRect",  390,1060, 160,  80, "Update Tracking", "#F0FDF4","#4ADE80", tc="#14532D"),
            N("n_end",    "pill",         390,1200, 160,  60, "Delivered",       "#ECFDF5","#34D399", tc="#064E3B", fw="700"),
        ],
        edges=[
            E("e01","n_order",  "n_inv",    "bottom","top"),
            E("e02","n_inv",    "n_dec",    "bottom","top"),
            E("e03","n_dec",    "n_back",   "left",  "top",  "No", "#FB7185"),
            E("e04","n_dec",    "n_reserve","right", "top",  "Yes","#4ADE80"),
            E("e05","n_reserve","n_pay",    "bottom","top"),
            E("e06","n_pay",    "n_pack",   "bottom","top"),
            E("e07","n_pack",   "n_ship",   "bottom","top"),
            E("e08","n_ship",   "n_track",  "bottom","top"),
            E("e09","n_track",  "n_end",    "bottom","top"),
        ]),
    "prompts": [
        "Create an order fulfillment flowchart",
        "Draw an e-commerce order processing flow",
        "Order fulfillment process diagram",
        "Show the order lifecycle from receipt to delivery",
        "Build a fulfillment flow: order received, check stock, reserve, pay, pack, ship, deliver",
        "Order processing flow with backorder handling when items are out of stock",
        "Diagram the order fulfillment pipeline",
        "E-commerce order flow: inventory check, reserve, process payment, pack, ship, track",
        "Show the complete order fulfillment process from order to delivery",
        "Order flow with in-stock decision: yes → reserve and fulfill, no → backorder",
        "Create a warehouse fulfillment flowchart",
        "Order processing diagram with inventory check and backorder path",
        "Fulfillment flow: receive order, check inventory, reserve items, payment, pack, ship",
        "Show how an e-commerce order gets processed and delivered",
        "Order management flow from customer order to doorstep delivery",
        "Build a flowchart for the complete order-to-ship process",
        "Diagram order fulfillment with inventory check and backorder decision",
        "E-commerce backend flow: order in → stock check → fulfill or backorder",
        "Show the order lifecycle: received, inventory, reserve, pay, pack, ship, deliver",
        "Create a flow for order management with stock availability decision",
        "Fulfillment flowchart showing the path from order to package delivery",
        "Draw the order processing pipeline with backorder branch for out-of-stock",
        "Show a retail order fulfillment flow with 9 steps",
        "Order fulfillment diagram with tracking update before delivery",
        "E-commerce fulfillment: check stock → reserve items → charge card → pack → ship → done",
    ]
})

# ── F16  Feature Flag Evaluation ────────────────────────────────────────────────
SCENARIOS.append({
    "diagram": D("d_f16", "Feature Flag Evaluation",
        nodes=[
            N("n_req",    "parallelogram",170,  40, 160,  80, "Incoming Request","#F0F9FF","#38BDF8", tc="#0C4A6E"),
            N("n_ctx",    "rect",         170, 180, 160,  80, "Load User Context","#EEF2FF","#818CF8",tc="#1E1B4B"),
            N("n_flag",   "rect",         170, 320, 160,  80, "Check Feature Flag","#EEF2FF","#818CF8",tc="#1E1B4B"),
            N("n_dec",    "diamond",      155, 460, 190, 110, "Flag Enabled?",   "#FDF2F8","#F472B6", tc="#831843", fw="700"),
            N("n_new",    "roundedRect",  390, 640, 160,  80, "New Feature",     "#F0FDF4","#4ADE80", tc="#14532D"),
            N("n_old",    "roundedRect",  -40, 640, 160,  80, "Legacy Feature",  "#EEF2FF","#818CF8", tc="#1E1B4B"),
            N("n_resp",   "parallelogram",170, 800, 160,  80, "Return Response", "#F0F9FF","#38BDF8", tc="#0C4A6E"),
        ],
        edges=[
            E("e01","n_req",  "n_ctx",  "bottom","top"),
            E("e02","n_ctx",  "n_flag", "bottom","top"),
            E("e03","n_flag", "n_dec",  "bottom","top"),
            E("e04","n_dec",  "n_new",  "right", "top",  "Yes","#4ADE80"),
            E("e05","n_dec",  "n_old",  "left",  "top",  "No", "#6B7280"),
            E("e06","n_new",  "n_resp", "bottom","top"),
            E("e07","n_old",  "n_resp", "bottom","top"),
        ]),
    "prompts": [
        "Create a feature flag evaluation flowchart",
        "Draw a feature toggle flow diagram",
        "Feature flag flow: load context, check flag, new or legacy feature",
        "Show how feature flags route users to different code paths",
        "Build a flowchart for feature flag evaluation with two code paths",
        "Feature toggle diagram: request → load context → check flag → new or old feature",
        "Diagram a feature flag check with new feature and fallback paths",
        "Show the feature flag decision flow for A/B testing",
        "Feature flag flow: flag enabled goes to new feature, disabled goes to legacy",
        "Create a feature flag routing diagram",
        "Flowchart for feature flag: enabled → new code path, disabled → old code path",
        "Show a request flowing through a feature flag check",
        "Feature toggle: load user context, check flag, branch to new or legacy feature",
        "Build a feature flag diagram for gradual feature rollout",
        "Diagram how a feature flag switches between old and new implementations",
        "Create a flow showing A/B test routing via feature flag",
        "Feature flag evaluation: load context, check flag, route to new or fallback path",
        "Show feature flag decision with two diverging paths that reconverge at response",
        "Flowchart: incoming request, load user config, check feature flag, serve new or legacy",
        "Feature flag flow with context loading and two parallel outcome paths",
        "Draw a diagram showing feature toggle logic in a web application",
        "Feature flag routing flow for progressive feature delivery",
        "Show the complete feature flag evaluation from request to response",
        "Flowchart for LaunchDarkly-style feature flag evaluation",
        "Create a feature flag diagram: enabled → new feature, disabled → legacy feature",
    ]
})

# ── F17  Cache Read-Through ─────────────────────────────────────────────────────
SCENARIOS.append({
    "diagram": D("d_f17", "Cache Read-Through",
        nodes=[
            N("n_req",    "parallelogram",170,  40, 160,  80, "Request",         "#F0F9FF","#38BDF8", tc="#0C4A6E"),
            N("n_cache",  "cylinder",     170, 180, 160,  80, "Check Cache",     "#EFF6FF","#60A5FA", tc="#1E3A8A"),
            N("n_dec",    "diamond",      155, 320, 190, 110, "Cache Hit?",      "#FDF2F8","#F472B6", tc="#831843", fw="700"),
            N("n_hit",    "roundedRect",  390, 500, 160,  80, "Return Cached",   "#F0FDF4","#4ADE80", tc="#14532D"),
            N("n_db",     "cylinder",     -40, 500, 160,  80, "Query Database",  "#EFF6FF","#60A5FA", tc="#1E3A8A"),
            N("n_store",  "rect",         -40, 640, 160,  80, "Store in Cache",  "#EEF2FF","#818CF8", tc="#1E1B4B"),
            N("n_resp",   "parallelogram",170, 780, 160,  80, "Return Response", "#F0F9FF","#38BDF8", tc="#0C4A6E"),
        ],
        edges=[
            E("e01","n_req",  "n_cache","bottom","top"),
            E("e02","n_cache","n_dec",  "bottom","top"),
            E("e03","n_dec",  "n_hit",  "right", "top",  "Yes","#4ADE80"),
            E("e04","n_dec",  "n_db",   "left",  "top",  "No", "#6B7280"),
            E("e05","n_db",   "n_store","bottom","top"),
            E("e06","n_store","n_resp", "bottom","top"),
            E("e07","n_hit",  "n_resp", "bottom","top"),
        ]),
    "prompts": [
        "Create a cache read-through flowchart",
        "Draw a cache lookup flow diagram",
        "Caching flow: check cache, hit returns cached, miss queries DB and stores",
        "Show the cache hit/miss flow",
        "Build a cache read-through diagram with cache miss DB fallback",
        "Cache flow: cache hit → return cached, cache miss → query DB → store → return",
        "Diagram the read-through caching pattern",
        "Show how a cache check works with fallback to database on miss",
        "Cache lookup flowchart with cylinder shapes for cache and database",
        "Create a caching flow: incoming request, check cache, hit or miss decision",
        "Flowchart: check Redis cache, if hit return data, if miss query DB and populate cache",
        "Read-through cache pattern diagram",
        "Show cache hit and miss paths in a flowchart",
        "Build a cache read diagram with two paths: fast cache return or DB query",
        "Cache flow with cache-aside pattern: check cache → decision → return or fetch from DB",
        "Diagram caching layer: request comes in, check cache, serve from cache or from DB",
        "Create a flow showing read-through caching with cache population on miss",
        "Show the caching layer flow with cylinder for Redis and database",
        "Cache lookup flow: request → cache check → hit? Yes: return cached. No: DB query → cache → return",
        "Flowchart for application caching with read-through pattern",
        "Diagram cache miss handling: query DB, store result in cache, return to caller",
        "Create a cache lookup diagram with fast path and slow path",
        "Show read-through cache pattern: check → hit or miss → fetch from DB if miss",
        "Flowchart for Redis caching with database fallback on cache miss",
        "Cache-aside pattern flowchart: check cache hit, if miss populate from DB",
    ]
})

# ── F18  Incident Response ──────────────────────────────────────────────────────
SCENARIOS.append({
    "diagram": D("d_f18", "Incident Response",
        nodes=[
            N("n_alert",  "pill",         170,  40, 160,  60, "Alert Triggered", "#FFF1F2","#FB7185", tc="#881337", fw="700"),
            N("n_page",   "rect",         170, 160, 160,  80, "Page On-Call",    "#EEF2FF","#818CF8", tc="#1E1B4B"),
            N("n_inv",    "rect",         170, 300, 160,  80, "Investigate",     "#EEF2FF","#818CF8", tc="#1E1B4B"),
            N("n_dec",    "diamond",      155, 440, 190, 110, "P1/P2?",          "#FDF2F8","#F472B6", tc="#831843", fw="700"),
            N("n_war",    "rect",         390, 620, 160,  80, "Open War Room",   "#FFF1F2","#FB7185", tc="#881337"),
            N("n_std",    "rect",         -40, 620, 160,  80, "Standard Fix",    "#EEF2FF","#818CF8", tc="#1E1B4B"),
            N("n_fix",    "rect",         170, 780, 160,  80, "Implement Fix",   "#EEF2FF","#818CF8", tc="#1E1B4B"),
            N("n_deploy", "roundedRect",  170, 920, 160,  80, "Deploy Hotfix",   "#F0FDF4","#4ADE80", tc="#14532D"),
            N("n_pm",     "callout",      170,1060, 160,  80, "Post-mortem",     "#FFFBEB","#F59E0B", tc="#78350F"),
            N("n_end",    "pill",         170,1200, 160,  60, "Resolved",        "#ECFDF5","#34D399", tc="#064E3B", fw="700"),
        ],
        edges=[
            E("e01","n_alert","n_page", "bottom","top"),
            E("e02","n_page", "n_inv",  "bottom","top"),
            E("e03","n_inv",  "n_dec",  "bottom","top"),
            E("e04","n_dec",  "n_war",  "right", "top",  "Yes","#FB7185"),
            E("e05","n_dec",  "n_std",  "left",  "top",  "No", "#6B7280"),
            E("e06","n_war",  "n_fix",  "bottom","left"),
            E("e07","n_std",  "n_fix",  "right", "left"),
            E("e08","n_fix",  "n_deploy","bottom","top"),
            E("e09","n_deploy","n_pm",  "bottom","top"),
            E("e10","n_pm",   "n_end",  "bottom","top"),
        ]),
    "prompts": [
        "Create an incident response flowchart",
        "Draw an on-call incident handling flow",
        "Incident response process diagram",
        "Show the incident lifecycle from alert to post-mortem",
        "Build an incident flow: alert, page on-call, investigate, severity triage, fix, deploy",
        "Incident management flow with P1/P2 escalation to war room",
        "Diagram an on-call incident response process",
        "Show incident flow: alert triggers page, investigate, high severity → war room",
        "Create a flowchart for handling production incidents",
        "Incident response: alert → page on-call → investigate → P1? → war room or standard fix",
        "On-call runbook flow: page triggered, investigation, severity routing, fix, post-mortem",
        "Show an incident response flow with post-mortem at the end",
        "Diagram the SRE incident response process",
        "Incident flow: triggered alert, on-call response, triage, fix, deploy hotfix, post-mortem",
        "Build a flowchart for production outage response",
        "Incident management: alert → page → investigate → P1/P2 decision → war room or normal fix",
        "Show how an engineering team responds to production incidents",
        "Create an SRE incident response diagram with severity branching",
        "Incident response flow from alert to resolved status with post-mortem",
        "On-call incident diagram: alert, investigate, critical branch to war room, hotfix, PM",
        "Draw a process for handling service outages",
        "Incident response flowchart with war room escalation for critical issues",
        "Show the complete incident lifecycle: alert → fix → post-mortem",
        "SRE incident flow: page on-call, triage severity, war room if critical, deploy fix",
        "Create a flowchart for production incident management from alert to resolution",
    ]
})

# ── F19  Blue/Green Deployment ──────────────────────────────────────────────────
SCENARIOS.append({
    "diagram": D("d_f19", "Blue/Green Deployment",
        nodes=[
            N("n_start",  "pill",         170,  40, 160,  60, "Start Release",   "#ECFDF5","#34D399", tc="#064E3B", fw="700"),
            N("n_build",  "rect",         170, 160, 160,  80, "Build New Image", "#EEF2FF","#818CF8", tc="#1E1B4B"),
            N("n_green",  "roundedRect",  170, 300, 160,  80, "Deploy to Green", "#F0FDF4","#4ADE80", tc="#14532D"),
            N("n_smoke",  "rect",         170, 440, 160,  80, "Run Smoke Tests", "#EEF2FF","#818CF8", tc="#1E1B4B"),
            N("n_dec",    "diamond",      155, 580, 190, 110, "Healthy?",        "#FDF2F8","#F472B6", tc="#831843", fw="700"),
            N("n_fail",   "callout",      -40, 760, 160,  80, "Rollback Green",  "#FFF1F2","#FB7185", tc="#881337"),
            N("n_switch", "rect",         390, 760, 160,  80, "Switch Traffic",  "#EEF2FF","#818CF8", tc="#1E1B4B"),
            N("n_monitor","rect",         390, 900, 160,  80, "Monitor Metrics", "#EEF2FF","#818CF8", tc="#1E1B4B"),
            N("n_dec2",   "diamond",      375,1040, 190, 110, "Stable?",         "#FDF2F8","#F472B6", tc="#831843", fw="700"),
            N("n_rollb",  "callout",      560,1220, 160,  80, "Rollback to Blue","#FFF1F2","#FB7185", tc="#881337"),
            N("n_retire", "roundedRect",  200,1220, 160,  80, "Retire Blue",     "#F0FDF4","#4ADE80", tc="#14532D"),
            N("n_end",    "pill",         200,1360, 160,  60, "Done",            "#ECFDF5","#34D399", tc="#064E3B", fw="700"),
        ],
        edges=[
            E("e01","n_start",  "n_build",  "bottom","top"),
            E("e02","n_build",  "n_green",  "bottom","top"),
            E("e03","n_green",  "n_smoke",  "bottom","top"),
            E("e04","n_smoke",  "n_dec",    "bottom","top"),
            E("e05","n_dec",    "n_fail",   "left",  "top",  "No", "#FB7185"),
            E("e06","n_dec",    "n_switch", "right", "top",  "Yes","#4ADE80"),
            E("e07","n_switch", "n_monitor","bottom","top"),
            E("e08","n_monitor","n_dec2",   "bottom","top"),
            E("e09","n_dec2",   "n_rollb",  "right", "top",  "No", "#FB7185"),
            E("e10","n_dec2",   "n_retire", "left",  "top",  "Yes","#4ADE80"),
            E("e11","n_retire", "n_end",    "bottom","top"),
        ]),
    "prompts": [
        "Create a blue/green deployment flowchart",
        "Draw a blue-green deployment flow diagram",
        "Blue/green deployment with rollback capability",
        "Show the blue/green deployment process with smoke tests and traffic switch",
        "Deployment flow: build image, deploy green, smoke test, switch traffic, monitor, retire blue",
        "Blue-green deployment with health check and rollback on failure",
        "Diagram a zero-downtime deployment using blue/green strategy",
        "Show blue/green deploy: deploy green, test, healthy? yes switch traffic, no rollback",
        "Build a deployment flowchart with two health decision gates",
        "Blue/green deployment flow with monitoring after traffic switch",
        "Create a release flow using blue/green strategy with smoke tests",
        "Deployment diagram: build, deploy to green env, test, switch LB traffic, monitor, done",
        "Show blue/green deployment with rollback on both smoke test failure and instability",
        "Diagram the blue/green deployment lifecycle from build to blue retirement",
        "Create a deployment flow showing traffic migration between environments",
        "Blue-green: deploy to inactive env, run tests, healthy → switch traffic, else rollback",
        "Show a zero-downtime deployment flow with monitoring and stability check",
        "Deployment flowchart: new image → green env → smoke tests → traffic switch → monitor",
        "Build a blue/green deployment diagram with two rollback paths",
        "Diagram a deployment strategy that keeps old blue env as rollback option",
        "Show the complete blue/green deployment process from start to environment retirement",
        "Blue/green deployment flow: test gate before traffic switch and stability gate after",
        "Create a flowchart for a production deployment using blue/green technique",
        "Deployment flow with retire-blue step after confirming new environment is stable",
        "Draw a blue/green deployment diagram with smoke test and post-switch monitoring",
    ]
})

# ── F20  User Onboarding ────────────────────────────────────────────────────────
SCENARIOS.append({
    "diagram": D("d_f20", "User Onboarding Flow",
        nodes=[
            N("n_reg",    "pill",          40, 160, 160,  60, "Register",        "#ECFDF5","#34D399", tc="#064E3B", fw="700"),
            N("n_verify", "rect",         260, 160, 160,  80, "Verify Email",    "#EEF2FF","#818CF8", tc="#1E1B4B"),
            N("n_welcome","roundedRect",  480, 160, 160,  80, "Welcome Screen",  "#EEF2FF","#818CF8", tc="#1E1B4B"),
            N("n_profile","parallelogram",700, 160, 160,  80, "Set Up Profile",  "#F0F9FF","#38BDF8", tc="#0C4A6E"),
            N("n_integ",  "rect",         920, 160, 160,  80, "Connect Apps",    "#EEF2FF","#818CF8", tc="#1E1B4B"),
            N("n_email",  "rect",        1140, 160, 160,  80, "Welcome Email",   "#EEF2FF","#818CF8", tc="#1E1B4B"),
            N("n_done",   "pill",        1360, 160, 160,  60, "Onboarding Done", "#ECFDF5","#34D399", tc="#064E3B", fw="700"),
        ],
        edges=[
            E("e01","n_reg",    "n_verify", "right","left"),
            E("e02","n_verify", "n_welcome","right","left"),
            E("e03","n_welcome","n_profile","right","left"),
            E("e04","n_profile","n_integ",  "right","left"),
            E("e05","n_integ",  "n_email",  "right","left"),
            E("e06","n_email",  "n_done",   "right","left"),
        ], vx=20, vy=100, vz=0.85),
    "prompts": [
        "Create a user onboarding flowchart",
        "Draw a new user onboarding flow",
        "User onboarding process diagram",
        "Show the steps to onboard a new user",
        "Build a horizontal onboarding flow: register, verify, welcome, profile, apps, email, done",
        "Onboarding flow for a SaaS application",
        "Diagram the user onboarding journey",
        "Show new user setup steps from registration to onboarding completion",
        "Onboarding: register → verify email → welcome screen → profile → connect apps → welcome email",
        "Create a left-to-right onboarding flow",
        "User setup flow: registration, email verification, profile configuration, app integrations",
        "Show the 7-step user onboarding process",
        "Horizontal onboarding diagram from first registration to complete setup",
        "Build a flowchart for user activation and onboarding",
        "Onboarding flow: sign up, verify email, see welcome screen, fill profile, done",
        "Show how a new SaaS user gets set up from signup to active user",
        "User onboarding diagram with email verification and profile setup steps",
        "Create a left-to-right user activation flow",
        "Onboarding pipeline: register → verify → welcome → profile → integrations → email → done",
        "Draw a horizontal diagram for new user onboarding",
        "Show the onboarding steps for a B2B SaaS product",
        "User activation flow from registration to completing onboarding",
        "Create an onboarding flowchart with 7 steps in a horizontal layout",
        "Diagram the first-run user experience from register to onboarding complete",
        "Show user onboarding: signup, email confirm, welcome, profile, connect apps, finish",
    ]
})
