"""GCP architecture scenarios — 16 scenarios × 25 prompts = 400 examples."""
from .helpers import N, E, D

def GC(nid, shape, x, y, label, accent, **kw):
    return N(nid, shape, x, y, 90, 90, label, "#FFFFFF", "#E5E7EB",
             sw=1, tc="#111827", fs=11, fw="600", cloud=True, accent=accent, **kw)

COMPUTE  = "#4285F4"
STORAGE  = "#AECBFA"
DATABASE = "#5BB974"
FIREST   = "#FFA826"
ANALYTICS= "#AECBFA"
NETWORK  = "#4285F4"
PUBSUB   = "#EA4335"
AI       = "#FF6D00"
DEV      = "#FFA826"
MON      = "#34A853"
BUILD    = "#4285F4"

def zone(nid, x, y, w, h, fill, stroke, zi=0, op=0.5):
    return N(nid, "rect", x, y, w, h, "", fill, stroke, sw=1, zi=zi, op=op)

def zlabel(nid, x, y, text, tc):
    return N(nid, "textbox", x, y, 280, 20, text, "transparent", "transparent",
             sw=0, tc=tc, fs=10, fw="700", zi=1)

SCENARIOS = []

# ── G01  Simple Cloud Run Webapp ────────────────────────────────────────────────
SCENARIOS.append({
    "diagram": D("d_g01", "Cloud Run Webapp",
        nodes=[
            N("n_users","pill",      20, 95,120, 50,"Users","#DBEAFE","#4285F4",tc="#1E3A8A",fw="700",zi=1),
            GC("n_lb",   "gcp-loadbalancer",200,80,"Load Balancer",NETWORK,zi=1),
            GC("n_cr",   "gcp-cloudrun",    380,80,"Cloud Run",    COMPUTE,zi=1),
            GC("n_sql",  "gcp-cloudsql",    560,80,"Cloud SQL",    DATABASE,zi=1),
        ],
        edges=[
            E("e01","n_users","n_lb", "right","left",anim=True,color=NETWORK),
            E("e02","n_lb",   "n_cr", "right","left",color=COMPUTE,anim=True),
            E("e03","n_cr",   "n_sql","right","left",color=DATABASE),
        ], vx=10, vy=80),
    "prompts": [
        "Create a simple GCP Cloud Run web application diagram",
        "Draw a basic GCP architecture: load balancer, Cloud Run, Cloud SQL",
        "GCP: users → load balancer → Cloud Run → Cloud SQL",
        "Simple GCP webapp with Cloud Run and Cloud SQL",
        "Show a Cloud Run application on GCP",
        "GCP architecture: Cloud Load Balancing, Cloud Run, Cloud SQL",
        "Diagram a serverless GCP web app",
        "Simple GCP: HTTP load balancer routes to Cloud Run, which uses Cloud SQL",
        "Create a GCP diagram for a containerized serverless web app",
        "GCP Cloud Run diagram with managed database",
        "Show a GCP webapp: load balancer → Cloud Run container → Cloud SQL PostgreSQL",
        "Minimal GCP architecture with Cloud Run and Cloud SQL",
        "GCP serverless webapp: users hit load balancer, Cloud Run handles requests, Cloud SQL stores data",
        "Draw a 4-node GCP architecture with Cloud Run",
        "GCP diagram: Cloud Load Balancer, Cloud Run, Cloud SQL",
        "Simple GCP Cloud Run deployment backed by Cloud SQL",
        "Show the simplest GCP serverless web app architecture",
        "GCP: users → HTTPS load balancer → Cloud Run service → managed PostgreSQL",
        "Create a GCP Cloud Run web application architecture diagram",
        "GCP serverless: load balancer → Cloud Run → Cloud SQL",
        "Show a GCP architecture for a simple web application",
        "Cloud Run app on GCP with Cloud SQL database",
        "GCP: containerized app on Cloud Run with Cloud SQL backend",
        "Draw a GCP architecture with Cloud Load Balancing, Cloud Run, Cloud SQL",
        "Simple GCP web app diagram using managed serverless services",
    ]
})

# ── G02  Cloud Run + Cloud SQL + Cloud Storage ───────────────────────────────────
SCENARIOS.append({
    "diagram": D("d_g02", "Cloud Run Full Stack",
        nodes=[
            N("n_users","pill",      20,175,120, 50,"Users","#DBEAFE","#4285F4",tc="#1E3A8A",fw="700",zi=1),
            GC("n_lb",  "gcp-loadbalancer",200,160,"Load Balancer",NETWORK,zi=1),
            GC("n_cdn", "gcp-cdn",          380, 60,"Cloud CDN",    NETWORK,zi=1),
            GC("n_cr",  "gcp-cloudrun",     380,260,"Cloud Run",    COMPUTE,zi=1),
            GC("n_gcs", "gcp-storage",       560, 60,"Cloud Storage",STORAGE,zi=1),
            GC("n_sql", "gcp-cloudsql",      560,260,"Cloud SQL",   DATABASE,zi=1),
            GC("n_mon", "gcp-monitoring",    740,160,"Cloud Monitor",MON,    zi=1),
        ],
        edges=[
            E("e01","n_users","n_lb", "right","left",anim=True,color=NETWORK),
            E("e02","n_lb",   "n_cdn","right","left",label="static",color=NETWORK,es="dashed"),
            E("e03","n_lb",   "n_cr", "right","left",label="API",   color=COMPUTE,anim=True),
            E("e04","n_cdn",  "n_gcs","right","left",color=STORAGE),
            E("e05","n_cr",   "n_sql","right","left",color=DATABASE),
            E("e06","n_cr",   "n_mon","right","left",label="metrics",color="#D1D5DB",es="dotted"),
        ], vx=10, vy=50, vz=0.9),
    "prompts": [
        "Create a GCP Cloud Run full-stack architecture diagram",
        "Draw a GCP webapp with CDN, Cloud Run, Cloud Storage, and Cloud SQL",
        "GCP: load balancer routes to CDN for static assets and Cloud Run for API",
        "Show a GCP full-stack with Cloud CDN, Cloud Run, Storage, and SQL",
        "GCP diagram: CDN for static files, Cloud Run for backend, Cloud SQL for database",
        "Cloud Run app with GCP CDN and Cloud Storage for assets",
        "Show a GCP architecture with static file delivery and API backend",
        "GCP full-stack: load balancer, CDN, Cloud Run, Cloud Storage, Cloud SQL, monitoring",
        "Create a GCP diagram with CDN serving static files and Cloud Run handling API",
        "GCP web app with CDN for performance and Cloud Run for compute",
        "GCP: LB → CDN (static) + Cloud Run (API) → Cloud Storage + Cloud SQL",
        "Draw a GCP full-stack with separate static and dynamic tiers",
        "Cloud Run full stack on GCP with CDN, database, storage, and monitoring",
        "Show a GCP architecture for a web application with static and dynamic content",
        "GCP web app: load balancer, CDN, Cloud Run, Cloud SQL, Cloud Storage, monitoring",
        "Create a GCP diagram with Cloud CDN offloading static assets",
        "GCP full-stack architecture with Cloud Monitoring",
        "Show how GCP serves static and dynamic content through a load balancer",
        "GCP: HTTP LB → CDN → GCS for static, Cloud Run → Cloud SQL for dynamic",
        "GCP web application diagram with CDN, serverless backend, and managed database",
        "Cloud Run webapp on GCP with CDN, storage, SQL, and monitoring",
        "Draw a GCP architecture with four supporting services for a web app",
        "GCP full-stack: users → LB → CDN/Cloud Run → Storage/SQL → monitoring",
        "Show a complete GCP web application architecture with monitoring",
        "GCP diagram for a web app with CDN, serverless compute, and managed databases",
    ]
})

# ── G03  GKE Microservices ────────────────────────────────────────────────────────
SCENARIOS.append({
    "diagram": D("d_g03", "GKE Microservices",
        nodes=[
            N("n_users","pill",      20,265,120, 50,"Users","#DBEAFE","#4285F4",tc="#1E3A8A",fw="700",zi=1),
            GC("n_lb",  "gcp-loadbalancer",200,250,"Load Balancer",NETWORK,zi=1),
            GC("n_gke", "gcp-gke",          380,250,"GKE Cluster",  COMPUTE,zi=1),
            GC("n_svc1","gcp-cloudrun",     560, 80,"User Service",  COMPUTE,zi=1),
            GC("n_svc2","gcp-cloudrun",     560,250,"Order Service", COMPUTE,zi=1),
            GC("n_svc3","gcp-cloudrun",     560,420,"Product Service",COMPUTE,zi=1),
            GC("n_sql", "gcp-cloudsql",     740, 80,"Cloud SQL",    DATABASE,zi=1),
            GC("n_fst", "gcp-firestore",    740,250,"Firestore",    FIREST,  zi=1),
            GC("n_spn", "gcp-spanner",      740,420,"Cloud Spanner",DATABASE,zi=1),
            GC("n_pub", "gcp-pubsub",       920,250,"Pub/Sub",      PUBSUB,  zi=1),
            GC("n_mon", "gcp-monitoring",   920, 80,"Cloud Monitor",MON,    zi=1),
        ],
        edges=[
            E("e01","n_users","n_lb",  "right","left"),
            E("e02","n_lb",   "n_gke", "right","left",color=COMPUTE,anim=True),
            E("e03","n_gke",  "n_svc1","right","left",color=COMPUTE),
            E("e04","n_gke",  "n_svc2","right","left",color=COMPUTE),
            E("e05","n_gke",  "n_svc3","right","left",color=COMPUTE),
            E("e06","n_svc1", "n_sql", "right","left",color=DATABASE),
            E("e07","n_svc2", "n_fst", "right","left",color=FIREST),
            E("e08","n_svc3", "n_spn", "right","left",color=DATABASE),
            E("e09","n_svc2", "n_pub", "right","left",label="events",color=PUBSUB,anim=True),
            E("e10","n_svc1", "n_mon", "right","left",label="metrics",color="#D1D5DB",es="dotted"),
        ], vx=10, vy=30, vz=0.75),
    "prompts": [
        "Create a GKE microservices architecture diagram on GCP",
        "Draw a GCP GKE-based microservices diagram",
        "GCP GKE: load balancer → GKE cluster → three microservices with separate databases",
        "Show a microservices architecture running on GKE",
        "GCP microservices: GKE cluster, user/order/product services, Cloud SQL/Firestore/Spanner",
        "GKE microservices with database-per-service pattern on GCP",
        "Diagram GCP GKE deployment with three services and Pub/Sub",
        "GCP: GKE manages three services each with their own database",
        "Show GKE microservices on GCP with Pub/Sub event bus",
        "GCP microservices: GKE cluster routes to services, each has a dedicated database",
        "Create a GCP GKE microservices diagram with Cloud SQL, Firestore, and Spanner",
        "Show GKE cluster routing to user service (Cloud SQL), order service (Firestore), product service (Spanner)",
        "GCP: load balancer → GKE → microservices → databases, order service publishes to Pub/Sub",
        "GKE-based microservices on GCP with three separate data stores",
        "Draw a GCP diagram with GKE and three microservices",
        "GCP microservices with GKE, Pub/Sub, and Cloud Monitoring",
        "Kubernetes microservices on GCP with different databases per service",
        "Show a GCP GKE deployment with database isolation",
        "GCP: three GKE services, Cloud SQL for users, Firestore for orders, Spanner for products",
        "GKE microservices diagram with event-driven communication via Pub/Sub",
        "Create a GCP diagram showing GKE orchestrating three microservices",
        "GKE microservices on GCP with observability via Cloud Monitoring",
        "Show a GCP architecture where GKE runs multiple services with isolated databases",
        "GCP GKE microservices: load balancer, cluster, services, databases, event bus",
        "Draw a GCP microservices architecture with GKE and Pub/Sub",
    ]
})

# ── G04  BigQuery Data Pipeline ───────────────────────────────────────────────────
SCENARIOS.append({
    "diagram": D("d_g04", "GCP BigQuery Data Pipeline",
        nodes=[
            GC("n_src1","gcp-cloudsql",  40,175,"Cloud SQL",   DATABASE,zi=1),
            GC("n_src2","gcp-firestore", 40,335,"Firestore",   FIREST,  zi=1),
            GC("n_pub", "gcp-pubsub",   220,255,"Pub/Sub",     PUBSUB,  zi=1),
            GC("n_fun", "gcp-functions",400,255,"Cloud Functions",COMPUTE,zi=1),
            GC("n_gcs", "gcp-storage",  580, 80,"Raw GCS",     STORAGE, zi=1),
            GC("n_bld", "gcp-cloudbuild",580,255,"Cloud Build", BUILD,  zi=1),
            GC("n_bq",  "gcp-bigquery", 760,255,"BigQuery",    ANALYTICS,zi=1),
            GC("n_vai", "gcp-vertexai", 940,255,"Vertex AI",   AI,      zi=1),
            GC("n_mon", "gcp-monitoring",940, 80,"Cloud Monitor",MON,   zi=1),
        ],
        edges=[
            E("e01","n_src1","n_pub","right","left",color=PUBSUB),
            E("e02","n_src2","n_pub","right","left",color=PUBSUB),
            E("e03","n_pub", "n_fun","right","left",label="trigger",color=COMPUTE,anim=True),
            E("e04","n_fun", "n_gcs","right","left",label="store raw",color=STORAGE),
            E("e05","n_gcs", "n_bld","bottom","top",color=BUILD),
            E("e06","n_bld", "n_bq", "right","left",label="load",color=ANALYTICS),
            E("e07","n_bq",  "n_vai","right","left",label="train/query",color=AI,anim=True),
            E("e08","n_bq",  "n_mon","top","bottom",label="metrics",color="#D1D5DB",es="dotted"),
        ], vx=10, vy=50, vz=0.8),
    "prompts": [
        "Create a GCP BigQuery data pipeline architecture diagram",
        "Draw a GCP data analytics pipeline ending in BigQuery",
        "GCP: Cloud SQL + Firestore → Pub/Sub → Cloud Functions → GCS → BigQuery → Vertex AI",
        "Show a GCP analytics pipeline with BigQuery and Vertex AI",
        "GCP data pipeline: multiple sources, Pub/Sub, Functions, GCS, BigQuery, ML",
        "Diagram a GCP data analytics workflow with BigQuery",
        "GCP analytics: sources publish to Pub/Sub, Functions ingest to GCS, Cloud Build loads to BigQuery",
        "Show a GCP pipeline from transactional databases to BigQuery analytics",
        "Create a GCP BigQuery pipeline diagram",
        "GCP data engineering: Cloud SQL, Firestore → Pub/Sub → Functions → GCS → BigQuery",
        "GCP analytics with Vertex AI consuming from BigQuery",
        "Show a GCP data pipeline: sources → Pub/Sub → ingest → raw storage → BigQuery",
        "GCP: two data sources publish to Pub/Sub, Cloud Functions land in GCS, BigQuery for analytics",
        "Data pipeline on GCP ending in BigQuery and Vertex AI",
        "GCP analytics architecture: event-driven ingestion → GCS → BigQuery → ML with Vertex AI",
        "Create a GCP diagram for a machine learning data pipeline",
        "Show GCP data pipeline with Pub/Sub, Cloud Functions, GCS, and BigQuery",
        "GCP analytics: sources → Pub/Sub → Cloud Functions → GCS → BigQuery → Vertex AI",
        "Draw a GCP analytics platform with multiple data sources and BigQuery warehouse",
        "GCP data pipeline for analytics: ingest, store raw, load to BQ, train models",
        "GCP: Pub/Sub-driven pipeline from Cloud SQL to BigQuery with Vertex AI",
        "Show a GCP analytics pipeline with Cloud Monitoring",
        "GCP data platform: Cloud Functions for ETL, GCS for staging, BigQuery for analytics",
        "Diagram a GCP ML pipeline: data sources → Pub/Sub → ingest → BQ → Vertex AI",
        "Create a GCP analytics pipeline from transactional DBs to ML training",
    ]
})

# ── G05  Vertex AI ML Platform ────────────────────────────────────────────────────
SCENARIOS.append({
    "diagram": D("d_g05", "Vertex AI ML Platform",
        nodes=[
            GC("n_gcs",  "gcp-storage",  40,265,"Training Data GCS",STORAGE,zi=1),
            GC("n_bq",   "gcp-bigquery",220,265,"BigQuery",ANALYTICS,        zi=1),
            GC("n_vai",  "gcp-vertexai", 400,265,"Vertex AI Training",AI,     zi=1),
            GC("n_model","gcp-storage",  580,265,"Model Registry GCS",STORAGE,zi=1),
            GC("n_pred", "gcp-vertexai", 760,265,"Vertex AI Endpoint",AI,     zi=1),
            GC("n_cr",   "gcp-cloudrun", 940,265,"Prediction API",COMPUTE,    zi=1),
            GC("n_pub",  "gcp-pubsub",   580, 80,"Pub/Sub",     PUBSUB,       zi=1),
            GC("n_mon",  "gcp-monitoring",940, 80,"Cloud Monitor",MON,        zi=1),
            GC("n_cb",   "gcp-cloudbuild",400, 80,"Cloud Build",BUILD,        zi=1),
        ],
        edges=[
            E("e01","n_gcs", "n_vai","right","left",label="load data",color=AI),
            E("e02","n_bq",  "n_vai","right","left",color=AI),
            E("e03","n_cb",  "n_vai","bottom","top",label="trigger training",color=AI,anim=True),
            E("e04","n_vai", "n_model","right","left",label="save model",color=STORAGE),
            E("e05","n_model","n_pred","right","left",label="deploy",color=AI),
            E("e06","n_pred","n_cr",  "right","left",label="predict",color=COMPUTE,anim=True),
            E("e07","n_vai", "n_pub", "top","bottom",label="pipeline done",color=PUBSUB),
            E("e08","n_cr",  "n_mon", "top","bottom",label="metrics",color="#D1D5DB",es="dotted"),
        ], vx=10, vy=40, vz=0.8),
    "prompts": [
        "Create a Vertex AI ML platform architecture diagram on GCP",
        "Draw a GCP machine learning pipeline with Vertex AI",
        "GCP ML: GCS + BigQuery → Vertex AI Training → model registry → prediction endpoint",
        "Show a GCP ML platform with Vertex AI training and serving",
        "Vertex AI pipeline: training data, BigQuery, model training, model registry, prediction",
        "GCP ML architecture: data sources, Vertex AI training, deployment, serving API",
        "Diagram a GCP ML workflow with Vertex AI",
        "Show GCP Vertex AI model training and serving pipeline",
        "Create a GCP diagram for an ML platform with Vertex AI",
        "GCP: training data in GCS, train with Vertex AI, save to model registry, deploy endpoint",
        "Vertex AI ML platform: training pipeline, model registry, prediction endpoint, Cloud Run API",
        "Show a complete GCP ML architecture from data to prediction API",
        "GCP ML pipeline: GCS data, BigQuery features, Vertex AI training, model serving",
        "Vertex AI on GCP: Cloud Build triggers training, Vertex AI trains, deploys endpoint",
        "GCP ML platform with Cloud Build, Vertex AI, model registry, and prediction serving",
        "Create a GCP MLOps architecture diagram",
        "Show Vertex AI training and deployment pipeline on GCP",
        "GCP ML: GCS + BQ for data, Vertex AI for training and serving, Cloud Run for API",
        "Diagram a GCP ML pipeline with model registry and online serving",
        "Vertex AI architecture: train on data, save model, deploy to endpoint, serve predictions",
        "GCP ML platform with Pub/Sub notifications and Cloud Monitoring",
        "Show a GCP machine learning platform with Vertex AI training and prediction",
        "Create a GCP diagram for training and deploying ML models with Vertex AI",
        "GCP MLOps: Cloud Build triggers Vertex AI training, model deployed to prediction endpoint",
        "Vertex AI end-to-end: data ingestion, feature extraction, training, registry, serving",
    ]
})

# ── G06  Firebase App ─────────────────────────────────────────────────────────────
SCENARIOS.append({
    "diagram": D("d_g06", "Firebase App Architecture",
        nodes=[
            N("n_app",  "roundedRect", 20,175, 130, 70,"Mobile/Web App","#EFF6FF","#4285F4",tc="#1E3A8A",fw="700",zi=1),
            GC("n_fb",  "gcp-firebase",   200,160,"Firebase Auth", DEV,   zi=1),
            GC("n_fst", "gcp-firestore",  380,160,"Firestore",     FIREST,zi=1),
            GC("n_gcs", "gcp-storage",    560, 60,"Cloud Storage", STORAGE,zi=1),
            GC("n_fun", "gcp-functions",  560,260,"Cloud Functions",COMPUTE,zi=1),
            GC("n_pub", "gcp-pubsub",     740,260,"Pub/Sub",       PUBSUB,zi=1),
            GC("n_mon", "gcp-monitoring", 740, 60,"Monitoring",    MON,   zi=1),
        ],
        edges=[
            E("e01","n_app","n_fb",  "right","left",label="auth",color=DEV,anim=True),
            E("e02","n_app","n_fst", "right","left",label="realtime DB",color=FIREST,anim=True),
            E("e03","n_app","n_gcs", "right","top",label="uploads",color=STORAGE,es="dashed"),
            E("e04","n_fst","n_fun", "right","left",label="triggers",color=COMPUTE),
            E("e05","n_fun","n_pub", "right","left",color=PUBSUB,anim=True),
            E("e06","n_fun","n_mon", "top","bottom",label="logs",color="#D1D5DB",es="dotted"),
        ], vx=10, vy=50, vz=0.9),
    "prompts": [
        "Create a Firebase app architecture diagram on GCP",
        "Draw a Firebase-powered mobile/web app architecture",
        "GCP Firebase: app → Firebase Auth + Firestore + Cloud Storage",
        "Show a Firebase app with authentication, Firestore database, and Cloud Storage",
        "Firebase architecture: auth, realtime DB, file storage, Cloud Functions, Pub/Sub",
        "Diagram a mobile app using Firebase services on GCP",
        "Firebase app: auth, Firestore, storage, triggered Cloud Functions",
        "Show a GCP Firebase architecture for a mobile application",
        "Create a GCP diagram for a Firebase-powered app",
        "Firebase: authentication, Firestore realtime database, Storage for files, Functions for logic",
        "GCP: mobile app uses Firebase Auth, Firestore, Cloud Storage, with Functions triggered by DB",
        "Draw a Firebase app architecture with Pub/Sub",
        "Firebase mobile app: Auth → login, Firestore → data, Storage → media, Functions → events",
        "Show a GCP Firebase architecture with Cloud Functions triggered by Firestore",
        "Firebase GCP diagram: app auth, document store, file storage, serverless functions",
        "Create a Firebase app diagram with monitoring",
        "GCP Firebase: app uses auth service, Firestore triggers Functions which publish to Pub/Sub",
        "Diagram a real-time app using Firebase Firestore and Cloud Functions",
        "Firebase architecture: mobile/web app with auth, Firestore DB, GCS uploads, Functions",
        "Show a Firebase-based GCP architecture with event-driven Functions",
        "GCP: Firebase Auth for identity, Firestore for data, Storage for files, Functions for logic",
        "Firebase app on GCP with Cloud Monitoring observability",
        "Draw a Firebase architecture for a real-time collaboration app",
        "GCP Firebase diagram: auth, Firestore, storage, serverless logic, event bus",
        "Create a GCP diagram for a Firebase-powered real-time application",
    ]
})

# ── G07  Cloud Functions + Pub/Sub Event-Driven ───────────────────────────────────
SCENARIOS.append({
    "diagram": D("d_g07", "Cloud Functions Event-Driven",
        nodes=[
            GC("n_src",  "gcp-cloudrun",   40,175,"Source Service",COMPUTE,zi=1),
            GC("n_pub",  "gcp-pubsub",     220,175,"Pub/Sub Topic", PUBSUB,zi=1),
            GC("n_fun1", "gcp-functions",  400, 60,"Function A",   COMPUTE,zi=1),
            GC("n_fun2", "gcp-functions",  400,175,"Function B",   COMPUTE,zi=1),
            GC("n_fun3", "gcp-functions",  400,290,"Function C",   COMPUTE,zi=1),
            GC("n_fst",  "gcp-firestore",  580, 60,"Firestore",    FIREST, zi=1),
            GC("n_bq",   "gcp-bigquery",   580,175,"BigQuery",     ANALYTICS,zi=1),
            GC("n_gcs",  "gcp-storage",    580,290,"Cloud Storage",STORAGE,zi=1),
            GC("n_mon",  "gcp-monitoring", 760,175,"Cloud Monitor",MON,   zi=1),
        ],
        edges=[
            E("e01","n_src", "n_pub", "right","left",label="publish",color=PUBSUB,anim=True),
            E("e02","n_pub", "n_fun1","right","left",color=COMPUTE,anim=True),
            E("e03","n_pub", "n_fun2","right","left",color=COMPUTE,anim=True),
            E("e04","n_pub", "n_fun3","right","left",color=COMPUTE,anim=True),
            E("e05","n_fun1","n_fst", "right","left",color=FIREST),
            E("e06","n_fun2","n_bq",  "right","left",color=ANALYTICS),
            E("e07","n_fun3","n_gcs", "right","left",color=STORAGE),
            E("e08","n_fun2","n_mon", "right","left",label="metrics",color="#D1D5DB",es="dotted"),
        ], vx=10, vy=40, vz=0.85),
    "prompts": [
        "Create a GCP event-driven Cloud Functions architecture",
        "Draw a GCP Pub/Sub fan-out with Cloud Functions",
        "GCP: Pub/Sub fans out to three Cloud Functions",
        "Show a GCP event-driven architecture with Pub/Sub and Functions",
        "Pub/Sub → three Cloud Functions → Firestore, BigQuery, Cloud Storage",
        "GCP fan-out: one Pub/Sub topic triggers three Cloud Functions",
        "Diagram GCP Cloud Functions triggered by Pub/Sub",
        "Show GCP serverless event-driven architecture with three consumers",
        "GCP: source service publishes to Pub/Sub, three Cloud Functions process independently",
        "Create a GCP Pub/Sub fan-out diagram",
        "GCP event-driven: Pub/Sub fan-out to Functions, each writes to different sink",
        "Show a GCP architecture with Pub/Sub driving multiple Cloud Functions",
        "GCP: Pub/Sub topic subscribed by Function A (Firestore), B (BigQuery), C (GCS)",
        "Cloud Functions triggered by Pub/Sub on GCP",
        "GCP serverless: source publishes event, three functions each process it differently",
        "Create a GCP diagram showing event-driven fan-out with Cloud Functions",
        "Show Pub/Sub driving three parallel Cloud Functions on GCP",
        "GCP event architecture: publish once, process in parallel with Cloud Functions",
        "Pub/Sub to Cloud Functions: write to Firestore, BigQuery, and Cloud Storage",
        "GCP: event fan-out from Pub/Sub to three serverless function consumers",
        "Draw a GCP serverless event-driven diagram with monitoring",
        "GCP event-driven: source service, Pub/Sub topic, three Cloud Functions, three sinks",
        "Show a GCP architecture where one Pub/Sub message triggers three independent functions",
        "Cloud Functions fan-out on GCP with Firestore, BigQuery, and GCS as sinks",
        "GCP diagram: Pub/Sub fan-out drives Cloud Functions to three different data stores",
    ]
})

# ── G08  GCP Data Lake ───────────────────────────────────────────────────────────
SCENARIOS.append({
    "diagram": D("d_g08", "GCP Data Lake",
        nodes=[
            GC("n_src1","gcp-cloudsql",  40,260,"Cloud SQL",   DATABASE,zi=1),
            GC("n_src2","gcp-firestore", 40,420,"Firestore",   FIREST,  zi=1),
            GC("n_pub", "gcp-pubsub",   220,340,"Pub/Sub",     PUBSUB,  zi=1),
            GC("n_fun", "gcp-functions",400,340,"Ingest Fn",   COMPUTE, zi=1),
            GC("n_raw", "gcp-storage",  580, 80,"Raw Zone GCS",STORAGE, zi=1),
            GC("n_pro", "gcp-storage",  580,260,"Processed GCS",STORAGE,zi=1),
            GC("n_cur", "gcp-storage",  580,440,"Curated GCS", STORAGE, zi=1),
            GC("n_bq",  "gcp-bigquery", 760,260,"BigQuery DW", ANALYTICS,zi=1),
            GC("n_vai", "gcp-vertexai", 940,260,"Vertex AI",   AI,      zi=1),
        ],
        edges=[
            E("e01","n_src1","n_pub","right","left",color=PUBSUB),
            E("e02","n_src2","n_pub","right","left",color=PUBSUB),
            E("e03","n_pub", "n_fun","right","left",label="trigger",color=COMPUTE,anim=True),
            E("e04","n_fun", "n_raw","right","left",label="land raw",color=STORAGE),
            E("e05","n_raw", "n_pro","bottom","top",label="process",color=STORAGE,es="dashed"),
            E("e06","n_pro", "n_cur","bottom","top",label="curate",color=STORAGE,es="dashed"),
            E("e07","n_pro", "n_bq", "right","left",label="load",color=ANALYTICS),
            E("e08","n_bq",  "n_vai","right","left",label="train",color=AI,anim=True),
        ], vx=10, vy=30, vz=0.8),
    "prompts": [
        "Create a GCP data lake architecture diagram",
        "Draw a GCP data lake with Cloud Storage zones and BigQuery",
        "GCP data lake: Cloud SQL + Firestore → Pub/Sub → Functions → GCS zones → BigQuery",
        "Show a GCP data lake with raw, processed, and curated tiers",
        "GCP: multiple sources, Pub/Sub ingestion, Cloud Functions, tiered GCS, BigQuery, Vertex AI",
        "Diagram a GCP data lake architecture",
        "GCP data lake with three Cloud Storage zones and BigQuery warehouse",
        "Show a GCP analytics data lake with Vertex AI",
        "Create a GCP data lake diagram with Pub/Sub-driven ingestion",
        "GCP data lake: Cloud SQL → Pub/Sub → ingest function → GCS raw → processed → BigQuery",
        "GCP: data flows from databases through Pub/Sub to GCS data lake zones to BigQuery",
        "Show a three-tier GCS data lake on GCP ending in BigQuery",
        "GCP data lake with Pub/Sub-driven Cloud Functions and tiered storage",
        "Data lake on GCP: ingest, raw zone, processed zone, curated zone, warehouse",
        "GCP: two data sources, Pub/Sub broker, Cloud Function ingestor, GCS zones, BQ, Vertex AI",
        "Create a GCP data engineering architecture with data lake",
        "Show a GCP data lake architecture with ML pipeline via Vertex AI",
        "GCP: raw data → GCS → process → curated → load to BigQuery → train with Vertex AI",
        "Draw a GCP data lake from source databases to ML training",
        "GCP data lake with Pub/Sub-triggered ingestion and three GCS storage tiers",
        "Show a GCP analytics platform with data lake and machine learning",
        "GCP data lake: multiple sources, Pub/Sub, Cloud Functions, GCS tiers, BigQuery, Vertex AI",
        "Create a GCP diagram for a data engineering platform with data lake",
        "GCP data pipeline from transactional databases to BigQuery data warehouse",
        "Diagram a GCP data lake with tiered storage and ML integration",
    ]
})

# ── G09  Cloud Build CI/CD ─────────────────────────────────────────────────────────
SCENARIOS.append({
    "diagram": D("d_g09", "GCP Cloud Build CI/CD",
        nodes=[
            N("n_git",  "roundedRect", 20,175, 130, 70,"GitHub Repo","#F3F4F6","#9CA3AF",tc="#374151",fw="700",zi=1),
            GC("n_cb",  "gcp-cloudbuild",  200,160,"Cloud Build",  BUILD,  zi=1),
            GC("n_gcr", "gcp-storage",     380, 60,"Container Reg",STORAGE,zi=1),
            GC("n_gcs", "gcp-storage",     380,260,"Artifacts GCS",STORAGE,zi=1),
            GC("n_stg", "gcp-cloudrun",    560, 60,"Cloud Run Stg",COMPUTE,zi=1),
            GC("n_prd", "gcp-cloudrun",    560,260,"Cloud Run Prod",COMPUTE,zi=1),
            GC("n_pub", "gcp-pubsub",      740,160,"Pub/Sub",      PUBSUB, zi=1),
            GC("n_mon", "gcp-monitoring",  920,160,"Cloud Monitor",MON,    zi=1),
        ],
        edges=[
            E("e01","n_git","n_cb",  "right","left",label="push",color=BUILD,anim=True),
            E("e02","n_cb", "n_gcr", "right","left",label="push image",color=STORAGE),
            E("e03","n_cb", "n_gcs", "right","left",label="artifacts",color=STORAGE,es="dashed"),
            E("e04","n_gcr","n_stg", "right","left",label="deploy",color=COMPUTE),
            E("e05","n_gcr","n_prd", "right","left",label="deploy",color=COMPUTE),
            E("e06","n_cb", "n_pub", "right","left",label="notify",color=PUBSUB),
            E("e07","n_cb", "n_mon", "right","left",label="logs",color="#D1D5DB",es="dotted"),
        ], vx=10, vy=50, vz=0.85),
    "prompts": [
        "Create a GCP Cloud Build CI/CD pipeline diagram",
        "Draw a GCP CI/CD pipeline with Cloud Build",
        "GCP CI/CD: GitHub → Cloud Build → Container Registry → Cloud Run staging + prod",
        "Show a GCP deployment pipeline with Cloud Build",
        "GCP CI/CD: code push → Cloud Build → push image → deploy to Cloud Run",
        "Cloud Build pipeline: GitHub push, build image, push to registry, deploy",
        "Diagram a GCP Cloud Build CI/CD workflow",
        "Show GCP Cloud Build deploying to staging and production Cloud Run services",
        "GCP: GitHub push triggers Cloud Build, image pushed to GCR, deployed to Cloud Run",
        "Create a GCP CI/CD diagram with Cloud Build and Cloud Run",
        "GCP CI/CD pipeline: Cloud Build builds Docker image, deploys to Cloud Run environments",
        "Show GCP deployment pipeline with Pub/Sub notifications on completion",
        "GCP Cloud Build: push code, build image, push to registry, deploy to staging + prod",
        "GCP CI/CD with Cloud Build, Container Registry, and Cloud Run",
        "Draw a GCP CI/CD pipeline that deploys to two Cloud Run environments",
        "Cloud Build CI/CD on GCP with Cloud Monitoring",
        "GCP: GitHub, Cloud Build, GCR, Cloud Run staging, Cloud Run production",
        "Create a GCP CI/CD architecture with Pub/Sub build notifications",
        "Show a GCP deployment pipeline from commit to production",
        "GCP Cloud Build → push container → deploy to staging and production Cloud Run",
        "GCP CI/CD: build artifacts and container image, deploy to two environments",
        "Draw a GCP pipeline with Cloud Build and two Cloud Run deployment targets",
        "GCP deployment automation: Cloud Build CI/CD with Cloud Monitoring",
        "Show GCP Cloud Build deploying containerized apps to Cloud Run",
        "GCP CI/CD pipeline from GitHub to production Cloud Run service",
    ]
})

# ── G10  GCP Pub/Sub Event-Driven Microservices ───────────────────────────────────
SCENARIOS.append({
    "diagram": D("d_g10", "GCP Event-Driven Microservices",
        nodes=[
            N("n_users","pill",      20,265,120, 50,"Users","#DBEAFE","#4285F4",tc="#1E3A8A",fw="700",zi=1),
            GC("n_lb",  "gcp-loadbalancer",200,250,"Load Balancer",NETWORK,zi=1),
            GC("n_api", "gcp-cloudrun",    380,250,"API Service",  COMPUTE,zi=1),
            GC("n_pub", "gcp-pubsub",      560,250,"Pub/Sub",      PUBSUB, zi=1),
            GC("n_w1",  "gcp-functions",   740, 80,"Worker A",     COMPUTE,zi=1),
            GC("n_w2",  "gcp-functions",   740,250,"Worker B",     COMPUTE,zi=1),
            GC("n_w3",  "gcp-functions",   740,420,"Worker C",     COMPUTE,zi=1),
            GC("n_sql", "gcp-cloudsql",    920, 80,"Cloud SQL",    DATABASE,zi=1),
            GC("n_bq",  "gcp-bigquery",    920,250,"BigQuery",     ANALYTICS,zi=1),
            GC("n_gcs", "gcp-storage",     920,420,"Cloud Storage",STORAGE, zi=1),
        ],
        edges=[
            E("e01","n_users","n_lb", "right","left"),
            E("e02","n_lb",   "n_api","right","left",anim=True,color=NETWORK),
            E("e03","n_api",  "n_pub","right","left",label="publish",color=PUBSUB,anim=True),
            E("e04","n_pub",  "n_w1", "right","left",color=COMPUTE,anim=True),
            E("e05","n_pub",  "n_w2", "right","left",color=COMPUTE,anim=True),
            E("e06","n_pub",  "n_w3", "right","left",color=COMPUTE,anim=True),
            E("e07","n_w1",   "n_sql","right","left",color=DATABASE),
            E("e08","n_w2",   "n_bq", "right","left",color=ANALYTICS),
            E("e09","n_w3",   "n_gcs","right","left",color=STORAGE),
        ], vx=10, vy=30, vz=0.75),
    "prompts": [
        "Create a GCP event-driven microservices architecture",
        "Draw a GCP Pub/Sub-driven microservices diagram",
        "GCP: API service publishes to Pub/Sub, three Cloud Functions process events",
        "Show a GCP event-driven architecture with Pub/Sub and Cloud Functions",
        "GCP microservices with Pub/Sub: API → Pub/Sub → three workers → three data stores",
        "Diagram a GCP event-driven architecture with three consumers",
        "Show GCP Pub/Sub driving three independent worker functions",
        "GCP: users → LB → API service → Pub/Sub → three Cloud Functions → SQL/BQ/GCS",
        "Create a GCP Pub/Sub event-driven microservices diagram",
        "GCP event-driven: API publishes events, three functions each write to different storage",
        "Show a GCP architecture where Pub/Sub decouples the API from workers",
        "GCP microservices: load balancer, API, Pub/Sub, three function workers, three data stores",
        "GCP event-driven pattern: one publisher, one Pub/Sub topic, three subscribers",
        "Cloud Functions consume from Pub/Sub and write to Cloud SQL, BigQuery, and GCS",
        "GCP: API service emits to Pub/Sub, fan-out to function workers with different storage",
        "Create a GCP diagram showing event-driven decoupling with Pub/Sub",
        "Show a GCP architecture where Pub/Sub fans events to multiple Cloud Functions",
        "GCP Pub/Sub fan-out: API → Pub/Sub → Workers A/B/C → SQL/BigQuery/GCS",
        "GCP event-driven microservices with three independent worker services",
        "Show how GCP Pub/Sub enables asynchronous processing across multiple functions",
        "GCP: API tier publishes to Pub/Sub, async workers process and persist independently",
        "Draw GCP event-driven: load balancer, API, Pub/Sub, workers, and data sinks",
        "GCP microservices with Pub/Sub as the central event broker",
        "Show a GCP event bus architecture with Cloud Functions as consumers",
        "GCP diagram: users → API → Pub/Sub event bus → three Cloud Function consumers",
    ]
})

# ── G11  GCP Serverless with Firestore ────────────────────────────────────────────
SCENARIOS.append({
    "diagram": D("d_g11", "GCP Serverless API",
        nodes=[
            N("n_client","pill",    20, 95,120, 50,"Client","#DBEAFE","#4285F4",tc="#1E3A8A",fw="700",zi=1),
            GC("n_lb",  "gcp-loadbalancer",200,80,"Load Balancer",NETWORK,zi=1),
            GC("n_fun", "gcp-functions",   380,80,"Cloud Functions",COMPUTE,zi=1),
            GC("n_fst", "gcp-firestore",   560,80,"Firestore",    FIREST,  zi=1),
            GC("n_gcs", "gcp-storage",     740, 0,"Cloud Storage",STORAGE, zi=1),
            GC("n_pub", "gcp-pubsub",      740,160,"Pub/Sub",     PUBSUB,  zi=1),
            GC("n_mon", "gcp-monitoring",  920, 80,"Monitoring",  MON,     zi=1),
        ],
        edges=[
            E("e01","n_client","n_lb", "right","left",anim=True,color=NETWORK),
            E("e02","n_lb",    "n_fun","right","left",label="invoke",color=COMPUTE,anim=True),
            E("e03","n_fun",   "n_fst","right","left",color=FIREST),
            E("e04","n_fun",   "n_gcs","right","left",color=STORAGE,es="dashed"),
            E("e05","n_fun",   "n_pub","right","left",color=PUBSUB,anim=True),
            E("e06","n_fun",   "n_mon","right","left",label="logs",color="#D1D5DB",es="dotted"),
        ], vx=10, vy=60),
    "prompts": [
        "Create a GCP serverless API with Cloud Functions and Firestore",
        "Draw a GCP serverless backend using Cloud Functions",
        "GCP: client → load balancer → Cloud Functions → Firestore + GCS + Pub/Sub",
        "Show a GCP serverless API diagram",
        "Cloud Functions serverless API on GCP with Firestore database",
        "GCP serverless: load balancer → Cloud Functions → Firestore, Storage, Pub/Sub",
        "Diagram a GCP serverless API backed by Firestore",
        "Show a GCP Cloud Functions API with multiple backing services",
        "Create a GCP diagram for a serverless API with Cloud Functions",
        "GCP serverless: Cloud Functions handles requests, writes to Firestore, uploads to GCS",
        "GCP: load balancer routes to Cloud Functions, writes to Firestore and GCS",
        "Draw a serverless GCP API with Cloud Functions and Firestore",
        "GCP: HTTP API via Cloud Functions, Firestore for documents, GCS for files, Pub/Sub for events",
        "Cloud Functions API on GCP: LB → Functions → Firestore + Storage + events",
        "Show a GCP serverless architecture with Functions, Firestore, and Pub/Sub",
        "GCP serverless API with monitoring and event publishing",
        "Cloud Functions diagram on GCP: API calls, Firestore writes, file uploads, events",
        "Create a simple GCP serverless API using managed services",
        "Show a GCP serverless API: load balancer, Cloud Functions, Firestore, Storage",
        "GCP Functions API with Firestore backend and Pub/Sub event publishing",
        "Diagram a GCP Cloud Functions API with multiple data destinations",
        "GCP serverless: Cloud Functions API uses Firestore and GCS, publishes to Pub/Sub",
        "Show a GCP diagram for a serverless document API",
        "GCP Cloud Functions API: LB entry, Firestore DB, GCS storage, Pub/Sub events, monitoring",
        "Create a GCP serverless architecture with Cloud Functions as the API layer",
    ]
})

# ── G12  GCP Multi-region Setup ───────────────────────────────────────────────────
SCENARIOS.append({
    "diagram": D("d_g12", "GCP Multi-region",
        nodes=[
            N("n_users","pill",      20,265,120, 50,"Users","#DBEAFE","#4285F4",tc="#1E3A8A",fw="700",zi=1),
            GC("n_cdn", "gcp-cdn",       200,250,"Cloud CDN",    NETWORK, zi=1),
            GC("n_lb",  "gcp-loadbalancer",380,250,"Global LB",  NETWORK, zi=1),
            GC("n_us",  "gcp-cloudrun",   560, 80,"Cloud Run US",COMPUTE, zi=1),
            GC("n_eu",  "gcp-cloudrun",   560,420,"Cloud Run EU",COMPUTE, zi=1),
            GC("n_spn", "gcp-spanner",   740,250,"Cloud Spanner",DATABASE,zi=1),
            GC("n_gcs", "gcp-storage",   920,250,"Multi-Region GCS",STORAGE,zi=1),
            GC("n_mon", "gcp-monitoring",920, 80,"Monitoring",   MON,    zi=1),
        ],
        edges=[
            E("e01","n_users","n_cdn","right","left"),
            E("e02","n_cdn",  "n_lb", "right","left",color=NETWORK),
            E("e03","n_lb",   "n_us", "right","left",label="us-central1",color=COMPUTE,anim=True),
            E("e04","n_lb",   "n_eu", "right","left",label="europe-west1",color=COMPUTE,anim=True),
            E("e05","n_us",   "n_spn","right","left",color=DATABASE),
            E("e06","n_eu",   "n_spn","right","left",color=DATABASE),
            E("e07","n_spn",  "n_gcs","right","left",label="export",color=STORAGE,es="dashed"),
            E("e08","n_us",   "n_mon","right","left",label="metrics",color="#D1D5DB",es="dotted"),
        ], vx=10, vy=40, vz=0.85),
    "prompts": [
        "Create a GCP multi-region architecture diagram",
        "Draw a GCP global deployment across two regions",
        "GCP multi-region: Cloud CDN → global load balancer → Cloud Run US + EU → Cloud Spanner",
        "Show a GCP multi-region setup with Cloud Spanner for global consistency",
        "GCP global architecture with CDN, global load balancer, and two regional Cloud Run services",
        "GCP multi-region with Cloud Spanner as the globally distributed database",
        "Diagram a GCP global architecture for low latency worldwide",
        "GCP: global LB routes to US and EU Cloud Run instances, both use Cloud Spanner",
        "Show a GCP architecture designed for global users with multi-region deployment",
        "Create a GCP multi-region diagram with Cloud CDN and Cloud Spanner",
        "GCP global: CDN → global LB → Cloud Run in two regions → shared Spanner DB",
        "Show GCP multi-region with Cloud CDN for performance and Cloud Spanner for data",
        "GCP multi-region deployment: two Cloud Run services share one Cloud Spanner database",
        "Draw a global GCP architecture with Cloud CDN, global LB, regional Cloud Run",
        "GCP: Cloud CDN, global load balancer, US region, EU region, Cloud Spanner, GCS",
        "Create a GCP diagram for a globally distributed application",
        "Show a GCP architecture serving users in multiple regions",
        "GCP global: CDN + global LB routes to US and EU Cloud Run, Cloud Spanner for global DB",
        "Multi-region GCP with Cloud Spanner for strong consistency across regions",
        "GCP: Cloud CDN → load balancer → two regions → Cloud Spanner + GCS",
        "Show GCP multi-region deployment with globally consistent database",
        "Draw a GCP multi-region architecture with observability via Cloud Monitoring",
        "GCP multi-region: CDN, global LB, Cloud Run in two regions, shared Cloud Spanner",
        "Show how GCP handles global traffic routing to multiple regions",
        "GCP global deployment diagram with Cloud Spanner for multi-region consistency",
    ]
})

# ── G13  GCP Full Production Platform ─────────────────────────────────────────────
SCENARIOS.append({
    "diagram": D("d_g13", "GCP Full Production Platform",
        nodes=[
            zone("z_int","0",  40, 980, 120, "#EFF6FF","#BFDBFE"),
            zone("z_cmp","0", 180, 980, 140, "#EBF5FB","#93C6E7"),
            zone("z_asc","0", 340, 980, 140, "#FEF9E7","#F9E79F"),
            zone("z_dat","0", 500, 980, 140, "#E8F8F5","#A9DFBF"),
            zone("z_ops","0", 660, 320, 170, "#FDF2F8","#FBCFE8"),
            zlabel("l_int",8,  43,"INTERNET EDGE", "#93C5FD"),
            zlabel("l_cmp",8, 183,"COMPUTE",        "#60A5FA"),
            zlabel("l_asc",8, 343,"ASYNC LAYER",    "#FCD34D"),
            zlabel("l_dat",8, 503,"DATA",            "#6EE7B7"),
            zlabel("l_ops",8, 663,"OBSERVABILITY",  "#F9A8D4"),
            N("n_usr","pill",      20, 85,120, 50,"Users","#DBEAFE","#4285F4",tc="#1E3A8A",fw="700",zi=2),
            GC("n_cdn","gcp-cdn",          200, 70,"Cloud CDN",     NETWORK,zi=2),
            GC("n_lb", "gcp-loadbalancer", 380, 70,"Load Balancer", NETWORK,zi=2),
            GC("n_gcs_s","gcp-storage",    560, 70,"Static GCS",    STORAGE,zi=2),
            GC("n_cr", "gcp-cloudrun",     200,230,"Cloud Run",     COMPUTE,zi=2),
            GC("n_gke","gcp-gke",          380,230,"GKE",           COMPUTE,zi=2),
            GC("n_fun","gcp-functions",    560,230,"Cloud Functions",COMPUTE,zi=2),
            GC("n_pub","gcp-pubsub",       200,400,"Pub/Sub",       PUBSUB, zi=2),
            GC("n_bq2","gcp-bigquery",     380,400,"BigQuery",      ANALYTICS,zi=2),
            GC("n_gcs2","gcp-storage",     560,400,"GCS",           STORAGE,zi=2),
            GC("n_sql","gcp-cloudsql",     200,570,"Cloud SQL",     DATABASE,zi=2),
            GC("n_fst","gcp-firestore",    380,570,"Firestore",     FIREST,  zi=2),
            GC("n_spn","gcp-spanner",      560,570,"Cloud Spanner", DATABASE,zi=2),
            GC("n_vai","gcp-vertexai",     740,570,"Vertex AI",     AI,      zi=2),
            GC("n_cb", "gcp-cloudbuild",   740,230,"Cloud Build",   BUILD,   zi=2),
            GC("n_mon","gcp-monitoring",   740,400,"Cloud Monitor", MON,     zi=2),
        ],
        edges=[
            E("e01","n_usr","n_cdn","right","left"),
            E("e02","n_cdn","n_lb", "right","left",color=NETWORK),
            E("e03","n_lb", "n_gcs_s","right","left",label="static",color=STORAGE,es="dashed"),
            E("e04","n_lb", "n_cr", "bottom","top",label="API",    color=COMPUTE,anim=True),
            E("e05","n_lb", "n_gke","bottom","top",label="web",    color=COMPUTE,anim=True),
            E("e06","n_cr", "n_pub","bottom","top",label="events", color=PUBSUB),
            E("e07","n_gke","n_fun","right","left",color=COMPUTE),
            E("e08","n_pub","n_bq2","right","left",color=ANALYTICS,anim=True),
            E("e09","n_pub","n_gcs2","right","left",color=STORAGE),
            E("e10","n_cr", "n_sql","bottom","top",color=DATABASE),
            E("e11","n_gke","n_fst","bottom","top",color=FIREST),
            E("e12","n_fun","n_spn","bottom","top",color=DATABASE),
            E("e13","n_bq2","n_vai","right","left",label="train",  color=AI,anim=True),
            E("e14","n_cb", "n_gke","bottom","top",label="deploy", color=COMPUTE),
            E("e15","n_cr", "n_mon","right","left",label="metrics",color="#D1D5DB",es="dotted"),
        ], vx=10, vy=20, vz=0.65),
    "prompts": [
        "Create a comprehensive GCP production platform architecture diagram",
        "Draw a full GCP production architecture",
        "Full GCP platform: internet edge, compute, async, data, and observability zones",
        "GCP production: CDN, load balancer, Cloud Run, GKE, Functions, Pub/Sub, BigQuery, Firestore, Cloud SQL, Spanner, Vertex AI",
        "Show a complete GCP enterprise platform with multiple compute and data services",
        "Comprehensive GCP architecture diagram with 5 zone labels",
        "GCP full platform: CDN + LB routing to Cloud Run + GKE, Pub/Sub async, multiple databases",
        "Show a large GCP architecture with all major service categories",
        "GCP production: compute tier with Cloud Run + GKE + Functions, data tier with SQL + Firestore + Spanner",
        "Full GCP platform diagram with Cloud Build CI/CD and Cloud Monitoring observability",
        "Create a GCP enterprise architecture with compute, messaging, data, and ML layers",
        "GCP: CDN → LB → Cloud Run + GKE + Functions → Pub/Sub → BigQuery + Firestore + Cloud SQL + Spanner → Vertex AI",
        "Show a comprehensive GCP platform with Vertex AI for ML",
        "GCP full production: static site, serverless, Kubernetes, events, analytics, ML",
        "Draw a large-scale GCP architecture with zone backgrounds",
        "GCP enterprise platform with Cloud Build, Cloud Monitoring, and Vertex AI",
        "Full GCP architecture: three compute options, Pub/Sub events, three databases, analytics",
        "Create a comprehensive GCP diagram with all major services",
        "GCP production platform: CDN, load balancer, Cloud Run, GKE, Pub/Sub, databases, Vertex AI",
        "Show a full GCP architecture with observability and ML integration",
        "GCP diagram with Cloud Run, GKE, Cloud Functions, Pub/Sub, multiple databases, Vertex AI",
        "Comprehensive GCP: compute layer (CR+GKE+Functions), async (Pub/Sub), data (SQL+Firestore+Spanner), ML",
        "GCP full production platform with 5 architectural zones",
        "Show a complete GCP enterprise backend architecture",
        "Draw a comprehensive GCP platform diagram with Vertex AI and Cloud Monitoring",
    ]
})

# ── G14  GCP Streaming Analytics ──────────────────────────────────────────────────
SCENARIOS.append({
    "diagram": D("d_g14", "GCP Streaming Analytics",
        nodes=[
            GC("n_app", "gcp-firebase",   40,175,"Mobile App",  DEV,      zi=1),
            GC("n_pub", "gcp-pubsub",    220,175,"Pub/Sub",     PUBSUB,   zi=1),
            GC("n_fun", "gcp-functions", 400,175,"Stream Processor",COMPUTE,zi=1),
            GC("n_bq",  "gcp-bigquery",  580, 80,"BigQuery",    ANALYTICS,zi=1),
            GC("n_gcs", "gcp-storage",   580,290,"Raw GCS",     STORAGE,  zi=1),
            GC("n_vai", "gcp-vertexai",  760, 80,"Vertex AI",   AI,       zi=1),
            GC("n_mon", "gcp-monitoring",760,290,"Monitoring",  MON,      zi=1),
        ],
        edges=[
            E("e01","n_app","n_pub","right","left",label="events",color=PUBSUB,anim=True),
            E("e02","n_pub","n_fun","right","left",color=COMPUTE,anim=True),
            E("e03","n_fun","n_bq", "right","left",label="stream",color=ANALYTICS,anim=True),
            E("e04","n_fun","n_gcs","right","left",label="raw",   color=STORAGE,es="dashed"),
            E("e05","n_bq", "n_vai","right","left",label="train", color=AI),
            E("e06","n_fun","n_mon","right","left",label="metrics",color="#D1D5DB",es="dotted"),
        ], vx=10, vy=60),
    "prompts": [
        "Create a GCP streaming analytics architecture",
        "Draw a GCP real-time analytics pipeline",
        "GCP streaming: mobile app → Pub/Sub → Cloud Functions → BigQuery + GCS",
        "Show a GCP real-time event processing pipeline",
        "GCP streaming analytics: app events, Pub/Sub, stream processor, BigQuery, Vertex AI",
        "Diagram a GCP streaming data pipeline",
        "GCP: mobile app publishes events to Pub/Sub, Cloud Functions processes and loads to BigQuery",
        "Show GCP real-time analytics with Vertex AI model training",
        "Create a GCP streaming pipeline: events → Pub/Sub → processor → BigQuery + storage",
        "GCP streaming analytics with BigQuery and Vertex AI",
        "Pub/Sub streaming to BigQuery via Cloud Functions on GCP",
        "GCP: real-time event stream from app, Pub/Sub broker, function processor, BigQuery sink",
        "Show a GCP analytics pipeline for real-time user event processing",
        "GCP streaming: app events → Pub/Sub → Cloud Functions → BigQuery and raw GCS",
        "Create a real-time GCP analytics pipeline ending in BigQuery",
        "GCP streaming analytics with ML training from BigQuery using Vertex AI",
        "Show a GCP architecture for streaming event analytics",
        "GCP Pub/Sub to BigQuery streaming with Cloud Functions as processor",
        "GCP: Firebase app sends events to Pub/Sub, Cloud Functions processes and loads to BQ",
        "Real-time GCP analytics: mobile events → Pub/Sub → Functions → BigQuery → Vertex AI",
        "GCP streaming architecture with Cloud Monitoring",
        "Show a GCP real-time data pipeline from mobile app to analytics warehouse",
        "GCP streaming: Firebase app, Pub/Sub, Cloud Functions, BigQuery, GCS archive, Vertex AI",
        "Create a GCP streaming analytics diagram for a mobile application",
        "GCP real-time analytics pipeline from event source to BigQuery",
    ]
})

# ── G15  GCP Vertex AI + Firebase App ────────────────────────────────────────────
SCENARIOS.append({
    "diagram": D("d_g15", "AI-Powered Firebase App",
        nodes=[
            N("n_app",  "roundedRect", 20,175, 130, 70,"Mobile App","#EFF6FF","#4285F4",tc="#1E3A8A",fw="700",zi=1),
            GC("n_fb",  "gcp-firebase",    200,160,"Firebase",    DEV,      zi=1),
            GC("n_fst", "gcp-firestore",   380,160,"Firestore",   FIREST,   zi=1),
            GC("n_fun", "gcp-functions",   560,160,"Cloud Functions",COMPUTE,zi=1),
            GC("n_pub", "gcp-pubsub",      740, 60,"Pub/Sub",     PUBSUB,   zi=1),
            GC("n_vai", "gcp-vertexai",    740,260,"Vertex AI",   AI,       zi=1),
            GC("n_bq",  "gcp-bigquery",    920,160,"BigQuery",    ANALYTICS,zi=1),
            GC("n_mon", "gcp-monitoring", 1100,160,"Monitoring",  MON,      zi=1),
        ],
        edges=[
            E("e01","n_app","n_fb", "right","left",label="auth",   color=DEV,anim=True),
            E("e02","n_app","n_fst","right","left",label="read/write",color=FIREST,anim=True),
            E("e03","n_fst","n_fun","right","left",label="trigger", color=COMPUTE),
            E("e04","n_fun","n_pub","right","left",color=PUBSUB,anim=True),
            E("e05","n_fun","n_vai","right","left",label="predict", color=AI,anim=True),
            E("e06","n_vai","n_bq", "right","left",label="log",     color=ANALYTICS),
            E("e07","n_bq", "n_mon","right","left",label="metrics", color="#D1D5DB",es="dotted"),
        ], vx=10, vy=60, vz=0.85),
    "prompts": [
        "Create a GCP AI-powered Firebase app architecture",
        "Draw a GCP mobile app with Firebase and Vertex AI",
        "GCP: Firebase app → Firestore triggers Cloud Functions → Vertex AI predictions",
        "Show a GCP architecture for an AI-powered mobile app",
        "Firebase app with Vertex AI: auth, Firestore, Functions, Vertex AI predictions",
        "GCP AI app: Firebase auth, Firestore database, Cloud Functions, Vertex AI",
        "Diagram a GCP mobile app with machine learning via Vertex AI",
        "Show Firestore triggering Cloud Functions that call Vertex AI for predictions",
        "Create a GCP diagram for an AI-powered Firebase application",
        "GCP: app uses Firebase, data in Firestore, Functions call Vertex AI for recommendations",
        "Firebase + Vertex AI on GCP: mobile app, auth, Firestore, serverless functions, ML",
        "Show a GCP architecture where Cloud Functions serve ML predictions from Vertex AI",
        "GCP: Firebase auth, Firestore triggers Functions, Functions call Vertex AI, log to BigQuery",
        "Draw a GCP AI app: Firebase, Firestore, Cloud Functions, Vertex AI, BigQuery",
        "GCP mobile app with AI recommendations via Vertex AI",
        "Show how GCP Firebase and Vertex AI work together in a mobile app",
        "GCP: Firebase auth + Firestore data → Cloud Functions → Vertex AI predictions → BigQuery logs",
        "AI-powered GCP app: Firebase, Firestore, serverless functions, Vertex AI endpoint",
        "Create a GCP diagram for a personalization app using Vertex AI",
        "Show a GCP architecture for a mobile app with AI-driven features",
        "Firebase app on GCP with Vertex AI for real-time predictions",
        "GCP: Firestore document changes trigger Cloud Functions which call Vertex AI",
        "Mobile GCP app with Firebase, Cloud Functions, Vertex AI, BigQuery, and monitoring",
        "Draw a GCP Firebase + Vertex AI + BigQuery architecture for an AI app",
        "Show a complete GCP AI-powered mobile application architecture",
    ]
})

# ── G16  GCP Network Architecture ─────────────────────────────────────────────────
SCENARIOS.append({
    "diagram": D("d_g16", "GCP Network Architecture",
        nodes=[
            N("n_users","pill",      20,265,120, 50,"Users","#DBEAFE","#4285F4",tc="#1E3A8A",fw="700",zi=1),
            GC("n_cdn", "gcp-cdn",       200,250,"Cloud CDN",    NETWORK, zi=1),
            GC("n_glb", "gcp-loadbalancer",380,250,"Global LB",  NETWORK, zi=1),
            GC("n_vpc", "gcp-vpc",        560,250,"VPC Network", NETWORK, zi=1),
            GC("n_cr",  "gcp-cloudrun",   740, 80,"Cloud Run",   COMPUTE, zi=1),
            GC("n_gke", "gcp-gke",        740,250,"GKE Private", COMPUTE, zi=1),
            GC("n_sql", "gcp-cloudsql",   740,420,"Cloud SQL Priv",DATABASE,zi=1),
            GC("n_mon", "gcp-monitoring", 920,250,"Cloud Monitor",MON,    zi=1),
            GC("n_cb",  "gcp-cloudbuild", 920, 80,"Cloud Build",  BUILD,  zi=1),
        ],
        edges=[
            E("e01","n_users","n_cdn","right","left"),
            E("e02","n_cdn",  "n_glb","right","left",color=NETWORK),
            E("e03","n_glb",  "n_vpc","right","left",color=NETWORK,anim=True),
            E("e04","n_vpc",  "n_cr", "right","left",color=COMPUTE),
            E("e05","n_vpc",  "n_gke","right","left",color=COMPUTE),
            E("e06","n_vpc",  "n_sql","right","left",color=DATABASE),
            E("e07","n_gke",  "n_sql","right","left",label="private IP",color=DATABASE,es="dashed"),
            E("e08","n_cb",   "n_gke","bottom","top",label="deploy",color=COMPUTE),
            E("e09","n_gke",  "n_mon","right","left",label="metrics",color="#D1D5DB",es="dotted"),
        ], vx=10, vy=40, vz=0.85),
    "prompts": [
        "Create a GCP network architecture diagram",
        "Draw a GCP VPC-based architecture",
        "GCP: CDN → global load balancer → VPC → Cloud Run + GKE + Cloud SQL",
        "Show a GCP network architecture with VPC isolation",
        "GCP VPC diagram with Cloud CDN, global LB, and private services",
        "GCP network: CDN, global load balancer, VPC network, private Cloud Run and GKE",
        "Diagram a GCP architecture with VPC for network isolation",
        "Show a GCP VPC containing Cloud Run, GKE, and Cloud SQL",
        "GCP: Cloud CDN → Global LB → VPC Network → private compute + database",
        "Create a GCP network diagram with VPC-based security",
        "GCP VPC architecture: CDN, LB, VPC, Cloud Run, GKE, Cloud SQL, monitoring",
        "Show how GCP VPC isolates compute and database from the internet",
        "GCP network: users → CDN → global LB → VPC → Cloud Run + GKE → Cloud SQL",
        "Draw a GCP architecture with VPC Network for private compute",
        "GCP VPC-based architecture with Cloud Build for CI/CD",
        "Show a GCP diagram with private subnet using VPC Network",
        "GCP: CDN routes to global LB, LB routes to VPC, VPC contains all compute and data",
        "Create a GCP network architecture with private services in VPC",
        "GCP VPC diagram with Cloud Run, GKE, and Cloud SQL in private network",
        "Show a GCP architecture where services communicate via VPC private IPs",
        "GCP: global CDN, load balancer, VPC isolation, Cloud Build deployment",
        "GCP network architecture with VPC, private GKE, and Cloud SQL",
        "Draw a GCP diagram with network isolation using VPC",
        "GCP: Cloud Build deploys to GKE inside VPC, GKE uses Cloud SQL via private IP",
        "Show a secure GCP network architecture with VPC and private services",
    ]
})
